// Code generated by MockGen. DO NOT EDIT.
// Source: ./hydra.go
//
// Generated by this command:
//
//	mockgen -package mock -source ./hydra.go -destination ./mock/mock_hydra.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	hydra "github.com/openbkn-ai/bkn-comm-go/hydra"
	gomock "go.uber.org/mock/gomock"
)

// MockHydra is a mock of Hydra interface.
type MockHydra struct {
	ctrl     *gomock.Controller
	recorder *MockHydraMockRecorder
	isgomock struct{}
}

// MockHydraMockRecorder is the mock recorder for MockHydra.
type MockHydraMockRecorder struct {
	mock *MockHydra
}

// NewMockHydra creates a new mock instance.
func NewMockHydra(ctrl *gomock.Controller) *MockHydra {
	mock := &MockHydra{ctrl: ctrl}
	mock.recorder = &MockHydraMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHydra) EXPECT() *MockHydraMockRecorder {
	return m.recorder
}

// Introspect mocks base method.
func (m *MockHydra) Introspect(ctx context.Context, token string) (hydra.TokenIntrospectInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Introspect", ctx, token)
	ret0, _ := ret[0].(hydra.TokenIntrospectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Introspect indicates an expected call of Introspect.
func (mr *MockHydraMockRecorder) Introspect(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Introspect", reflect.TypeOf((*MockHydra)(nil).Introspect), ctx, token)
}

// VerifyToken mocks base method.
func (m *MockHydra) VerifyToken(ctx context.Context, c *gin.Context) (hydra.Visitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", ctx, c)
	ret0, _ := ret[0].(hydra.Visitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockHydraMockRecorder) VerifyToken(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockHydra)(nil).VerifyToken), ctx, c)
}
