# must be unique in a given SonarQube Server instance
sonar.projectKey=ontology-query

sonar.language=go

sonar.go.version=1.24

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.inclusions=**/*.go

sonar.coverage.exclusions=**/main.go,**/errors/**,**/mock/**,**/common/**,**/*_test.go,**/interfaces/**

sonar.go.tests.reportPaths=report/ut_report.xml

sonar.go.coverage.reportPaths=report/ut_coverage.out

# Not configured for now: SonarQube requires golangci-lint out-format=checkstyle, which conflicts with the junit-xml format required by DevOps.
# sonar.go.golangci-lint.reportPaths=report/lint_report.xml
