# Code generated by cmd/ptc-stub. DO NOT EDIT.
# 重新生成：make -C infra/sandbox bkn-tools
__toolkit_version__ = "sha256:b31a3d93d195d4eed3299f6c5cdb3c76f4c62c8950bafae26254ce0ff1eb5805"

# Copyright openbkn.ai
#
# Licensed under the Apache License, Version 2.0.
# See the LICENSE file in the project root for details.

"""Sandbox stub for BKN capabilities, generated by Context Loader.

_configure(event) injects credentials and lifecycle context before execution.
"""

import json
import os
import pathlib
import sys
import urllib.request

_CFG = {}
_SESSION = {}

# 最近几次调用返回值的形状。脚本抛异常时随 traceback 一并打出——代码模式下调用方
# 必须先写出取值路径再执行，猜错时 traceback 只说 "NoneType is not iterable"，不说
# 真实结构，于是整整一轮被用来 print 原始数据找字段名，而那又把数据灌回了上下文，
# 正好抵消代码模式省上下文的意义。这里只记形状不记值。
_SHAPES = []
_SHAPE_LIMIT = 6

# /workspace is shared by all calls. Create and enter a conversation-specific
# subdirectory so scripts can use relative paths without crossing sessions.
WORKDIR = pathlib.Path("/workspace")

# The MCP endpoint is in-cluster. A inherited proxy would make urllib issue an
# absolute-form request that the gateway rejects, so disable proxies explicitly.
_OPENER = urllib.request.build_opener(urllib.request.ProxyHandler({}))


class ToolError(RuntimeError):
    """A tool invocation failed; message contains the server response."""


def _configure(event):
    """Inject MCP endpoint, credentials, and lifecycle context; prepare workdir."""
    _install_shape_hook()
    global WORKDIR
    _CFG.update(event)
    _SESSION.clear()

    # Use an ASCII-only normalization instead of a hash. run_shell must derive
    # the same directory outside this stub, and Python's isalnum accepts Unicode
    # while the Go implementation intentionally does not.
    _SAFE = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"
    conversation = str((event.get("bkn") or {}).get("conversation_id") or "").strip()
    safe = "".join(c if c in _SAFE else "-" for c in conversation)[:64]
    candidate = pathlib.Path("/workspace") / ("conv-" + safe if safe else "shared")
    try:
        candidate.mkdir(parents=True, exist_ok=True)
        os.chdir(candidate)
        WORKDIR = candidate
    except OSError:
        # Keep the script runnable when the sandbox workdir is not writable.
        WORKDIR = pathlib.Path(os.getcwd())


def _rpc(method, params=None, notify=False):
    body = {"jsonrpc": "2.0", "method": method}
    if params is not None:
        body["params"] = params
    if not notify:
        body["id"] = _SESSION.get("seq", 0) + 1
        _SESSION["seq"] = body["id"]
    headers = {
    "Content-Type": "application/json",
    "Accept": "application/json, text/event-stream",
    "Accept-Language": _CFG.get("locale", "zh-CN"),
    "Authorization": "Bearer " + _CFG["token"],
    }
    if _SESSION.get("id"):
        headers["Mcp-Session-Id"] = _SESSION["id"]
    request = urllib.request.Request(
        _CFG["mcp"], data=json.dumps(body).encode(),
        headers=headers, method="POST",
    )
    response = _OPENER.open(request, timeout=_CFG.get("timeout", 120))
    if not _SESSION.get("id"):
        _SESSION["id"] = response.headers.get("Mcp-Session-Id")
    raw = response.read().decode()
    if not raw.strip():
        return None
    for line in raw.splitlines():
        if line.startswith("data: "):
            return json.loads(line[6:])
    return json.loads(raw)


def _ensure_session():
    """Reuse one MCP session per execution and initialize it at most once."""
    if _SESSION.get("ready"):
        return
    _rpc("initialize", {
        "protocolVersion": "2025-06-18",
        "capabilities": {},
        "clientInfo": {"name": "bkn-sandbox", "version": "1"},
    })
    _rpc("notifications/initialized", {}, notify=True)
    _SESSION["ready"] = True


def _call(tool, args):
    """Call an MCP tool, omitting None so the server applies schema defaults."""
    _ensure_session()
    payload = {k: v for k, v in args.items() if v is not None}
    # Business tools require bkn_context, which the caller supplies implicitly.
    if _CFG.get("bkn"):
        payload["bkn_context"] = _CFG["bkn"]

    result = _rpc("tools/call", {"name": tool, "arguments": payload})["result"]
    text = "".join(c["text"] for c in result["content"] if c["type"] == "text")
    if result.get("isError") or result.get("is_error"):
        raise ToolError(tool + ": " + text)
    try:
        value = json.loads(text)
    except json.JSONDecodeError:
        # Return non-JSON representations, such as response_format=toon, unchanged.
        return text
    _remember_shape(tool, value)
    return value


def _describe(value, depth=0):
    """把一个值压成形状描述。只留键名与条数，不留值。

    深到 3 层：顶层 dict -> 数组 -> 元素 dict 的键名。字段名多半就在最后那层
    （nodes[].object_type_name、object_types[].concept_name），折在前面就白记了。
    """
    if isinstance(value, dict):
        if depth >= 3:
            return "{%d 键}" % len(value)
        inner = ", ".join(
            "%s: %s" % (k, _describe(v, depth + 1)) for k, v in list(value.items())[:12]
        )
        more = ", …共 %d 键" % len(value) if len(value) > 12 else ""
        return "{" + inner + more + "}"
    if isinstance(value, list):
        if not value:
            return "[]"
        return "[%d × %s]" % (len(value), _describe(value[0], depth + 1))
    return type(value).__name__


def _remember_shape(tool, value):
    _SHAPES.append((tool, _describe(value)))
    del _SHAPES[:-_SHAPE_LIMIT]


def _shape_report():
    """给失败的执行附上最近几次调用的返回结构。"""
    if not _SHAPES:
        return ""
    lines = ["", "[最近的返回结构——按这个改，不必再跑一轮把数据打出来找字段名]"]
    lines += ["  %s -> %s" % (tool, shape) for tool, shape in _SHAPES]
    return "\n".join(lines)


def _install_shape_hook():
    """让脚本失败时带上最近几次调用的返回结构。

    要挂两处，因为沙箱的两套 wrapper 对异常的处理不一样：

      - subprocess runner 直接 `result = handler(event)`，异常未捕获，走 excepthook；
      - bwrap runner 把它包在 try/except 里，打完 traceback 后 sys.exit(1)，
        excepthook 永远不会被调用。

    只挂 excepthook 的话，这段在开了 bwrap 的部署上完全不生效——而那是生产配置。
    所以同时接管 sys.exit：非零退出即视为失败。

    装在 stub 而不是 wrapper 里：wrapper 有三处实现（服务端 /mcp/ptc、studio、
    沙箱 SDK），且改 wrapper 等于让沙箱运行时去认识 BKN 的东西。
    """
    if getattr(sys, "_bkn_shape_hook", False):
        return

    def emit():
        report = _shape_report()
        if report:
            sys.stderr.write(report + "\n")

    previous_hook = sys.excepthook

    def hook(kind, value, tb):
        previous_hook(kind, value, tb)
        emit()

    previous_exit = sys.exit

    def guarded_exit(code=0):
        # 只在失败时补报告：成功退出时它是噪音，而 stderr 会原样回到调用方。
        if code:
            emit()
        previous_exit(code)

    sys.excepthook = hook
    sys.exit = guarded_exit
    sys._bkn_shape_hook = True

def list_knowledge_networks(direction: str = None, limit: int = None, name_pattern: str = None, offset: int = None, response_format: str = 'json', sort: str = None) -> dict:
    """列出可用的知识网络（返回 kn_id、名称、描述）。其余查询工具均需 kn_id，作为探索的第一步入口。

    direction: 排序方向，默认 desc

    limit: 单页数量，默认 20

    name_pattern: 按知识网络名称模糊过滤，可选

    offset: 偏移量，用于翻页，默认 0

    response_format: 文本格式：json 或 toon，默认 toon

    sort: 排序字段，默认 update_time
    """
    return _call("list_knowledge_networks", {"direction": direction, "limit": limit, "name_pattern": name_pattern, "offset": offset, "response_format": response_format, "sort": sort})


def get_kn_detail(kn_id: str, detail_level: str = 'summary', response_format: str = 'json') -> dict:
    """获取知识网络 schema（概念组、对象类型含 data_source.id、关系类型、行动类型）。默认 detail_level=summary：返回骨架 + 每个属性仅 name+type（不含 display_name/comment/字段映射/查询算子/映射规则）——足够理解结构与规划查询，体积小。需要某对象的完整字段映射（含 comment）时调 get_object_types，需要关系的 mapping_rules 时调 get_relation_types。detail_level=full 一次拿全量（体积大，慎用）。对象类条目附带 related_metric_count（该对象类下已建模指标数），用来判断是否值得下钻取指标。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    detail_level: 详情级别。summary（默认）：对象类/关系类/行动类骨架 + 每个属性仅 name+type（扁平同构，TOON 渲染成紧凑表格），不含 display_name/comment/字段映射/查询算子/映射规则，足够理解 schema 与规划查询；需要某对象完整字段映射（含 comment）改调 get_object_types，要关系 mapping_rules 改调 get_relation_types。full：一次返回全量（体积大，慎用）。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("get_kn_detail", {"kn_id": kn_id, "detail_level": detail_level, "response_format": response_format})


def search_schema(kn_id: str, query: str, enable_rerank: bool = True, include_columns: bool = False, max_concepts: int = 10, response_format: str = 'json', schema_brief: bool = True, search_scope: dict = None) -> dict:
    """统一的 Schema 探索入口，先锁定对象类（object_types）。根据 query 返回相关 object_types、relation_types、action_types、metric_types，供 query_*、find_*、get_* 工具继续消费；其中 metric_types 只是辅助线索，指标的权威清单以 get_object_types 返回的 related_metrics 为准（按对象类 scope 全量枚举）。默认返回精简 Schema（schema_brief=true：保留 data_source.id 与属性 name/type，并只列索引带来的算子 match/multi_match/knn，省约 70%），够规划查询；需要属性备注/主键/标签的完整 Schema 时传 schema_brief=false。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    query: 用户查询问题或关键词，多个关键词之间用空格隔开

    enable_rerank: 是否对关系类型启用 Rerank

    include_columns: 是否在每个对象类的 data_property 上额外返回物理列名 column（取自 mapped_field）。写 run_sql 时列名要用 column（物理列），而非 name（逻辑名）——二者可不同，且同一资源可被多个对象类用不同逻辑名映射。默认 false 以保持响应精简，准备写 SQL 时再开启。

    max_concepts: Schema 候选规模上限

    response_format: 文本格式：json 或 toon，默认 toon

    schema_brief: 是否返回精简 Schema（MCP 默认 true）。精简版保留写查询所需的 data_source.id 与属性 name/type，省去属性 comment、主键、标签，体积约省 70%；需要属性备注、主键或标签时显式传 false。注意：condition_operations 不受本开关影响——MCP 面两种模式下都只列**索引带来的**算子（match / multi_match / knn，取决于该字段建没建全文/向量索引，从属性类型推不出来），没有这类能力的字段不带这个键。比较算子（==、!=、in、like、range 等）按属性 type 自行判断，服务端不下发，详见 query_object_instance 的 condition 说明。

    search_scope: Schema 探索范围。至少需要开启一种概念类型；不传时默认四类全开。concept_groups 用于按 BKN 概念分组限定 Schema 召回范围。
    """
    return _call("search_schema", {"kn_id": kn_id, "query": query, "enable_rerank": enable_rerank, "include_columns": include_columns, "max_concepts": max_concepts, "response_format": response_format, "schema_brief": schema_brief, "search_scope": search_scope})


def get_object_types(ids: list, kn_id: str, response_format: str = 'json') -> dict:
    """按 id 批量取对象类的完整定义（data_properties 含 mapped_field/condition_operations，logic_properties 含 data_source/parameters），并返回该对象类下可用的指标 related_metrics（scope_type=object_type 且 scope_ref=对象类 id，含未绑逻辑属性的指标）。渐进式下钻用：先 get_kn_detail（summary）拿对象 id，再用本工具展开需要的对象。选定指标后：实例级且已绑逻辑属性走 get_logic_properties_values，类级或未绑的走 query_metric。ids 支持多个，一次取回；未匹配的 id 会在 missing 返回。

    ids: 要展开的对象类 id（取自 get_kn_detail summary 的 object_types[].id，也接受 name）。支持多个，一次批量取回。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("get_object_types", {"ids": ids, "kn_id": kn_id, "response_format": response_format})


def get_relation_types(ids: list, kn_id: str, response_format: str = 'json') -> dict:
    """按 id 批量取关系类的完整定义（含 mapping_rules、source/target 对象名）。渐进式下钻用：先 get_kn_detail（summary）拿关系 id，再用本工具展开。ids 支持多个，一次取回；未匹配的 id 会在 missing 返回。

    ids: 要展开的关系类 id（取自 get_kn_detail summary 的 relation_types[].id，也接受 name）。支持多个，一次批量取回。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("get_relation_types", {"ids": ids, "kn_id": kn_id, "response_format": response_format})


def search_instance(query: str, concept_groups: list = None, include_object_types: bool = True, kn_id: str = None, max_instances_per_type: int = 5, max_object_types: int = 10, rerank: bool = False, response_format: str = 'json') -> dict:
    """用一句自然语言直接召回实例，不需要先知道对象类和字段名。先按 query 锁定相关对象类，再在这些对象类上做语义实例召回（向量 + 全文两路并发，按名次融合），返回实例行**以及读懂它们所需的对象类精简定义**（只含真正出了实例的那几个），因此单次调用就够用，不必再回头查 Schema。适合「这句话说的是哪几条数据」这类取数起点；只想了解网络里有哪些结构、不取数时用 search_schema，已经知道对象类和过滤条件时用 query_object_instance。只有 condition_operations 含 match / knn 的属性参与召回，因此没建索引的对象类不会出实例。默认按名次融合排序；传 rerank=true 可让 cross-encoder 逐条判断相关性并重排，能分辨「欠款」与「还款」这类融合分不出的语义差异，代价是多一次模型调用。

    query: 自然语言问题或关键词。整句直接传，不必拆成字段条件——向量通道吃整句，全文通道由分析器分词。

    concept_groups: 限定召回范围到指定的 BKN 概念分组；不传则在整个知识网络内召回。

    include_object_types: 是否附带命中对象类的精简定义（属性名与类型），默认附带。关掉只在你已经拿着这些对象类的 Schema 时才划算——否则要读懂返回的实例还得再调一次 get_object_types。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    max_instances_per_type: 每个对象类最多返回几条实例。

    max_object_types: 参与实例召回的对象类数量上限。调大能覆盖更多对象类，代价是每多一个对象类多一轮下游查询。

    rerank: 是否对召回结果做语义精排。默认关。开启后由 cross-encoder 逐条判断 query 与实例的相关性并**重排返回顺序**——它能分辨「欠款」与「还款」这类名次融合分不出的差异。代价是多一次模型调用（约 100~400ms），且要求部署里注册了精排小模型；模型不可用时自动退回原顺序，不报错。要精度就开，要快就别开。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("search_instance", {"query": query, "concept_groups": concept_groups, "include_object_types": include_object_types, "kn_id": kn_id, "max_instances_per_type": max_instances_per_type, "max_object_types": max_object_types, "rerank": rerank, "response_format": response_format})


def query_object_instance(kn_id: str, ot_id: str, condition: dict = None, filters: list = None, include_logic_params: bool = None, limit: int = None, offset: int = None, properties: list = None, response_format: str = 'json', search_after: list = None, sort: list = None) -> dict:
    """单对象类实例过滤查询。已知对象类与过滤条件时，查询实例列表。支持 search_after 游标顺序翻页（用上一页返回的 search_after 取下一页，不支持跳页）。 文本检索按字段能力选算子：condition_operations 含 match 的字段可做全文模糊匹配，含 knn 的字段可做向量语义检索（自然语言、跨语言、换个说法都能召回，需配 limit_key=k + limit_value）；两者都要就用 or 把子条件并起来。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    ot_id: 对象类型ID

    condition: 过滤条件。operation 必填。比较算子配 field + value + value_from（value 与 value_from 必须同时出现，value_from 仅支持 const）；逻辑算子（and/or）配 sub_conditions 递归嵌套同结构条件。无过滤条件时可整体省略 condition。
算子分两类，判断依据不同：
① 比较算子按属性 type 自行判断，不会出现在 condition_operations 里。字符串类（string/keyword/text）：== != in not_in > >= < <= like not_like regex；数值/日期时间类：== != in not_in > >= < <= range out_range（不支持 like/regex）；exist / not_exist 任意类型可用，且不带 value。
② 索引算子以属性的 condition_operations 为准：含 match 才能全文匹配，含 knn 才能向量检索——它们取决于绑定资源上这个字段建没建全文/向量索引，从 type 推不出来。属性上没有 condition_operations 这个键，只说明该字段没建索引，不代表它不能过滤。condition_operations 里的 multi_match 只是「建了全文索引」的标记，本工具不支持该算子，用 match。
value 形状：单值算子用单值；in / not_in 用数组；range 用 [min, max]，两端都闭；out_range 同样用 [min, max]，排除这个闭区间；exist / not_exist 不传 value。knn 另需 limit_key=k + limit_value=<近邻数>。
like / not_like 的 value 是字面子串，不是 SQL LIKE 模式：直接给要包含的文字，不要自己拼 %；未转义的 % 会被拒（要匹配 % 字符本身写 \\%），_ 按普通字符处理。regex 的锚定随资源存储而变：索引路径是整串全匹配，表类资源翻成不加锚的 SQL 正则（MariaDB `REGEXP`、PostgreSQL `~`）是搜索语义，所以「包含」一律写 .*词.*（两条路都成立）。字符串比较是否区分大小写同样由存储决定：索引路径区分，表类资源随列的排序规则（常见的 utf8mb4_*_ci 不区分），== / like / regex 都受影响，别拿大小写当筛选条件。

    filters: 扁平过滤简写：多个条件按 and 组合，等价于手写 condition 的 and 嵌套。覆盖最常见的「字段 op 值 [AND ...]」场景。与 condition 互斥（同传时 condition 优先）；需要 or 或多层嵌套时改用 condition。算子选择与取值规则同 condition：比较算子按属性 type 判断，match 以属性的 condition_operations 为准；like/not_like 的值是字面子串（不要自己拼 %，未转义的 % 会被拒），regex 的锚定与大小写敏感性随资源存储而变（「包含」写 .*词.*）。不带值的 exist/not_exist 与要配 limit_key/limit_value 的 knn 走不通这条简写，用 condition 写。

    include_logic_params: 是否返回逻辑属性计算参数

    limit: 单页返回数量，默认 10，范围 1-10000

    offset: 偏移翻页（资源/vega 表源路径）：跳过前 N 条，支持跳到任意页。与 search_after 互斥（同传时 search_after 优先）。

    properties: 指定返回的对象属性字段列表，默认返回所有属性

    response_format: 文本格式：json 或 toon，默认 toon

    search_after: 游标分页（对象索引/数据视图路径）：传上一次响应返回的 search_after 取下一页；首次不传。仅顺翻，不跳页。

    sort: 排序字段，按数组顺序依次比较（前一个相等才看后一个）。不传则由服务端按默认序返回，默认序不保证语义（不是「最新」也不是「最相关」），所以「最近的 N 条」「金额最高的 N 个」这类问题必须显式传 sort，不能靠 limit 截默认序。field 必须是该对象类的属性名，用 search_schema 或 get_object_types 确认后再传。
    """
    return _call("query_object_instance", {"kn_id": kn_id, "ot_id": ot_id, "condition": condition, "filters": filters, "include_logic_params": include_logic_params, "limit": limit, "offset": offset, "properties": properties, "response_format": response_format, "search_after": search_after, "sort": sort})


def query_instance_subgraph(kn_id: str, relation_type_paths: list, include_logic_params: bool = None, response_format: str = 'json') -> dict:
    """沿关系路径拉取实例子图，支持多跳关系查询。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    relation_type_paths: 关系路径模板。object_types 与 relation_types 的顺序必须严格对应：n 跳路径 => object_types 长度为 n+1，relation_types 长度为 n；relation_types 不可为空。节点上的过滤条件取值规则：like/not_like 是字面子串（不要自己拼 %，未转义的 % 会被拒），regex 的锚定与大小写敏感性随资源存储而变（「包含」写 .*词.*）

    include_logic_params: 是否返回逻辑属性计算参数，默认 false

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("query_instance_subgraph", {"kn_id": kn_id, "relation_type_paths": relation_type_paths, "include_logic_params": include_logic_params, "response_format": response_format})


def explore_subgraph(direction: str, kn_id: str, path_length: int, source_object_type_id: str, concept_groups: list = None, condition: dict = None, include_incomplete_path: bool = False, include_logic_params: bool = None, limit: int = None, offset: int = None, response_format: str = 'json', search_after: list = None, sort: list = None) -> dict:
    """从一个起点对象类出发，按方向与跳数探索关联子图，不需要预先知道路径。

    direction: 探索方向。forward 只沿关系定义的出边走，backward 只沿入边走，bidirectional 两个方向都走。不确定关系是怎么定义的就用 bidirectional。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    path_length: 最大跳数，取 1-3，超出返回 400。路径数随跳数快速增长，先从 1-2 起步，不够再加。

    source_object_type_id: 探索起点的对象类 ID。用 search_schema 或 get_object_types 先确认。

    concept_groups: 概念分组 ID 数组，把探索范围限定在这些分组内的概念上。不传则不限范围。

    condition: 起点对象类的过滤条件，结构与 query_object_instance 的 condition 完全一致（operation 必填；比较算子配 field + value + value_from=const；and/or 配 sub_conditions 递归嵌套）。只作用于**起点**，不过滤路径上的其他对象类。不传则以该对象类的全部实例为起点（受 limit 限制）。

    include_incomplete_path: 是否返回残缺路径——已走过至少一条边、但没走满 path_length 就无路可走的那些。默认 false 只返回完整路径。想知道「到底连到了哪儿为止」时打开。零边路径任何情况下都不返回。

    include_logic_params: 是否返回逻辑属性的计算参数，默认 false

    limit: **起点对象类**的实例数量上限，默认 10。不是返回路径的条数上限，也不是对象总数上限。

    offset: **起点对象类**的偏移翻页：跳过前 N 个起点。与 search_after 互斥。

    response_format: 文本格式：json 或 toon，默认 toon

    search_after: **起点对象类**的游标翻页：传上一次响应返回的 search_after 取下一批起点；首次不传。与 offset 互斥。

    sort: **起点对象类**的排序字段，按数组顺序依次比较。与 limit 配合决定「从哪些起点出发」，不影响路径本身的顺序。
    """
    return _call("explore_subgraph", {"direction": direction, "kn_id": kn_id, "path_length": path_length, "source_object_type_id": source_object_type_id, "concept_groups": concept_groups, "condition": condition, "include_incomplete_path": include_incomplete_path, "include_logic_params": include_logic_params, "limit": limit, "offset": offset, "response_format": response_format, "search_after": search_after, "sort": sort})


def get_logic_properties_values(_instance_identities: list, kn_id: str, ot_id: str, properties: list, query: str, additional_context: str = None, llm_model: str = None, response_format: str = 'json') -> dict:
    """逻辑属性解析（指标/算子）。针对实例批量计算已绑逻辑属性的值——指标路径里对应「实例级 + 已绑 logic property」这一支；类级指标、或未绑逻辑属性的指标改调 query_metric。

    _instance_identities: 对象实例标识数组。必须从 query_object_instance 或 query_instance_subgraph 的 _instance_identity 字段提取，不可臆造。按原顺序组成数组。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    ot_id: 对象类型ID

    properties: 逻辑属性名列表（metric/operator）。必须为 Schema 中存在的逻辑属性

    query: 用户查询，需含时间、统计维度、业务上下文

    additional_context: 可选。补充 timezone、instant、step 等上下文

    llm_model: 可选。覆盖动态参数生成所用大模型；为空走系统默认大模型。仅供测试/验证指定模型。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("get_logic_properties_values", {"_instance_identities": _instance_identities, "kn_id": kn_id, "ot_id": ot_id, "properties": properties, "query": query, "additional_context": additional_context, "llm_model": llm_model, "response_format": response_format})


def run_sql(sql: str, query_timeout: int = None, response_format: str = 'json') -> dict:
    """对知识网络挂载的数据资源执行只读 SQL（MySQL 方言）。标识符需要引用时用反引号；双引号是字符串字面量，不是标识符。注意：已建模指标不要用 SQL 重写口径——指标走 get_object_types 选定后的 query_metric / get_logic_properties_values；run_sql 用于未建成指标的即席聚合与跨表统计。表名用占位符 {{.resource_id}} 引用；vega 会解析成真实表并限量。仅允许单条 SELECT：支持同一 catalog 内的 JOIN、WHERE、GROUP BY/HAVING、ORDER BY、LIMIT 和常用聚合函数；不支持 WITH/CTE、UNION/INTERSECT/EXCEPT、多语句、写入/DDL 和跨目录 join，子查询与窗口函数不在兼容性承诺内。两种拿 resource_id + 物理列的方式：本体路 search_schema（对象类 data_source.id + data_property.column），数据层路 list_resources → describe_resource（直查裸资源，脱离本体）。

    sql: 只读 SQL（MySQL 方言）。标识符需要引用时用反引号；双引号是字符串字面量，不是标识符。表名必须用占位符 {{.<RESOURCE_ID>}} 引用，其中 <RESOURCE_ID> 替换成具体资源 id 的真实值——即 search_schema 返回的 data_source.id，或 list_resources 返回的 resource_id；点可选（{{id}} 与 {{.id}} 等价）。规则：① 禁止原样写 'resource_id'/'.resource_id' 等字面量，必须替换成真实 id；② 一张表对应一个 id，JOIN 多表时每个表用各自不同的 id；③ 列名用物理列名（search_schema 的 data_property.column，需 include_columns=true；或 describe_resource 返回），不是逻辑名。示例 ✗错（两表共用占位、且写成字面量）：FROM {{.resource_id}} g JOIN {{.resource_id}} t ON g.tournament_id=t.tournament_id ；✓对（先 search_schema 取 goals 与 tournaments 各自的 data_source.id，再逐表替换）：SELECT t.tournament_name, g.family_name, COUNT(*) AS c FROM {{.<goals的data_source.id>}} g JOIN {{.<tournaments的data_source.id>}} t ON g.tournament_id=t.tournament_id GROUP BY t.tournament_name, g.family_name ORDER BY c DESC。仅允许单条 SELECT。支持同一 catalog 内的 JOIN、WHERE、GROUP BY/HAVING、ORDER BY、LIMIT 和常用聚合函数（COUNT/SUM/AVG/MIN/MAX）。不支持 WITH / CTE、UNION / INTERSECT / EXCEPT（vega 会以 `VegaBackend.Query.InvalidParameter` 拒绝）、多语句、任何写入与 DDL、跨数据目录 join；子查询和窗口函数不在当前兼容性承诺内，请勿依赖。vega 会自动限量（最多 10000 行）。

    query_timeout: 查询超时（秒），范围 1-3600，默认 60。可选。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("run_sql", {"sql": sql, "query_timeout": query_timeout, "response_format": response_format})


def query_metric(kn_id: str, metric_id: str, analysis_dimensions: list = None, condition: dict = None, fill_null: bool = None, having: dict = None, limit: int = None, order_by: list = None, response_format: str = 'json', time: dict = None) -> dict:
    """按已建模指标的口径取数（OT-first 路径第 3 步）。先 search_schema / get_kn_detail 锁定对象类，再 get_object_types 从 related_metrics 里选定 metric_id，最后调本工具计算——口径写在 MetricDefinition 里，别用 run_sql 自己重写。分流：实例级且已绑逻辑属性的走 get_logic_properties_values；类级、或未绑逻辑属性的走本工具。可选 condition 过滤、analysis_dimensions 拆维、time 取单点或序列。时间窗规则：省略 instant 等同于序列查询，必须给 step；start 与 end 要么都给要么都不给。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    metric_id: 指标 ID，取自 get_object_types 返回的 related_metrics[].id。不要自己编造。

    analysis_dimensions: 分析维度（按维度拆分结果），取值必须来自 related_metrics[].analysis_dimensions。

    condition: 过滤条件，结构与 query_object_instance 的 condition 一致（field / operation / value / value_from，可 and/or 嵌套）。

    fill_null: 区间序列查询时，无数据的步长点是否补空，默认 false。仅对序列查询有效，且必须同时给 time.start 与 time.end。

    having: 对聚合结果过滤

    limit: 返回条数上限

    order_by: 结果排序

    response_format: 文本格式：json 或 toon，默认 toon

    time: 时间窗。指标无时间维度（related_metrics[].time_dimension 为空）时可整体省略。注意：省略 instant 等同于 instant=false（序列查询），此时必须传 step。start 与 end 要么都传要么都不传。
    """
    return _call("query_metric", {"kn_id": kn_id, "metric_id": metric_id, "analysis_dimensions": analysis_dimensions, "condition": condition, "fill_null": fill_null, "having": having, "limit": limit, "order_by": order_by, "response_format": response_format, "time": time})


def get_action_info(at_id: str, kn_id: str, _instance_identities: list = None, response_format: str = 'json') -> dict:
    """行动信息召回。针对对象实例返回可执行行动的工具定义。

    at_id: 行动类型ID

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    _instance_identities: 对象实例标识列表（可选）。每个元素必须从 query_object_instance 或 query_instance_subgraph 的 _instance_identity 字段提取，不可臆造。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("get_action_info", {"at_id": at_id, "kn_id": kn_id, "_instance_identities": _instance_identities, "response_format": response_format})


def execute_action(at_id: str, kn_id: str, _instance_identities: list = None, dynamic_params: dict = None) -> dict:
    """执行行动。先用 get_action_info 获取行动的 dynamic_params schema，再填入真实动态参数值触发执行（异步，返回 execution_id）。同一 kn + 行动类型 + 实例集合与 dynamic_params 在窗口期内重复提交会返回 409，不要重试，改用 get_action_execution 查询已有 execution。

    at_id: 行动类型 ID，由 search_schema 或 get_kn_detail 返回。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    _instance_identities: 目标实例列表；为空时由行动驱动按行动条件扫描全部匹配实例。每个元素需从 query_object_instance 或 query_instance_subgraph 的 _instance_identity 字段提取，不可臆造。

    dynamic_params: 行动的动态参数值（对应行动类型中 value_from=input 的参数）。请先调用 get_action_info 获取该行动的 dynamic_params schema 与参数名，再在此按名逐个填入真实值。注意：每个参数是独立的键，不要把多个参数名拼成一个键。
    """
    return _call("execute_action", {"at_id": at_id, "kn_id": kn_id, "_instance_identities": _instance_identities, "dynamic_params": dynamic_params})


def get_action_execution(execution_id: str, kn_id: str, response_format: str = 'json') -> dict:
    """查询单次行动执行的状态与结果。用 execute_action 返回的 execution_id 查询整体 status 与逐对象 results。

    execution_id: 行动执行 ID，由 execute_action 返回。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    response_format: 响应格式：json 或 toon，默认 toon（更省 token）。
    """
    return _call("get_action_execution", {"execution_id": execution_id, "kn_id": kn_id, "response_format": response_format})


def list_action_executions(kn_id: str, action_type_id: str = None, limit: int = None, offset: int = None, response_format: str = 'json', search_after: list = None, start_time_from: int = None, start_time_to: int = None, status: str = None, trigger_type: str = None) -> dict:
    """列出行动执行历史，可按行动类型、状态、触发方式过滤并分页。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    action_type_id: 按行动类型 ID 过滤（可选）。

    limit: 分页条数（可选），默认 20，最大 1000。

    offset: 分页偏移（可选）。

    response_format: 响应格式：json 或 toon，默认 toon（更省 token）。

    search_after: 游标分页（可选）：将上一页响应返回的 search_after 原样传入以获取下一页，比 offset 更适合深翻页。

    start_time_from: 起始时间下界（Unix 毫秒，可选）。

    start_time_to: 起始时间上界（Unix 毫秒，可选）。

    status: 按执行状态过滤（可选）：pending/running/completed/failed/cancelled。

    trigger_type: 按触发方式过滤（可选）：manual/scheduled。
    """
    return _call("list_action_executions", {"kn_id": kn_id, "action_type_id": action_type_id, "limit": limit, "offset": offset, "response_format": response_format, "search_after": search_after, "start_time_from": start_time_from, "start_time_to": start_time_to, "status": status, "trigger_type": trigger_type})


def list_resources(catalog_id: str = None, kn_id: str = None, limit: int = None, offset: int = None, response_format: str = 'json', type: str = None) -> dict:
    """数据层资源直查（脱离本体）：列出当前账户有权查看的数据资源（resource_id、name、type、catalog_id）。要「某张知识网络有哪些表」就传 kn_id，一次全返该网络绑定的资源；不传 kn_id 时是账户级资源池分页，可按 catalog_id / type 过滤。资源未建成对象类、或想绕本体直查数据时用。配合 describe_resource + run_sql。

    catalog_id: 可选。限定某数据目录（catalog）下的资源。传了 kn_id 时忽略。

    kn_id: 可选。只列该知识网络已绑定的数据资源（对象类的 data_source）。传了它就一次全返，catalog_id / offset / limit 一律忽略；要「这张网有哪些表」就传它，别用分页去捞。

    limit: 可选。分页大小，默认 20。传了 kn_id 时忽略。

    offset: 可选。分页偏移，默认 0。传了 kn_id 时忽略。

    response_format: 文本格式：json 或 toon，默认 toon

    type: 可选。按资源类别过滤（table / file / fileset / api / metric / topic / index / logicview / dataset）。与 kn_id 同时传时，对该网络绑定的资源生效。
    """
    return _call("list_resources", {"catalog_id": catalog_id, "kn_id": kn_id, "limit": limit, "offset": offset, "response_format": response_format, "type": type})


def describe_resource(resource_id: str, response_format: str = 'json') -> dict:
    """取单个数据资源的物理 schema：connector_type 与列（columns:[{name,type}]）。写 run_sql 前用它拿物理列名。入参 resource_id 取自 list_resources。

    resource_id: 资源 ID（取自 list_resources 的 resource_id）。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("describe_resource", {"resource_id": resource_id, "response_format": response_format})


def find_skills(kn_id: str, object_type_id: str, instance_identities: list = None, response_format: str = 'json', skill_query: str = None, top_k: int = 10) -> dict:
    """技能召回。根据知识网络、对象类型、实例上下文等召回匹配的可用技能列表。

    kn_id: 知识网络 ID。也可改用 X-Kn-ID 请求头传入。

    object_type_id: 对象类型 ID（必填）。当前版本仅支持对象类级或实例级技能召回，且该对象类型必须存在于当前知识网络中

    instance_identities: 实例标识列表（可选）。提供时进一步缩小至具体实例关联的技能

    response_format: 文本格式：json 或 toon，默认 toon

    skill_query: 技能查询关键词（可选）。用于语义匹配过滤技能

    top_k: 返回的最大技能数量，默认 10
    """
    return _call("find_skills", {"kn_id": kn_id, "object_type_id": object_type_id, "instance_identities": instance_identities, "response_format": response_format, "skill_query": skill_query, "top_k": top_k})


def list_skills(category: str = None, name: str = None, page: int = None, page_size: int = None, response_format: str = 'json') -> dict:
    """浏览已发布技能（不需要知识网络上下文）。与 find_skills 互补：那条按对象类/实例召回，这条按名称或分类翻列表。拿到 skill_id 后用 get_skill_content 读 SKILL.md，用 read_skill_file 下钻附属文件，用 execute_skill 执行入口命令。

    category: 可选。按技能分类过滤。

    name: 可选。按技能名称模糊过滤。

    page: 可选。页码，从 1 开始，默认 1。

    page_size: 可选。每页大小，默认 20。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("list_skills", {"category": category, "name": name, "page": page, "page_size": page_size, "response_format": response_format})


def get_skill_content(skill_id: str, response_format: str = 'json') -> dict:
    """读技能主文档 SKILL.md 正文，并返回技能包内的文件清单（files[].rel_path）。技能的用法与入口命令都写在这里；需要哪个附属文件再用 read_skill_file 单取，不必整包读。

    skill_id: 技能 ID（取自 list_skills 或 find_skills 的 skill_id）。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("get_skill_content", {"skill_id": skill_id, "response_format": response_format})


def read_skill_file(rel_path: str, skill_id: str, response_format: str = 'json') -> dict:
    """读技能包内单个文件的正文，rel_path 取自 get_skill_content 返回的 files 清单。渐进式加载用：大文件不必常驻上下文。二进制文件只回元数据不回正文。

    rel_path: 技能包内相对路径，取自 get_skill_content 返回的 files[].rel_path。不接受包外路径（../ 会被拒）。

    skill_id: 技能 ID（取自 list_skills 或 find_skills 的 skill_id）。

    response_format: 文本格式：json 或 toon，默认 toon
    """
    return _call("read_skill_file", {"rel_path": rel_path, "skill_id": skill_id, "response_format": response_format})


__all__ = [
    "list_knowledge_networks",
    "get_kn_detail",
    "search_schema",
    "get_object_types",
    "get_relation_types",
    "search_instance",
    "query_object_instance",
    "query_instance_subgraph",
    "explore_subgraph",
    "get_logic_properties_values",
    "run_sql",
    "query_metric",
    "get_action_info",
    "execute_action",
    "get_action_execution",
    "list_action_executions",
    "list_resources",
    "describe_resource",
    "find_skills",
    "list_skills",
    "get_skill_content",
    "read_skill_file",
    "ToolError",
]
