// Code generated by MockGen. DO NOT EDIT.
// Source: logics_intcomp_config.go
//
// Generated by this command:
//
//	mockgen -source=logics_intcomp_config.go -destination=../mocks/intcomp_config.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIIntCompConfigService is a mock of IIntCompConfigService interface.
type MockIIntCompConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockIIntCompConfigServiceMockRecorder
	isgomock struct{}
}

// MockIIntCompConfigServiceMockRecorder is the mock recorder for MockIIntCompConfigService.
type MockIIntCompConfigServiceMockRecorder struct {
	mock *MockIIntCompConfigService
}

// NewMockIIntCompConfigService creates a new mock instance.
func NewMockIIntCompConfigService(ctrl *gomock.Controller) *MockIIntCompConfigService {
	mock := &MockIIntCompConfigService{ctrl: ctrl}
	mock.recorder = &MockIIntCompConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIntCompConfigService) EXPECT() *MockIIntCompConfigServiceMockRecorder {
	return m.recorder
}

// DeleteConfig mocks base method.
func (m *MockIIntCompConfigService) DeleteConfig(ctx context.Context, tx *sql.Tx, configType, configID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfig", ctx, tx, configType, configID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfig indicates an expected call of DeleteConfig.
func (mr *MockIIntCompConfigServiceMockRecorder) DeleteConfig(ctx, tx, configType, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfig", reflect.TypeOf((*MockIIntCompConfigService)(nil).DeleteConfig), ctx, tx, configType, configID)
}
