// Code generated by MockGen. DO NOT EDIT.
// Source: logics_capability.go
//
// Generated by this command:
//
//	mockgen -source=logics_capability.go -destination=../mocks/logics_capability.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/openbkn-ai/bkn-foundry/adp/execution-factory/operator-integration/server/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockCapabilityIndexSyncService is a mock of CapabilityIndexSyncService interface.
type MockCapabilityIndexSyncService struct {
	ctrl     *gomock.Controller
	recorder *MockCapabilityIndexSyncServiceMockRecorder
	isgomock struct{}
}

// MockCapabilityIndexSyncServiceMockRecorder is the mock recorder for MockCapabilityIndexSyncService.
type MockCapabilityIndexSyncServiceMockRecorder struct {
	mock *MockCapabilityIndexSyncService
}

// NewMockCapabilityIndexSyncService creates a new mock instance.
func NewMockCapabilityIndexSyncService(ctrl *gomock.Controller) *MockCapabilityIndexSyncService {
	mock := &MockCapabilityIndexSyncService{ctrl: ctrl}
	mock.recorder = &MockCapabilityIndexSyncServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapabilityIndexSyncService) EXPECT() *MockCapabilityIndexSyncServiceMockRecorder {
	return m.recorder
}

// DeleteCapability mocks base method.
func (m *MockCapabilityIndexSyncService) DeleteCapability(ctx context.Context, ref interfaces.CapabilityRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCapability", ctx, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCapability indicates an expected call of DeleteCapability.
func (mr *MockCapabilityIndexSyncServiceMockRecorder) DeleteCapability(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCapability", reflect.TypeOf((*MockCapabilityIndexSyncService)(nil).DeleteCapability), ctx, ref)
}

// DeleteOwner mocks base method.
func (m *MockCapabilityIndexSyncService) DeleteOwner(ctx context.Context, capabilityType, ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOwner", ctx, capabilityType, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOwner indicates an expected call of DeleteOwner.
func (mr *MockCapabilityIndexSyncServiceMockRecorder) DeleteOwner(ctx, capabilityType, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOwner", reflect.TypeOf((*MockCapabilityIndexSyncService)(nil).DeleteOwner), ctx, capabilityType, ownerID)
}

// EnsureInitialized mocks base method.
func (m *MockCapabilityIndexSyncService) EnsureInitialized(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureInitialized", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureInitialized indicates an expected call of EnsureInitialized.
func (mr *MockCapabilityIndexSyncServiceMockRecorder) EnsureInitialized(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureInitialized", reflect.TypeOf((*MockCapabilityIndexSyncService)(nil).EnsureInitialized), ctx)
}

// Init mocks base method.
func (m *MockCapabilityIndexSyncService) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockCapabilityIndexSyncServiceMockRecorder) Init(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockCapabilityIndexSyncService)(nil).Init), ctx)
}

// ListIndexed mocks base method.
func (m *MockCapabilityIndexSyncService) ListIndexed(ctx context.Context, capabilityType string) ([]interfaces.IndexedCapability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexed", ctx, capabilityType)
	ret0, _ := ret[0].([]interfaces.IndexedCapability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexed indicates an expected call of ListIndexed.
func (mr *MockCapabilityIndexSyncServiceMockRecorder) ListIndexed(ctx, capabilityType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexed", reflect.TypeOf((*MockCapabilityIndexSyncService)(nil).ListIndexed), ctx, capabilityType)
}

// ListIndexedByOwner mocks base method.
func (m *MockCapabilityIndexSyncService) ListIndexedByOwner(ctx context.Context, capabilityType, ownerID string) ([]interfaces.IndexedCapability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexedByOwner", ctx, capabilityType, ownerID)
	ret0, _ := ret[0].([]interfaces.IndexedCapability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexedByOwner indicates an expected call of ListIndexedByOwner.
func (mr *MockCapabilityIndexSyncServiceMockRecorder) ListIndexedByOwner(ctx, capabilityType, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexedByOwner", reflect.TypeOf((*MockCapabilityIndexSyncService)(nil).ListIndexedByOwner), ctx, capabilityType, ownerID)
}

// UpsertCapability mocks base method.
func (m *MockCapabilityIndexSyncService) UpsertCapability(ctx context.Context, doc *interfaces.CapabilityDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCapability", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCapability indicates an expected call of UpsertCapability.
func (mr *MockCapabilityIndexSyncServiceMockRecorder) UpsertCapability(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCapability", reflect.TypeOf((*MockCapabilityIndexSyncService)(nil).UpsertCapability), ctx, doc)
}

// MockCapabilitySearchService is a mock of CapabilitySearchService interface.
type MockCapabilitySearchService struct {
	ctrl     *gomock.Controller
	recorder *MockCapabilitySearchServiceMockRecorder
	isgomock struct{}
}

// MockCapabilitySearchServiceMockRecorder is the mock recorder for MockCapabilitySearchService.
type MockCapabilitySearchServiceMockRecorder struct {
	mock *MockCapabilitySearchService
}

// NewMockCapabilitySearchService creates a new mock instance.
func NewMockCapabilitySearchService(ctrl *gomock.Controller) *MockCapabilitySearchService {
	mock := &MockCapabilitySearchService{ctrl: ctrl}
	mock.recorder = &MockCapabilitySearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapabilitySearchService) EXPECT() *MockCapabilitySearchServiceMockRecorder {
	return m.recorder
}

// SearchCapabilities mocks base method.
func (m *MockCapabilitySearchService) SearchCapabilities(ctx context.Context, req *interfaces.SearchCapabilitiesReq) (*interfaces.SearchCapabilitiesResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCapabilities", ctx, req)
	ret0, _ := ret[0].(*interfaces.SearchCapabilitiesResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCapabilities indicates an expected call of SearchCapabilities.
func (mr *MockCapabilitySearchServiceMockRecorder) SearchCapabilities(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCapabilities", reflect.TypeOf((*MockCapabilitySearchService)(nil).SearchCapabilities), ctx, req)
}
