apiVersion: v1
kind: Service
metadata:
  name: {{ include "otelcol-contrib.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "otelcol-contrib.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "otelcol-contrib.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.service.ports.http }}
      targetPort: otlp-http
      protocol: TCP
