apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.moduleName }}
  namespace: {{ .Values.namespace }}
  labels:
    module: {{ .Values.moduleName }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    module: {{ .Values.moduleName }}
  ports:
    - name: {{ .Values.moduleName }}
      port: {{ .Values.service.bknBackend.port }}
      protocol: TCP
      targetPort: backend
