// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/resource_data_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/resource_data_service.go -destination ../interfaces/mock/mock_resource_data_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockResourceDataService is a mock of ResourceDataService interface.
type MockResourceDataService struct {
	ctrl     *gomock.Controller
	recorder *MockResourceDataServiceMockRecorder
	isgomock struct{}
}

// MockResourceDataServiceMockRecorder is the mock recorder for MockResourceDataService.
type MockResourceDataServiceMockRecorder struct {
	mock *MockResourceDataService
}

// NewMockResourceDataService creates a new mock instance.
func NewMockResourceDataService(ctrl *gomock.Controller) *MockResourceDataService {
	mock := &MockResourceDataService{ctrl: ctrl}
	mock.recorder = &MockResourceDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceDataService) EXPECT() *MockResourceDataServiceMockRecorder {
	return m.recorder
}

// QueryWithPaging mocks base method.
func (m *MockResourceDataService) QueryWithPaging(ctx context.Context, resource *interfaces.Resource, params *interfaces.ResourceDataQueryParams) (*interfaces.ResourceDataQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWithPaging", ctx, resource, params)
	ret0, _ := ret[0].(*interfaces.ResourceDataQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWithPaging indicates an expected call of QueryWithPaging.
func (mr *MockResourceDataServiceMockRecorder) QueryWithPaging(ctx, resource, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithPaging", reflect.TypeOf((*MockResourceDataService)(nil).QueryWithPaging), ctx, resource, params)
}
