// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/resource_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/resource_access.go -destination ../interfaces/mock/mock_resource_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockResourceAccess is a mock of ResourceAccess interface.
type MockResourceAccess struct {
	ctrl     *gomock.Controller
	recorder *MockResourceAccessMockRecorder
	isgomock struct{}
}

// MockResourceAccessMockRecorder is the mock recorder for MockResourceAccess.
type MockResourceAccessMockRecorder struct {
	mock *MockResourceAccess
}

// NewMockResourceAccess creates a new mock instance.
func NewMockResourceAccess(ctrl *gomock.Controller) *MockResourceAccess {
	mock := &MockResourceAccess{ctrl: ctrl}
	mock.recorder = &MockResourceAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceAccess) EXPECT() *MockResourceAccessMockRecorder {
	return m.recorder
}

// AttachListExtensions mocks base method.
func (m *MockResourceAccess) AttachListExtensions(ctx context.Context, params interfaces.ResourcesQueryParams, resources []*interfaces.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachListExtensions", ctx, params, resources)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachListExtensions indicates an expected call of AttachListExtensions.
func (mr *MockResourceAccessMockRecorder) AttachListExtensions(ctx, params, resources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachListExtensions", reflect.TypeOf((*MockResourceAccess)(nil).AttachListExtensions), ctx, params, resources)
}

// CheckExistByCategories mocks base method.
func (m *MockResourceAccess) CheckExistByCategories(ctx context.Context, catalogID string, categories []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistByCategories", ctx, catalogID, categories)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistByCategories indicates an expected call of CheckExistByCategories.
func (mr *MockResourceAccessMockRecorder) CheckExistByCategories(ctx, catalogID, categories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistByCategories", reflect.TypeOf((*MockResourceAccess)(nil).CheckExistByCategories), ctx, catalogID, categories)
}

// Create mocks base method.
func (m *MockResourceAccess) Create(ctx context.Context, tx *sql.Tx, resource *interfaces.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockResourceAccessMockRecorder) Create(ctx, tx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockResourceAccess)(nil).Create), ctx, tx, resource)
}

// DeleteByCatalogID mocks base method.
func (m *MockResourceAccess) DeleteByCatalogID(ctx context.Context, tx *sql.Tx, catalogID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCatalogID", ctx, tx, catalogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCatalogID indicates an expected call of DeleteByCatalogID.
func (mr *MockResourceAccessMockRecorder) DeleteByCatalogID(ctx, tx, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCatalogID", reflect.TypeOf((*MockResourceAccess)(nil).DeleteByCatalogID), ctx, tx, catalogID)
}

// DeleteByIDs mocks base method.
func (m *MockResourceAccess) DeleteByIDs(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDs", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIDs indicates an expected call of DeleteByIDs.
func (mr *MockResourceAccessMockRecorder) DeleteByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDs", reflect.TypeOf((*MockResourceAccess)(nil).DeleteByIDs), ctx, ids)
}

// GetByCatalogID mocks base method.
func (m *MockResourceAccess) GetByCatalogID(ctx context.Context, catalogID string) ([]*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCatalogID", ctx, catalogID)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCatalogID indicates an expected call of GetByCatalogID.
func (mr *MockResourceAccessMockRecorder) GetByCatalogID(ctx, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCatalogID", reflect.TypeOf((*MockResourceAccess)(nil).GetByCatalogID), ctx, catalogID)
}

// GetByID mocks base method.
func (m *MockResourceAccess) GetByID(ctx context.Context, tx *sql.Tx, id string) (*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tx, id)
	ret0, _ := ret[0].(*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockResourceAccessMockRecorder) GetByID(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockResourceAccess)(nil).GetByID), ctx, tx, id)
}

// GetByIDs mocks base method.
func (m *MockResourceAccess) GetByIDs(ctx context.Context, ids []string) ([]*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockResourceAccessMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockResourceAccess)(nil).GetByIDs), ctx, ids)
}

// GetByIDsBasic mocks base method.
func (m *MockResourceAccess) GetByIDsBasic(ctx context.Context, ids []string) ([]*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDsBasic", ctx, ids)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDsBasic indicates an expected call of GetByIDsBasic.
func (mr *MockResourceAccessMockRecorder) GetByIDsBasic(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDsBasic", reflect.TypeOf((*MockResourceAccess)(nil).GetByIDsBasic), ctx, ids)
}

// GetByName mocks base method.
func (m *MockResourceAccess) GetByName(ctx context.Context, catalogID, name string) (*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, catalogID, name)
	ret0, _ := ret[0].(*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockResourceAccessMockRecorder) GetByName(ctx, catalogID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockResourceAccess)(nil).GetByName), ctx, catalogID, name)
}

// List mocks base method.
func (m *MockResourceAccess) List(ctx context.Context, params interfaces.ResourcesQueryParams) ([]*interfaces.Resource, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockResourceAccessMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockResourceAccess)(nil).List), ctx, params)
}

// ListAuthResources mocks base method.
func (m *MockResourceAccess) ListAuthResources(ctx context.Context, params interfaces.AuthResourceQueryParams) ([]*interfaces.AuthResourceEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuthResources", ctx, params)
	ret0, _ := ret[0].([]*interfaces.AuthResourceEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuthResources indicates an expected call of ListAuthResources.
func (mr *MockResourceAccessMockRecorder) ListAuthResources(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuthResources", reflect.TypeOf((*MockResourceAccess)(nil).ListAuthResources), ctx, params)
}

// ListIDs mocks base method.
func (m *MockResourceAccess) ListIDs(ctx context.Context, params interfaces.ResourcesQueryParams) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIDs", ctx, params)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIDs indicates an expected call of ListIDs.
func (mr *MockResourceAccessMockRecorder) ListIDs(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIDs", reflect.TypeOf((*MockResourceAccess)(nil).ListIDs), ctx, params)
}

// Update mocks base method.
func (m *MockResourceAccess) Update(ctx context.Context, tx *sql.Tx, resource *interfaces.Resource, expectedUpdateTime int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, resource, expectedUpdateTime)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockResourceAccessMockRecorder) Update(ctx, tx, resource, expectedUpdateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockResourceAccess)(nil).Update), ctx, tx, resource, expectedUpdateTime)
}

// UpdateDiscoverStatus mocks base method.
func (m *MockResourceAccess) UpdateDiscoverStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDiscoverStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDiscoverStatus indicates an expected call of UpdateDiscoverStatus.
func (mr *MockResourceAccessMockRecorder) UpdateDiscoverStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDiscoverStatus", reflect.TypeOf((*MockResourceAccess)(nil).UpdateDiscoverStatus), ctx, id, status)
}

// UpdateDiscoveryMetadata mocks base method.
func (m *MockResourceAccess) UpdateDiscoveryMetadata(ctx context.Context, tx *sql.Tx, resource *interfaces.Resource, expectedUpdateTime int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDiscoveryMetadata", ctx, tx, resource, expectedUpdateTime)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDiscoveryMetadata indicates an expected call of UpdateDiscoveryMetadata.
func (mr *MockResourceAccessMockRecorder) UpdateDiscoveryMetadata(ctx, tx, resource, expectedUpdateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDiscoveryMetadata", reflect.TypeOf((*MockResourceAccess)(nil).UpdateDiscoveryMetadata), ctx, tx, resource, expectedUpdateTime)
}

// UpdateLocalIndexName mocks base method.
func (m *MockResourceAccess) UpdateLocalIndexName(ctx context.Context, tx *sql.Tx, id, localIndexName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocalIndexName", ctx, tx, id, localIndexName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocalIndexName indicates an expected call of UpdateLocalIndexName.
func (mr *MockResourceAccessMockRecorder) UpdateLocalIndexName(ctx, tx, id, localIndexName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocalIndexName", reflect.TypeOf((*MockResourceAccess)(nil).UpdateLocalIndexName), ctx, tx, id, localIndexName)
}

// UpdateLocalIndexState mocks base method.
func (m *MockResourceAccess) UpdateLocalIndexState(ctx context.Context, tx *sql.Tx, id, localIndexStatus, localIndexName, syncMark string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocalIndexState", ctx, tx, id, localIndexStatus, localIndexName, syncMark)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLocalIndexState indicates an expected call of UpdateLocalIndexState.
func (mr *MockResourceAccessMockRecorder) UpdateLocalIndexState(ctx, tx, id, localIndexStatus, localIndexName, syncMark any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocalIndexState", reflect.TypeOf((*MockResourceAccess)(nil).UpdateLocalIndexState), ctx, tx, id, localIndexStatus, localIndexName, syncMark)
}

// UpdateSemanticMetadata mocks base method.
func (m *MockResourceAccess) UpdateSemanticMetadata(ctx context.Context, tx *sql.Tx, resource *interfaces.Resource, expectedUpdateTime int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSemanticMetadata", ctx, tx, resource, expectedUpdateTime)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSemanticMetadata indicates an expected call of UpdateSemanticMetadata.
func (mr *MockResourceAccessMockRecorder) UpdateSemanticMetadata(ctx, tx, resource, expectedUpdateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSemanticMetadata", reflect.TypeOf((*MockResourceAccess)(nil).UpdateSemanticMetadata), ctx, tx, resource, expectedUpdateTime)
}

// UpdateStatus mocks base method.
func (m *MockResourceAccess) UpdateStatus(ctx context.Context, tx *sql.Tx, id, status, statusMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, tx, id, status, statusMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockResourceAccessMockRecorder) UpdateStatus(ctx, tx, id, status, statusMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockResourceAccess)(nil).UpdateStatus), ctx, tx, id, status, statusMessage)
}
