// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/catalog_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/catalog_access.go -destination ../interfaces/mock/mock_catalog_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockCatalogAccess is a mock of CatalogAccess interface.
type MockCatalogAccess struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogAccessMockRecorder
	isgomock struct{}
}

// MockCatalogAccessMockRecorder is the mock recorder for MockCatalogAccess.
type MockCatalogAccessMockRecorder struct {
	mock *MockCatalogAccess
}

// NewMockCatalogAccess creates a new mock instance.
func NewMockCatalogAccess(ctrl *gomock.Controller) *MockCatalogAccess {
	mock := &MockCatalogAccess{ctrl: ctrl}
	mock.recorder = &MockCatalogAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogAccess) EXPECT() *MockCatalogAccessMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCatalogAccess) Create(ctx context.Context, tx *sql.Tx, catalog *interfaces.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, catalog)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCatalogAccessMockRecorder) Create(ctx, tx, catalog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCatalogAccess)(nil).Create), ctx, tx, catalog)
}

// DeleteByID mocks base method.
func (m *MockCatalogAccess) DeleteByID(ctx context.Context, tx *sql.Tx, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockCatalogAccessMockRecorder) DeleteByID(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockCatalogAccess)(nil).DeleteByID), ctx, tx, id)
}

// GetByID mocks base method.
func (m *MockCatalogAccess) GetByID(ctx context.Context, id string) (*interfaces.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCatalogAccessMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCatalogAccess)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockCatalogAccess) GetByIDs(ctx context.Context, ids []string) ([]*interfaces.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*interfaces.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockCatalogAccessMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockCatalogAccess)(nil).GetByIDs), ctx, ids)
}

// GetByName mocks base method.
func (m *MockCatalogAccess) GetByName(ctx context.Context, name string) (*interfaces.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*interfaces.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockCatalogAccessMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockCatalogAccess)(nil).GetByName), ctx, name)
}

// GetSummariesByIDs mocks base method.
func (m *MockCatalogAccess) GetSummariesByIDs(ctx context.Context, ids []string) ([]*interfaces.CatalogSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummariesByIDs", ctx, ids)
	ret0, _ := ret[0].([]*interfaces.CatalogSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummariesByIDs indicates an expected call of GetSummariesByIDs.
func (mr *MockCatalogAccessMockRecorder) GetSummariesByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummariesByIDs", reflect.TypeOf((*MockCatalogAccess)(nil).GetSummariesByIDs), ctx, ids)
}

// List mocks base method.
func (m *MockCatalogAccess) List(ctx context.Context, params interfaces.CatalogsQueryParams) ([]*interfaces.CatalogSummary, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.CatalogSummary)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCatalogAccessMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCatalogAccess)(nil).List), ctx, params)
}

// ListAuthResources mocks base method.
func (m *MockCatalogAccess) ListAuthResources(ctx context.Context, params interfaces.AuthResourceQueryParams) ([]*interfaces.AuthResourceEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuthResources", ctx, params)
	ret0, _ := ret[0].([]*interfaces.AuthResourceEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuthResources indicates an expected call of ListAuthResources.
func (mr *MockCatalogAccessMockRecorder) ListAuthResources(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuthResources", reflect.TypeOf((*MockCatalogAccess)(nil).ListAuthResources), ctx, params)
}

// ListInternalIDs mocks base method.
func (m *MockCatalogAccess) ListInternalIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInternalIDs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInternalIDs indicates an expected call of ListInternalIDs.
func (mr *MockCatalogAccessMockRecorder) ListInternalIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInternalIDs", reflect.TypeOf((*MockCatalogAccess)(nil).ListInternalIDs), ctx)
}

// ListPermissionRefs mocks base method.
func (m *MockCatalogAccess) ListPermissionRefs(ctx context.Context, params interfaces.CatalogsQueryParams) ([]interfaces.CatalogPermissionRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissionRefs", ctx, params)
	ret0, _ := ret[0].([]interfaces.CatalogPermissionRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissionRefs indicates an expected call of ListPermissionRefs.
func (mr *MockCatalogAccessMockRecorder) ListPermissionRefs(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissionRefs", reflect.TypeOf((*MockCatalogAccess)(nil).ListPermissionRefs), ctx, params)
}

// Update mocks base method.
func (m *MockCatalogAccess) Update(ctx context.Context, tx *sql.Tx, catalog *interfaces.Catalog, expectedUpdateTime int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, catalog, expectedUpdateTime)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCatalogAccessMockRecorder) Update(ctx, tx, catalog, expectedUpdateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCatalogAccess)(nil).Update), ctx, tx, catalog, expectedUpdateTime)
}

// UpdateEnabled mocks base method.
func (m *MockCatalogAccess) UpdateEnabled(ctx context.Context, id string, enabled bool, status interfaces.CatalogHealthCheckStatus, updateTime int64, updater interfaces.AccountInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnabled", ctx, id, enabled, status, updateTime, updater)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEnabled indicates an expected call of UpdateEnabled.
func (mr *MockCatalogAccessMockRecorder) UpdateEnabled(ctx, id, enabled, status, updateTime, updater any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnabled", reflect.TypeOf((*MockCatalogAccess)(nil).UpdateEnabled), ctx, id, enabled, status, updateTime, updater)
}

// UpdateHealthCheckStatus mocks base method.
func (m *MockCatalogAccess) UpdateHealthCheckStatus(ctx context.Context, id string, status interfaces.CatalogHealthCheckStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHealthCheckStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHealthCheckStatus indicates an expected call of UpdateHealthCheckStatus.
func (mr *MockCatalogAccessMockRecorder) UpdateHealthCheckStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHealthCheckStatus", reflect.TypeOf((*MockCatalogAccess)(nil).UpdateHealthCheckStatus), ctx, id, status)
}

// UpdateMetadata mocks base method.
func (m *MockCatalogAccess) UpdateMetadata(ctx context.Context, id string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", ctx, id, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockCatalogAccessMockRecorder) UpdateMetadata(ctx, id, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockCatalogAccess)(nil).UpdateMetadata), ctx, id, metadata)
}
