// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/catalog_health_check_schedule_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/catalog_health_check_schedule_access.go -destination ../interfaces/mock/mock_catalog_health_check_schedule_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockCatalogHealthCheckScheduleAccess is a mock of CatalogHealthCheckScheduleAccess interface.
type MockCatalogHealthCheckScheduleAccess struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogHealthCheckScheduleAccessMockRecorder
	isgomock struct{}
}

// MockCatalogHealthCheckScheduleAccessMockRecorder is the mock recorder for MockCatalogHealthCheckScheduleAccess.
type MockCatalogHealthCheckScheduleAccessMockRecorder struct {
	mock *MockCatalogHealthCheckScheduleAccess
}

// NewMockCatalogHealthCheckScheduleAccess creates a new mock instance.
func NewMockCatalogHealthCheckScheduleAccess(ctrl *gomock.Controller) *MockCatalogHealthCheckScheduleAccess {
	mock := &MockCatalogHealthCheckScheduleAccess{ctrl: ctrl}
	mock.recorder = &MockCatalogHealthCheckScheduleAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogHealthCheckScheduleAccess) EXPECT() *MockCatalogHealthCheckScheduleAccessMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCatalogHealthCheckScheduleAccess) Create(ctx context.Context, tx *sql.Tx, schedule *interfaces.CatalogHealthCheckSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCatalogHealthCheckScheduleAccessMockRecorder) Create(ctx, tx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCatalogHealthCheckScheduleAccess)(nil).Create), ctx, tx, schedule)
}

// DeleteByCatalogIDs mocks base method.
func (m *MockCatalogHealthCheckScheduleAccess) DeleteByCatalogIDs(ctx context.Context, tx *sql.Tx, catalogIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCatalogIDs", ctx, tx, catalogIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCatalogIDs indicates an expected call of DeleteByCatalogIDs.
func (mr *MockCatalogHealthCheckScheduleAccessMockRecorder) DeleteByCatalogIDs(ctx, tx, catalogIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCatalogIDs", reflect.TypeOf((*MockCatalogHealthCheckScheduleAccess)(nil).DeleteByCatalogIDs), ctx, tx, catalogIDs)
}

// GetByCatalogID mocks base method.
func (m *MockCatalogHealthCheckScheduleAccess) GetByCatalogID(ctx context.Context, catalogID string) (*interfaces.CatalogHealthCheckSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCatalogID", ctx, catalogID)
	ret0, _ := ret[0].(*interfaces.CatalogHealthCheckSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCatalogID indicates an expected call of GetByCatalogID.
func (mr *MockCatalogHealthCheckScheduleAccessMockRecorder) GetByCatalogID(ctx, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCatalogID", reflect.TypeOf((*MockCatalogHealthCheckScheduleAccess)(nil).GetByCatalogID), ctx, catalogID)
}

// ListDue mocks base method.
func (m *MockCatalogHealthCheckScheduleAccess) ListDue(ctx context.Context, now int64) ([]*interfaces.CatalogHealthCheckSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDue", ctx, now)
	ret0, _ := ret[0].([]*interfaces.CatalogHealthCheckSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDue indicates an expected call of ListDue.
func (mr *MockCatalogHealthCheckScheduleAccessMockRecorder) ListDue(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDue", reflect.TypeOf((*MockCatalogHealthCheckScheduleAccess)(nil).ListDue), ctx, now)
}

// Update mocks base method.
func (m *MockCatalogHealthCheckScheduleAccess) Update(ctx context.Context, schedule *interfaces.CatalogHealthCheckSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCatalogHealthCheckScheduleAccessMockRecorder) Update(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCatalogHealthCheckScheduleAccess)(nil).Update), ctx, schedule)
}

// UpdateInheritedNextRun mocks base method.
func (m *MockCatalogHealthCheckScheduleAccess) UpdateInheritedNextRun(ctx context.Context, now, nextRun int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInheritedNextRun", ctx, now, nextRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInheritedNextRun indicates an expected call of UpdateInheritedNextRun.
func (mr *MockCatalogHealthCheckScheduleAccessMockRecorder) UpdateInheritedNextRun(ctx, now, nextRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInheritedNextRun", reflect.TypeOf((*MockCatalogHealthCheckScheduleAccess)(nil).UpdateInheritedNextRun), ctx, now, nextRun)
}

// UpdateRunMetadata mocks base method.
func (m *MockCatalogHealthCheckScheduleAccess) UpdateRunMetadata(ctx context.Context, catalogID string, scheduleUpdateTime, lastRun, nextRun int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunMetadata", ctx, catalogID, scheduleUpdateTime, lastRun, nextRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunMetadata indicates an expected call of UpdateRunMetadata.
func (mr *MockCatalogHealthCheckScheduleAccessMockRecorder) UpdateRunMetadata(ctx, catalogID, scheduleUpdateTime, lastRun, nextRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunMetadata", reflect.TypeOf((*MockCatalogHealthCheckScheduleAccess)(nil).UpdateRunMetadata), ctx, catalogID, scheduleUpdateTime, lastRun, nextRun)
}
