// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/discover_task_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/discover_task_service.go -destination ../interfaces/mock/mock_discover_task_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockDiscoverTaskService is a mock of DiscoverTaskService interface.
type MockDiscoverTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoverTaskServiceMockRecorder
	isgomock struct{}
}

// MockDiscoverTaskServiceMockRecorder is the mock recorder for MockDiscoverTaskService.
type MockDiscoverTaskServiceMockRecorder struct {
	mock *MockDiscoverTaskService
}

// NewMockDiscoverTaskService creates a new mock instance.
func NewMockDiscoverTaskService(ctrl *gomock.Controller) *MockDiscoverTaskService {
	mock := &MockDiscoverTaskService{ctrl: ctrl}
	mock.recorder = &MockDiscoverTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoverTaskService) EXPECT() *MockDiscoverTaskServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDiscoverTaskService) Create(ctx context.Context, req *interfaces.CreateDiscoverTaskRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDiscoverTaskServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDiscoverTaskService)(nil).Create), ctx, req)
}

// DeleteByIDs mocks base method.
func (m *MockDiscoverTaskService) DeleteByIDs(ctx context.Context, ids []string, ignoreMissing bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDs", ctx, ids, ignoreMissing)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIDs indicates an expected call of DeleteByIDs.
func (mr *MockDiscoverTaskServiceMockRecorder) DeleteByIDs(ctx, ids, ignoreMissing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDs", reflect.TypeOf((*MockDiscoverTaskService)(nil).DeleteByIDs), ctx, ids, ignoreMissing)
}

// DispatchSignal mocks base method.
func (m *MockDiscoverTaskService) DispatchSignal() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchSignal")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// DispatchSignal indicates an expected call of DispatchSignal.
func (mr *MockDiscoverTaskServiceMockRecorder) DispatchSignal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchSignal", reflect.TypeOf((*MockDiscoverTaskService)(nil).DispatchSignal))
}

// GetByID mocks base method.
func (m *MockDiscoverTaskService) GetByID(ctx context.Context, id string) (*interfaces.DiscoverTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.DiscoverTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDiscoverTaskServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDiscoverTaskService)(nil).GetByID), ctx, id)
}

// InternalGetByID mocks base method.
func (m *MockDiscoverTaskService) InternalGetByID(ctx context.Context, id string) (*interfaces.DiscoverTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.DiscoverTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalGetByID indicates an expected call of InternalGetByID.
func (mr *MockDiscoverTaskServiceMockRecorder) InternalGetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetByID", reflect.TypeOf((*MockDiscoverTaskService)(nil).InternalGetByID), ctx, id)
}

// InternalList mocks base method.
func (m *MockDiscoverTaskService) InternalList(ctx context.Context, params interfaces.DiscoverTaskQueryParams) ([]*interfaces.DiscoverTaskSummary, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalList", ctx, params)
	ret0, _ := ret[0].([]*interfaces.DiscoverTaskSummary)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InternalList indicates an expected call of InternalList.
func (mr *MockDiscoverTaskServiceMockRecorder) InternalList(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalList", reflect.TypeOf((*MockDiscoverTaskService)(nil).InternalList), ctx, params)
}

// InternalMarkCancelled mocks base method.
func (m *MockDiscoverTaskService) InternalMarkCancelled(ctx context.Context, id, message string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkCancelled", ctx, id, message)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkCancelled indicates an expected call of InternalMarkCancelled.
func (mr *MockDiscoverTaskServiceMockRecorder) InternalMarkCancelled(ctx, id, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkCancelled", reflect.TypeOf((*MockDiscoverTaskService)(nil).InternalMarkCancelled), ctx, id, message)
}

// InternalMarkCompleted mocks base method.
func (m *MockDiscoverTaskService) InternalMarkCompleted(ctx context.Context, id string, result *interfaces.DiscoverResult) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkCompleted", ctx, id, result)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkCompleted indicates an expected call of InternalMarkCompleted.
func (mr *MockDiscoverTaskServiceMockRecorder) InternalMarkCompleted(ctx, id, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkCompleted", reflect.TypeOf((*MockDiscoverTaskService)(nil).InternalMarkCompleted), ctx, id, result)
}

// InternalMarkFailed mocks base method.
func (m *MockDiscoverTaskService) InternalMarkFailed(ctx context.Context, id, message string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkFailed", ctx, id, message)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkFailed indicates an expected call of InternalMarkFailed.
func (mr *MockDiscoverTaskServiceMockRecorder) InternalMarkFailed(ctx, id, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkFailed", reflect.TypeOf((*MockDiscoverTaskService)(nil).InternalMarkFailed), ctx, id, message)
}

// InternalMarkRunning mocks base method.
func (m *MockDiscoverTaskService) InternalMarkRunning(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkRunning", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkRunning indicates an expected call of InternalMarkRunning.
func (mr *MockDiscoverTaskServiceMockRecorder) InternalMarkRunning(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkRunning", reflect.TypeOf((*MockDiscoverTaskService)(nil).InternalMarkRunning), ctx, id)
}

// List mocks base method.
func (m *MockDiscoverTaskService) List(ctx context.Context, params interfaces.DiscoverTaskQueryParams) ([]*interfaces.DiscoverTaskSummary, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.DiscoverTaskSummary)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDiscoverTaskServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDiscoverTaskService)(nil).List), ctx, params)
}

// RequestDispatch mocks base method.
func (m *MockDiscoverTaskService) RequestDispatch() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestDispatch")
}

// RequestDispatch indicates an expected call of RequestDispatch.
func (mr *MockDiscoverTaskServiceMockRecorder) RequestDispatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestDispatch", reflect.TypeOf((*MockDiscoverTaskService)(nil).RequestDispatch))
}
