// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/build_task_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/build_task_service.go -destination ../interfaces/mock/mock_build_task_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockBuildTaskService is a mock of BuildTaskService interface.
type MockBuildTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockBuildTaskServiceMockRecorder
	isgomock struct{}
}

// MockBuildTaskServiceMockRecorder is the mock recorder for MockBuildTaskService.
type MockBuildTaskServiceMockRecorder struct {
	mock *MockBuildTaskService
}

// NewMockBuildTaskService creates a new mock instance.
func NewMockBuildTaskService(ctrl *gomock.Controller) *MockBuildTaskService {
	mock := &MockBuildTaskService{ctrl: ctrl}
	mock.recorder = &MockBuildTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildTaskService) EXPECT() *MockBuildTaskServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBuildTaskService) Create(ctx context.Context, req *interfaces.CreateBuildTaskRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBuildTaskServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBuildTaskService)(nil).Create), ctx, req)
}

// DeleteByIDs mocks base method.
func (m *MockBuildTaskService) DeleteByIDs(ctx context.Context, ids []string, ignoreMissing bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDs", ctx, ids, ignoreMissing)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIDs indicates an expected call of DeleteByIDs.
func (mr *MockBuildTaskServiceMockRecorder) DeleteByIDs(ctx, ids, ignoreMissing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDs", reflect.TypeOf((*MockBuildTaskService)(nil).DeleteByIDs), ctx, ids, ignoreMissing)
}

// DispatchSignal mocks base method.
func (m *MockBuildTaskService) DispatchSignal() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchSignal")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// DispatchSignal indicates an expected call of DispatchSignal.
func (mr *MockBuildTaskServiceMockRecorder) DispatchSignal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchSignal", reflect.TypeOf((*MockBuildTaskService)(nil).DispatchSignal))
}

// GetByID mocks base method.
func (m *MockBuildTaskService) GetByID(ctx context.Context, id string) (*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBuildTaskServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBuildTaskService)(nil).GetByID), ctx, id)
}

// InternalGetByCatalogID mocks base method.
func (m *MockBuildTaskService) InternalGetByCatalogID(ctx context.Context, catalogID string) ([]*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetByCatalogID", ctx, catalogID)
	ret0, _ := ret[0].([]*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalGetByCatalogID indicates an expected call of InternalGetByCatalogID.
func (mr *MockBuildTaskServiceMockRecorder) InternalGetByCatalogID(ctx, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetByCatalogID", reflect.TypeOf((*MockBuildTaskService)(nil).InternalGetByCatalogID), ctx, catalogID)
}

// InternalGetByID mocks base method.
func (m *MockBuildTaskService) InternalGetByID(ctx context.Context, id string) (*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalGetByID indicates an expected call of InternalGetByID.
func (mr *MockBuildTaskServiceMockRecorder) InternalGetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetByID", reflect.TypeOf((*MockBuildTaskService)(nil).InternalGetByID), ctx, id)
}

// InternalGetStatusByID mocks base method.
func (m *MockBuildTaskService) InternalGetStatusByID(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetStatusByID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalGetStatusByID indicates an expected call of InternalGetStatusByID.
func (mr *MockBuildTaskServiceMockRecorder) InternalGetStatusByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetStatusByID", reflect.TypeOf((*MockBuildTaskService)(nil).InternalGetStatusByID), ctx, id)
}

// InternalList mocks base method.
func (m *MockBuildTaskService) InternalList(ctx context.Context, params interfaces.BuildTasksQueryParams) ([]*interfaces.BuildTaskSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalList", ctx, params)
	ret0, _ := ret[0].([]*interfaces.BuildTaskSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalList indicates an expected call of InternalList.
func (mr *MockBuildTaskServiceMockRecorder) InternalList(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalList", reflect.TypeOf((*MockBuildTaskService)(nil).InternalList), ctx, params)
}

// InternalMarkCancelled mocks base method.
func (m *MockBuildTaskService) InternalMarkCancelled(ctx context.Context, tx *sql.Tx, id, detail string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkCancelled", ctx, tx, id, detail)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkCancelled indicates an expected call of InternalMarkCancelled.
func (mr *MockBuildTaskServiceMockRecorder) InternalMarkCancelled(ctx, tx, id, detail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkCancelled", reflect.TypeOf((*MockBuildTaskService)(nil).InternalMarkCancelled), ctx, tx, id, detail)
}

// InternalMarkCompleted mocks base method.
func (m *MockBuildTaskService) InternalMarkCompleted(ctx context.Context, tx *sql.Tx, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkCompleted", ctx, tx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkCompleted indicates an expected call of InternalMarkCompleted.
func (mr *MockBuildTaskServiceMockRecorder) InternalMarkCompleted(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkCompleted", reflect.TypeOf((*MockBuildTaskService)(nil).InternalMarkCompleted), ctx, tx, id)
}

// InternalMarkFailed mocks base method.
func (m *MockBuildTaskService) InternalMarkFailed(ctx context.Context, tx *sql.Tx, id, detail string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkFailed", ctx, tx, id, detail)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkFailed indicates an expected call of InternalMarkFailed.
func (mr *MockBuildTaskServiceMockRecorder) InternalMarkFailed(ctx, tx, id, detail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkFailed", reflect.TypeOf((*MockBuildTaskService)(nil).InternalMarkFailed), ctx, tx, id, detail)
}

// InternalMarkRunning mocks base method.
func (m *MockBuildTaskService) InternalMarkRunning(ctx context.Context, tx *sql.Tx, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkRunning", ctx, tx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkRunning indicates an expected call of InternalMarkRunning.
func (mr *MockBuildTaskServiceMockRecorder) InternalMarkRunning(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkRunning", reflect.TypeOf((*MockBuildTaskService)(nil).InternalMarkRunning), ctx, tx, id)
}

// InternalMarkStopped mocks base method.
func (m *MockBuildTaskService) InternalMarkStopped(ctx context.Context, tx *sql.Tx, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkStopped", ctx, tx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkStopped indicates an expected call of InternalMarkStopped.
func (mr *MockBuildTaskServiceMockRecorder) InternalMarkStopped(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkStopped", reflect.TypeOf((*MockBuildTaskService)(nil).InternalMarkStopped), ctx, tx, id)
}

// InternalSetProgress mocks base method.
func (m *MockBuildTaskService) InternalSetProgress(ctx context.Context, tx *sql.Tx, id string, progress interfaces.BuildTaskProgress) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalSetProgress", ctx, tx, id, progress)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalSetProgress indicates an expected call of InternalSetProgress.
func (mr *MockBuildTaskServiceMockRecorder) InternalSetProgress(ctx, tx, id, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalSetProgress", reflect.TypeOf((*MockBuildTaskService)(nil).InternalSetProgress), ctx, tx, id, progress)
}

// List mocks base method.
func (m *MockBuildTaskService) List(ctx context.Context, params interfaces.BuildTasksQueryParams) ([]*interfaces.BuildTaskSummary, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.BuildTaskSummary)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockBuildTaskServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBuildTaskService)(nil).List), ctx, params)
}

// RequestDispatch mocks base method.
func (m *MockBuildTaskService) RequestDispatch() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestDispatch")
}

// RequestDispatch indicates an expected call of RequestDispatch.
func (mr *MockBuildTaskServiceMockRecorder) RequestDispatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestDispatch", reflect.TypeOf((*MockBuildTaskService)(nil).RequestDispatch))
}

// Start mocks base method.
func (m *MockBuildTaskService) Start(ctx context.Context, taskID string, reset bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, taskID, reset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockBuildTaskServiceMockRecorder) Start(ctx, taskID, reset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockBuildTaskService)(nil).Start), ctx, taskID, reset)
}

// Stop mocks base method.
func (m *MockBuildTaskService) Stop(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockBuildTaskServiceMockRecorder) Stop(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockBuildTaskService)(nil).Stop), ctx, taskID)
}
