// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/model_factory_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/model_factory_service.go -destination ../interfaces/mock/mock_model_factory_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockModelFactoryService is a mock of ModelFactoryService interface.
type MockModelFactoryService struct {
	ctrl     *gomock.Controller
	recorder *MockModelFactoryServiceMockRecorder
	isgomock struct{}
}

// MockModelFactoryServiceMockRecorder is the mock recorder for MockModelFactoryService.
type MockModelFactoryServiceMockRecorder struct {
	mock *MockModelFactoryService
}

// NewMockModelFactoryService creates a new mock instance.
func NewMockModelFactoryService(ctrl *gomock.Controller) *MockModelFactoryService {
	mock := &MockModelFactoryService{ctrl: ctrl}
	mock.recorder = &MockModelFactoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelFactoryService) EXPECT() *MockModelFactoryServiceMockRecorder {
	return m.recorder
}

// GetModelByID mocks base method.
func (m *MockModelFactoryService) GetModelByID(ctx context.Context, modelID string) (*interfaces.SmallModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelByID", ctx, modelID)
	ret0, _ := ret[0].(*interfaces.SmallModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelByID indicates an expected call of GetModelByID.
func (mr *MockModelFactoryServiceMockRecorder) GetModelByID(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelByID", reflect.TypeOf((*MockModelFactoryService)(nil).GetModelByID), ctx, modelID)
}

// GetVector mocks base method.
func (m *MockModelFactoryService) GetVector(ctx context.Context, model *interfaces.SmallModel, words []string) ([]*interfaces.VectorResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVector", ctx, model, words)
	ret0, _ := ret[0].([]*interfaces.VectorResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVector indicates an expected call of GetVector.
func (mr *MockModelFactoryServiceMockRecorder) GetVector(ctx, model, words any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVector", reflect.TypeOf((*MockModelFactoryService)(nil).GetVector), ctx, model, words)
}
