// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/user_mgmt_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/user_mgmt_service.go -destination ../interfaces/mock/mock_user_mgmt_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "github.com/openbkn-ai/bkn-foundry/adp/vega/vega-backend/server/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserMgmtService is a mock of UserMgmtService interface.
type MockUserMgmtService struct {
	ctrl     *gomock.Controller
	recorder *MockUserMgmtServiceMockRecorder
	isgomock struct{}
}

// MockUserMgmtServiceMockRecorder is the mock recorder for MockUserMgmtService.
type MockUserMgmtServiceMockRecorder struct {
	mock *MockUserMgmtService
}

// NewMockUserMgmtService creates a new mock instance.
func NewMockUserMgmtService(ctrl *gomock.Controller) *MockUserMgmtService {
	mock := &MockUserMgmtService{ctrl: ctrl}
	mock.recorder = &MockUserMgmtServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserMgmtService) EXPECT() *MockUserMgmtServiceMockRecorder {
	return m.recorder
}

// GetAccountNames mocks base method.
func (m *MockUserMgmtService) GetAccountNames(ctx context.Context, accountInfos []*interfaces.AccountInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountNames", ctx, accountInfos)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAccountNames indicates an expected call of GetAccountNames.
func (mr *MockUserMgmtServiceMockRecorder) GetAccountNames(ctx, accountInfos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountNames", reflect.TypeOf((*MockUserMgmtService)(nil).GetAccountNames), ctx, accountInfos)
}
