// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/semantic_understanding_task_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/semantic_understanding_task_service.go -destination ../interfaces/mock/mock_semantic_understanding_task_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockSemanticUnderstandingTaskService is a mock of SemanticUnderstandingTaskService interface.
type MockSemanticUnderstandingTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockSemanticUnderstandingTaskServiceMockRecorder
	isgomock struct{}
}

// MockSemanticUnderstandingTaskServiceMockRecorder is the mock recorder for MockSemanticUnderstandingTaskService.
type MockSemanticUnderstandingTaskServiceMockRecorder struct {
	mock *MockSemanticUnderstandingTaskService
}

// NewMockSemanticUnderstandingTaskService creates a new mock instance.
func NewMockSemanticUnderstandingTaskService(ctrl *gomock.Controller) *MockSemanticUnderstandingTaskService {
	mock := &MockSemanticUnderstandingTaskService{ctrl: ctrl}
	mock.recorder = &MockSemanticUnderstandingTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemanticUnderstandingTaskService) EXPECT() *MockSemanticUnderstandingTaskServiceMockRecorder {
	return m.recorder
}

// CreateCatalogTask mocks base method.
func (m *MockSemanticUnderstandingTaskService) CreateCatalogTask(ctx context.Context, catalogID string, req *interfaces.CreateSemanticUnderstandingTaskRequest) (*interfaces.SemanticUnderstandingTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCatalogTask", ctx, catalogID, req)
	ret0, _ := ret[0].(*interfaces.SemanticUnderstandingTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCatalogTask indicates an expected call of CreateCatalogTask.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) CreateCatalogTask(ctx, catalogID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCatalogTask", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).CreateCatalogTask), ctx, catalogID, req)
}

// CreateResourceTask mocks base method.
func (m *MockSemanticUnderstandingTaskService) CreateResourceTask(ctx context.Context, resourceID string, req *interfaces.CreateSemanticUnderstandingTaskRequest) (*interfaces.SemanticUnderstandingTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResourceTask", ctx, resourceID, req)
	ret0, _ := ret[0].(*interfaces.SemanticUnderstandingTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResourceTask indicates an expected call of CreateResourceTask.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) CreateResourceTask(ctx, resourceID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResourceTask", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).CreateResourceTask), ctx, resourceID, req)
}

// DeleteByIDs mocks base method.
func (m *MockSemanticUnderstandingTaskService) DeleteByIDs(ctx context.Context, ids []string, ignoreMissing bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDs", ctx, ids, ignoreMissing)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIDs indicates an expected call of DeleteByIDs.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) DeleteByIDs(ctx, ids, ignoreMissing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDs", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).DeleteByIDs), ctx, ids, ignoreMissing)
}

// DispatchSignal mocks base method.
func (m *MockSemanticUnderstandingTaskService) DispatchSignal() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchSignal")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// DispatchSignal indicates an expected call of DispatchSignal.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) DispatchSignal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchSignal", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).DispatchSignal))
}

// GetByID mocks base method.
func (m *MockSemanticUnderstandingTaskService) GetByID(ctx context.Context, id string) (*interfaces.SemanticUnderstandingTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.SemanticUnderstandingTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).GetByID), ctx, id)
}

// InternalGetByID mocks base method.
func (m *MockSemanticUnderstandingTaskService) InternalGetByID(ctx context.Context, id string) (*interfaces.SemanticUnderstandingTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.SemanticUnderstandingTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalGetByID indicates an expected call of InternalGetByID.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) InternalGetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetByID", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).InternalGetByID), ctx, id)
}

// InternalList mocks base method.
func (m *MockSemanticUnderstandingTaskService) InternalList(ctx context.Context, params interfaces.SemanticUnderstandingTaskQueryParams) ([]*interfaces.SemanticUnderstandingTaskSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalList", ctx, params)
	ret0, _ := ret[0].([]*interfaces.SemanticUnderstandingTaskSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalList indicates an expected call of InternalList.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) InternalList(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalList", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).InternalList), ctx, params)
}

// InternalMarkCancelled mocks base method.
func (m *MockSemanticUnderstandingTaskService) InternalMarkCancelled(ctx context.Context, id, failureDetail string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkCancelled", ctx, id, failureDetail)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkCancelled indicates an expected call of InternalMarkCancelled.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) InternalMarkCancelled(ctx, id, failureDetail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkCancelled", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).InternalMarkCancelled), ctx, id, failureDetail)
}

// InternalMarkCompleted mocks base method.
func (m *MockSemanticUnderstandingTaskService) InternalMarkCompleted(ctx context.Context, tx *sql.Tx, id, resultJSON string, confidence float64, confidenceDetailJSON string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkCompleted", ctx, tx, id, resultJSON, confidence, confidenceDetailJSON)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkCompleted indicates an expected call of InternalMarkCompleted.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) InternalMarkCompleted(ctx, tx, id, resultJSON, confidence, confidenceDetailJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkCompleted", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).InternalMarkCompleted), ctx, tx, id, resultJSON, confidence, confidenceDetailJSON)
}

// InternalMarkFailed mocks base method.
func (m *MockSemanticUnderstandingTaskService) InternalMarkFailed(ctx context.Context, id, failureDetail string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkFailed", ctx, id, failureDetail)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkFailed indicates an expected call of InternalMarkFailed.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) InternalMarkFailed(ctx, id, failureDetail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkFailed", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).InternalMarkFailed), ctx, id, failureDetail)
}

// InternalMarkRunning mocks base method.
func (m *MockSemanticUnderstandingTaskService) InternalMarkRunning(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalMarkRunning", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalMarkRunning indicates an expected call of InternalMarkRunning.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) InternalMarkRunning(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalMarkRunning", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).InternalMarkRunning), ctx, id)
}

// InternalSetAgentTaskID mocks base method.
func (m *MockSemanticUnderstandingTaskService) InternalSetAgentTaskID(ctx context.Context, id, agentTaskID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalSetAgentTaskID", ctx, id, agentTaskID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalSetAgentTaskID indicates an expected call of InternalSetAgentTaskID.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) InternalSetAgentTaskID(ctx, id, agentTaskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalSetAgentTaskID", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).InternalSetAgentTaskID), ctx, id, agentTaskID)
}

// InternalSetApplied mocks base method.
func (m *MockSemanticUnderstandingTaskService) InternalSetApplied(ctx context.Context, tx *sql.Tx, id string, applied bool, applyDetailJSON string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalSetApplied", ctx, tx, id, applied, applyDetailJSON)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalSetApplied indicates an expected call of InternalSetApplied.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) InternalSetApplied(ctx, tx, id, applied, applyDetailJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalSetApplied", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).InternalSetApplied), ctx, tx, id, applied, applyDetailJSON)
}

// List mocks base method.
func (m *MockSemanticUnderstandingTaskService) List(ctx context.Context, params interfaces.SemanticUnderstandingTaskQueryParams) ([]*interfaces.SemanticUnderstandingTaskSummary, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.SemanticUnderstandingTaskSummary)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).List), ctx, params)
}

// RequestDispatch mocks base method.
func (m *MockSemanticUnderstandingTaskService) RequestDispatch() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestDispatch")
}

// RequestDispatch indicates an expected call of RequestDispatch.
func (mr *MockSemanticUnderstandingTaskServiceMockRecorder) RequestDispatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestDispatch", reflect.TypeOf((*MockSemanticUnderstandingTaskService)(nil).RequestDispatch))
}
