// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/asynq_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/asynq_access.go -destination ../interfaces/mock/mock_asynq_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	gomock "go.uber.org/mock/gomock"
)

// MockAsynqAccess is a mock of AsynqAccess interface.
type MockAsynqAccess struct {
	ctrl     *gomock.Controller
	recorder *MockAsynqAccessMockRecorder
	isgomock struct{}
}

// MockAsynqAccessMockRecorder is the mock recorder for MockAsynqAccess.
type MockAsynqAccessMockRecorder struct {
	mock *MockAsynqAccess
}

// NewMockAsynqAccess creates a new mock instance.
func NewMockAsynqAccess(ctrl *gomock.Controller) *MockAsynqAccess {
	mock := &MockAsynqAccess{ctrl: ctrl}
	mock.recorder = &MockAsynqAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsynqAccess) EXPECT() *MockAsynqAccessMockRecorder {
	return m.recorder
}

// CreateClient mocks base method.
func (m *MockAsynqAccess) CreateClient() *asynq.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient")
	ret0, _ := ret[0].(*asynq.Client)
	return ret0
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockAsynqAccessMockRecorder) CreateClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockAsynqAccess)(nil).CreateClient))
}

// CreateServer mocks base method.
func (m *MockAsynqAccess) CreateServer() *asynq.Server {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServer")
	ret0, _ := ret[0].(*asynq.Server)
	return ret0
}

// CreateServer indicates an expected call of CreateServer.
func (mr *MockAsynqAccessMockRecorder) CreateServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServer", reflect.TypeOf((*MockAsynqAccess)(nil).CreateServer))
}
