// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/build_task_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/build_task_service.go -destination ../interfaces/mock/mock_build_task_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	asynq "github.com/hibiken/asynq"
	gomock "go.uber.org/mock/gomock"
)

// MockBuildTaskService is a mock of BuildTaskService interface.
type MockBuildTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockBuildTaskServiceMockRecorder
	isgomock struct{}
}

// MockBuildTaskServiceMockRecorder is the mock recorder for MockBuildTaskService.
type MockBuildTaskServiceMockRecorder struct {
	mock *MockBuildTaskService
}

// NewMockBuildTaskService creates a new mock instance.
func NewMockBuildTaskService(ctrl *gomock.Controller) *MockBuildTaskService {
	mock := &MockBuildTaskService{ctrl: ctrl}
	mock.recorder = &MockBuildTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildTaskService) EXPECT() *MockBuildTaskServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBuildTaskService) Create(ctx context.Context, req *interfaces.CreateBuildTaskRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBuildTaskServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBuildTaskService)(nil).Create), ctx, req)
}

// DebugTaskQueue mocks base method.
func (m *MockBuildTaskService) DebugTaskQueue() <-chan *asynq.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebugTaskQueue")
	ret0, _ := ret[0].(<-chan *asynq.Task)
	return ret0
}

// DebugTaskQueue indicates an expected call of DebugTaskQueue.
func (mr *MockBuildTaskServiceMockRecorder) DebugTaskQueue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugTaskQueue", reflect.TypeOf((*MockBuildTaskService)(nil).DebugTaskQueue))
}

// Delete mocks base method.
func (m *MockBuildTaskService) Delete(ctx context.Context, ids []string, ignoreMissing, deleteActiveIndex bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ids, ignoreMissing, deleteActiveIndex)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBuildTaskServiceMockRecorder) Delete(ctx, ids, ignoreMissing, deleteActiveIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBuildTaskService)(nil).Delete), ctx, ids, ignoreMissing, deleteActiveIndex)
}

// GetByID mocks base method.
func (m *MockBuildTaskService) GetByID(ctx context.Context, id string) (*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBuildTaskServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBuildTaskService)(nil).GetByID), ctx, id)
}

// GetByResourceID mocks base method.
func (m *MockBuildTaskService) GetByResourceID(ctx context.Context, resourceID string) (*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByResourceID", ctx, resourceID)
	ret0, _ := ret[0].(*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByResourceID indicates an expected call of GetByResourceID.
func (mr *MockBuildTaskServiceMockRecorder) GetByResourceID(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByResourceID", reflect.TypeOf((*MockBuildTaskService)(nil).GetByResourceID), ctx, resourceID)
}

// InternalGetByCatalogID mocks base method.
func (m *MockBuildTaskService) InternalGetByCatalogID(ctx context.Context, catalogID string) ([]*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetByCatalogID", ctx, catalogID)
	ret0, _ := ret[0].([]*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalGetByCatalogID indicates an expected call of InternalGetByCatalogID.
func (mr *MockBuildTaskServiceMockRecorder) InternalGetByCatalogID(ctx, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetByCatalogID", reflect.TypeOf((*MockBuildTaskService)(nil).InternalGetByCatalogID), ctx, catalogID)
}

// InternalGetByID mocks base method.
func (m *MockBuildTaskService) InternalGetByID(ctx context.Context, id string) (*interfaces.BuildTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.BuildTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalGetByID indicates an expected call of InternalGetByID.
func (mr *MockBuildTaskServiceMockRecorder) InternalGetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetByID", reflect.TypeOf((*MockBuildTaskService)(nil).InternalGetByID), ctx, id)
}

// InternalGetStatus mocks base method.
func (m *MockBuildTaskService) InternalGetStatus(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetStatus", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalGetStatus indicates an expected call of InternalGetStatus.
func (mr *MockBuildTaskServiceMockRecorder) InternalGetStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetStatus", reflect.TypeOf((*MockBuildTaskService)(nil).InternalGetStatus), ctx, id)
}

// InternalList mocks base method.
func (m *MockBuildTaskService) InternalList(ctx context.Context, params interfaces.BuildTasksQueryParams) ([]*interfaces.BuildTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalList", ctx, params)
	ret0, _ := ret[0].([]*interfaces.BuildTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InternalList indicates an expected call of InternalList.
func (mr *MockBuildTaskServiceMockRecorder) InternalList(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalList", reflect.TypeOf((*MockBuildTaskService)(nil).InternalList), ctx, params)
}

// InternalUpdateStatus mocks base method.
func (m *MockBuildTaskService) InternalUpdateStatus(ctx context.Context, tx *sql.Tx, id string, update interfaces.BuildTaskUpdate, allowedStatuses ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tx, id, update}
	for _, a := range allowedStatuses {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InternalUpdateStatus", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalUpdateStatus indicates an expected call of InternalUpdateStatus.
func (mr *MockBuildTaskServiceMockRecorder) InternalUpdateStatus(ctx, tx, id, update any, allowedStatuses ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tx, id, update}, allowedStatuses...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalUpdateStatus", reflect.TypeOf((*MockBuildTaskService)(nil).InternalUpdateStatus), varargs...)
}

// List mocks base method.
func (m *MockBuildTaskService) List(ctx context.Context, params interfaces.BuildTasksQueryParams) ([]*interfaces.BuildTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.BuildTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockBuildTaskServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBuildTaskService)(nil).List), ctx, params)
}

// Start mocks base method.
func (m *MockBuildTaskService) Start(ctx context.Context, taskID string, reset bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, taskID, reset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockBuildTaskServiceMockRecorder) Start(ctx, taskID, reset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockBuildTaskService)(nil).Start), ctx, taskID, reset)
}

// Stop mocks base method.
func (m *MockBuildTaskService) Stop(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockBuildTaskServiceMockRecorder) Stop(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockBuildTaskService)(nil).Stop), ctx, taskID)
}
