// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/condition.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/condition.go -destination ../interfaces/mock/mock_condition.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "github.com/openbkn-ai/bkn-foundry/adp/vega/vega-backend/server/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFilterCondition is a mock of FilterCondition interface.
type MockFilterCondition struct {
	ctrl     *gomock.Controller
	recorder *MockFilterConditionMockRecorder
	isgomock struct{}
}

// MockFilterConditionMockRecorder is the mock recorder for MockFilterCondition.
type MockFilterConditionMockRecorder struct {
	mock *MockFilterCondition
}

// NewMockFilterCondition creates a new mock instance.
func NewMockFilterCondition(ctrl *gomock.Controller) *MockFilterCondition {
	mock := &MockFilterCondition{ctrl: ctrl}
	mock.recorder = &MockFilterConditionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilterCondition) EXPECT() *MockFilterConditionMockRecorder {
	return m.recorder
}

// GetOperation mocks base method.
func (m *MockFilterCondition) GetOperation() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperation")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetOperation indicates an expected call of GetOperation.
func (mr *MockFilterConditionMockRecorder) GetOperation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperation", reflect.TypeOf((*MockFilterCondition)(nil).GetOperation))
}

// IsFixedLenArrayValue mocks base method.
func (m *MockFilterCondition) IsFixedLenArrayValue() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFixedLenArrayValue")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFixedLenArrayValue indicates an expected call of IsFixedLenArrayValue.
func (mr *MockFilterConditionMockRecorder) IsFixedLenArrayValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFixedLenArrayValue", reflect.TypeOf((*MockFilterCondition)(nil).IsFixedLenArrayValue))
}

// IsSingleValue mocks base method.
func (m *MockFilterCondition) IsSingleValue() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSingleValue")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSingleValue indicates an expected call of IsSingleValue.
func (mr *MockFilterConditionMockRecorder) IsSingleValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSingleValue", reflect.TypeOf((*MockFilterCondition)(nil).IsSingleValue))
}

// NeedConstValue mocks base method.
func (m *MockFilterCondition) NeedConstValue() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeedConstValue")
	ret0, _ := ret[0].(bool)
	return ret0
}

// NeedConstValue indicates an expected call of NeedConstValue.
func (mr *MockFilterConditionMockRecorder) NeedConstValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeedConstValue", reflect.TypeOf((*MockFilterCondition)(nil).NeedConstValue))
}

// NeedName mocks base method.
func (m *MockFilterCondition) NeedName() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeedName")
	ret0, _ := ret[0].(bool)
	return ret0
}

// NeedName indicates an expected call of NeedName.
func (mr *MockFilterConditionMockRecorder) NeedName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeedName", reflect.TypeOf((*MockFilterCondition)(nil).NeedName))
}

// NeedValue mocks base method.
func (m *MockFilterCondition) NeedValue() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeedValue")
	ret0, _ := ret[0].(bool)
	return ret0
}

// NeedValue indicates an expected call of NeedValue.
func (mr *MockFilterConditionMockRecorder) NeedValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeedValue", reflect.TypeOf((*MockFilterCondition)(nil).NeedValue))
}

// New mocks base method.
func (m *MockFilterCondition) New(ctx context.Context, cfg *interfaces.FilterCondCfg, fieldsMap map[string]*interfaces.Property) (interfaces.FilterCondition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", ctx, cfg, fieldsMap)
	ret0, _ := ret[0].(interfaces.FilterCondition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockFilterConditionMockRecorder) New(ctx, cfg, fieldsMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockFilterCondition)(nil).New), ctx, cfg, fieldsMap)
}

// RequiredValueLen mocks base method.
func (m *MockFilterCondition) RequiredValueLen() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiredValueLen")
	ret0, _ := ret[0].(int)
	return ret0
}

// RequiredValueLen indicates an expected call of RequiredValueLen.
func (mr *MockFilterConditionMockRecorder) RequiredValueLen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiredValueLen", reflect.TypeOf((*MockFilterCondition)(nil).RequiredValueLen))
}

// SupportSubCond mocks base method.
func (m *MockFilterCondition) SupportSubCond() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportSubCond")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportSubCond indicates an expected call of SupportSubCond.
func (mr *MockFilterConditionMockRecorder) SupportSubCond() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportSubCond", reflect.TypeOf((*MockFilterCondition)(nil).SupportSubCond))
}
