// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/connector_factory.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/connector_factory.go -destination ../interfaces/mock/mock_connector_factory.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockConnectorFactory is a mock of ConnectorFactory interface.
type MockConnectorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorFactoryMockRecorder
	isgomock struct{}
}

// MockConnectorFactoryMockRecorder is the mock recorder for MockConnectorFactory.
type MockConnectorFactoryMockRecorder struct {
	mock *MockConnectorFactory
}

// NewMockConnectorFactory creates a new mock instance.
func NewMockConnectorFactory(ctrl *gomock.Controller) *MockConnectorFactory {
	mock := &MockConnectorFactory{ctrl: ctrl}
	mock.recorder = &MockConnectorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorFactory) EXPECT() *MockConnectorFactoryMockRecorder {
	return m.recorder
}

// CreateConnectorInstance mocks base method.
func (m *MockConnectorFactory) CreateConnectorInstance(ctx context.Context, tp string, cfg interfaces.ConnectorConfig) (interfaces.Connector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConnectorInstance", ctx, tp, cfg)
	ret0, _ := ret[0].(interfaces.Connector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConnectorInstance indicates an expected call of CreateConnectorInstance.
func (mr *MockConnectorFactoryMockRecorder) CreateConnectorInstance(ctx, tp, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConnectorInstance", reflect.TypeOf((*MockConnectorFactory)(nil).CreateConnectorInstance), ctx, tp, cfg)
}

// DeleteConnector mocks base method.
func (m *MockConnectorFactory) DeleteConnector(ctx context.Context, tp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnector", ctx, tp)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConnector indicates an expected call of DeleteConnector.
func (mr *MockConnectorFactoryMockRecorder) DeleteConnector(ctx, tp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnector", reflect.TypeOf((*MockConnectorFactory)(nil).DeleteConnector), ctx, tp)
}

// GetSensitiveFields mocks base method.
func (m *MockConnectorFactory) GetSensitiveFields(tp string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensitiveFields", tp)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSensitiveFields indicates an expected call of GetSensitiveFields.
func (mr *MockConnectorFactoryMockRecorder) GetSensitiveFields(tp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensitiveFields", reflect.TypeOf((*MockConnectorFactory)(nil).GetSensitiveFields), tp)
}

// IsConnectorAvailable mocks base method.
func (m *MockConnectorFactory) IsConnectorAvailable(tp string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnectorAvailable", tp)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnectorAvailable indicates an expected call of IsConnectorAvailable.
func (mr *MockConnectorFactoryMockRecorder) IsConnectorAvailable(tp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnectorAvailable", reflect.TypeOf((*MockConnectorFactory)(nil).IsConnectorAvailable), tp)
}

// RegisterConnector mocks base method.
func (m *MockConnectorFactory) RegisterConnector(ctx context.Context, tp string, ct *interfaces.ConnectorType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterConnector", ctx, tp, ct)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterConnector indicates an expected call of RegisterConnector.
func (mr *MockConnectorFactoryMockRecorder) RegisterConnector(ctx, tp, ct any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterConnector", reflect.TypeOf((*MockConnectorFactory)(nil).RegisterConnector), ctx, tp, ct)
}

// ResolveConnectorTypeRegistration mocks base method.
func (m *MockConnectorFactory) ResolveConnectorTypeRegistration(ctx context.Context, ct *interfaces.ConnectorType) (*interfaces.ConnectorType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveConnectorTypeRegistration", ctx, ct)
	ret0, _ := ret[0].(*interfaces.ConnectorType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveConnectorTypeRegistration indicates an expected call of ResolveConnectorTypeRegistration.
func (mr *MockConnectorFactoryMockRecorder) ResolveConnectorTypeRegistration(ctx, ct any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveConnectorTypeRegistration", reflect.TypeOf((*MockConnectorFactory)(nil).ResolveConnectorTypeRegistration), ctx, ct)
}

// SetConnectorEnabled mocks base method.
func (m *MockConnectorFactory) SetConnectorEnabled(ctx context.Context, tp string, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectorEnabled", ctx, tp, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectorEnabled indicates an expected call of SetConnectorEnabled.
func (mr *MockConnectorFactoryMockRecorder) SetConnectorEnabled(ctx, tp, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectorEnabled", reflect.TypeOf((*MockConnectorFactory)(nil).SetConnectorEnabled), ctx, tp, enabled)
}
