// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/discover_schedule_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/discover_schedule_access.go -destination ../interfaces/mock/mock_discover_schedule_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockDiscoverScheduleAccess is a mock of DiscoverScheduleAccess interface.
type MockDiscoverScheduleAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoverScheduleAccessMockRecorder
	isgomock struct{}
}

// MockDiscoverScheduleAccessMockRecorder is the mock recorder for MockDiscoverScheduleAccess.
type MockDiscoverScheduleAccessMockRecorder struct {
	mock *MockDiscoverScheduleAccess
}

// NewMockDiscoverScheduleAccess creates a new mock instance.
func NewMockDiscoverScheduleAccess(ctrl *gomock.Controller) *MockDiscoverScheduleAccess {
	mock := &MockDiscoverScheduleAccess{ctrl: ctrl}
	mock.recorder = &MockDiscoverScheduleAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoverScheduleAccess) EXPECT() *MockDiscoverScheduleAccessMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDiscoverScheduleAccess) Create(ctx context.Context, schedule *interfaces.DiscoverSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDiscoverScheduleAccessMockRecorder) Create(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).Create), ctx, schedule)
}

// Delete mocks base method.
func (m *MockDiscoverScheduleAccess) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDiscoverScheduleAccessMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).Delete), ctx, id)
}

// DeleteByCatalogID mocks base method.
func (m *MockDiscoverScheduleAccess) DeleteByCatalogID(ctx context.Context, tx *sql.Tx, catalogID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCatalogID", ctx, tx, catalogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCatalogID indicates an expected call of DeleteByCatalogID.
func (mr *MockDiscoverScheduleAccessMockRecorder) DeleteByCatalogID(ctx, tx, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCatalogID", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).DeleteByCatalogID), ctx, tx, catalogID)
}

// GetByID mocks base method.
func (m *MockDiscoverScheduleAccess) GetByID(ctx context.Context, id string) (*interfaces.DiscoverSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.DiscoverSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDiscoverScheduleAccessMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockDiscoverScheduleAccess) List(ctx context.Context, params interfaces.DiscoverScheduleQueryParams) ([]*interfaces.DiscoverSchedule, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.DiscoverSchedule)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDiscoverScheduleAccessMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).List), ctx, params)
}

// ListDue mocks base method.
func (m *MockDiscoverScheduleAccess) ListDue(ctx context.Context, now int64) ([]*interfaces.DiscoverSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDue", ctx, now)
	ret0, _ := ret[0].([]*interfaces.DiscoverSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDue indicates an expected call of ListDue.
func (mr *MockDiscoverScheduleAccessMockRecorder) ListDue(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDue", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).ListDue), ctx, now)
}

// Update mocks base method.
func (m *MockDiscoverScheduleAccess) Update(ctx context.Context, schedule *interfaces.DiscoverSchedule, expectedUpdateTime int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, schedule, expectedUpdateTime)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDiscoverScheduleAccessMockRecorder) Update(ctx, schedule, expectedUpdateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).Update), ctx, schedule, expectedUpdateTime)
}

// UpdateEnabled mocks base method.
func (m *MockDiscoverScheduleAccess) UpdateEnabled(ctx context.Context, id string, enabled bool, nextRun *int64, expectedUpdateTime, updateTime int64, updater interfaces.AccountInfo) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnabled", ctx, id, enabled, nextRun, expectedUpdateTime, updateTime, updater)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEnabled indicates an expected call of UpdateEnabled.
func (mr *MockDiscoverScheduleAccessMockRecorder) UpdateEnabled(ctx, id, enabled, nextRun, expectedUpdateTime, updateTime, updater any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnabled", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).UpdateEnabled), ctx, id, enabled, nextRun, expectedUpdateTime, updateTime, updater)
}

// UpdateRunMetadata mocks base method.
func (m *MockDiscoverScheduleAccess) UpdateRunMetadata(ctx context.Context, id string, expectedUpdateTime, expectedNextRun, lastRun, nextRun int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunMetadata", ctx, id, expectedUpdateTime, expectedNextRun, lastRun, nextRun)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRunMetadata indicates an expected call of UpdateRunMetadata.
func (mr *MockDiscoverScheduleAccessMockRecorder) UpdateRunMetadata(ctx, id, expectedUpdateTime, expectedNextRun, lastRun, nextRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunMetadata", reflect.TypeOf((*MockDiscoverScheduleAccess)(nil).UpdateRunMetadata), ctx, id, expectedUpdateTime, expectedNextRun, lastRun, nextRun)
}
