// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/semantic_understanding_task_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/semantic_understanding_task_access.go -destination ../interfaces/mock/mock_semantic_understanding_task_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockSemanticUnderstandingTaskAccess is a mock of SemanticUnderstandingTaskAccess interface.
type MockSemanticUnderstandingTaskAccess struct {
	ctrl     *gomock.Controller
	recorder *MockSemanticUnderstandingTaskAccessMockRecorder
	isgomock struct{}
}

// MockSemanticUnderstandingTaskAccessMockRecorder is the mock recorder for MockSemanticUnderstandingTaskAccess.
type MockSemanticUnderstandingTaskAccessMockRecorder struct {
	mock *MockSemanticUnderstandingTaskAccess
}

// NewMockSemanticUnderstandingTaskAccess creates a new mock instance.
func NewMockSemanticUnderstandingTaskAccess(ctrl *gomock.Controller) *MockSemanticUnderstandingTaskAccess {
	mock := &MockSemanticUnderstandingTaskAccess{ctrl: ctrl}
	mock.recorder = &MockSemanticUnderstandingTaskAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemanticUnderstandingTaskAccess) EXPECT() *MockSemanticUnderstandingTaskAccessMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) Create(ctx context.Context, task *interfaces.SemanticUnderstandingTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).Create), ctx, task)
}

// DeleteByIDs mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) DeleteByIDs(ctx context.Context, ids []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDs", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByIDs indicates an expected call of DeleteByIDs.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) DeleteByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDs", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).DeleteByIDs), ctx, ids)
}

// FindActiveByInputHash mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) FindActiveByInputHash(ctx context.Context, scope, inputHash string) (*interfaces.SemanticUnderstandingTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByInputHash", ctx, scope, inputHash)
	ret0, _ := ret[0].(*interfaces.SemanticUnderstandingTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByInputHash indicates an expected call of FindActiveByInputHash.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) FindActiveByInputHash(ctx, scope, inputHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByInputHash", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).FindActiveByInputHash), ctx, scope, inputHash)
}

// GetByID mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) GetByID(ctx context.Context, id string) (*interfaces.SemanticUnderstandingTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.SemanticUnderstandingTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) GetByIDs(ctx context.Context, ids []string) ([]*interfaces.SemanticUnderstandingTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*interfaces.SemanticUnderstandingTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).GetByIDs), ctx, ids)
}

// InternalList mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) InternalList(ctx context.Context, params interfaces.SemanticUnderstandingTaskQueryParams) ([]*interfaces.SemanticUnderstandingTaskSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalList", ctx, params)
	ret0, _ := ret[0].([]*interfaces.SemanticUnderstandingTaskSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalList indicates an expected call of InternalList.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) InternalList(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalList", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).InternalList), ctx, params)
}

// List mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) List(ctx context.Context, params interfaces.SemanticUnderstandingTaskQueryParams) ([]*interfaces.SemanticUnderstandingTaskSummary, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.SemanticUnderstandingTaskSummary)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).List), ctx, params)
}

// MarkCancelled mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) MarkCancelled(ctx context.Context, id, failureDetail string, updateTime int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCancelled", ctx, id, failureDetail, updateTime)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkCancelled indicates an expected call of MarkCancelled.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) MarkCancelled(ctx, id, failureDetail, updateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCancelled", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).MarkCancelled), ctx, id, failureDetail, updateTime)
}

// MarkCancelledByCatalogID mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) MarkCancelledByCatalogID(ctx context.Context, tx *sql.Tx, catalogID, failureDetail string, updateTime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCancelledByCatalogID", ctx, tx, catalogID, failureDetail, updateTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCancelledByCatalogID indicates an expected call of MarkCancelledByCatalogID.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) MarkCancelledByCatalogID(ctx, tx, catalogID, failureDetail, updateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCancelledByCatalogID", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).MarkCancelledByCatalogID), ctx, tx, catalogID, failureDetail, updateTime)
}

// MarkCompleted mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) MarkCompleted(ctx context.Context, id, resultJSON string, confidence float64, confidenceDetailJSON string, updateTime int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCompleted", ctx, id, resultJSON, confidence, confidenceDetailJSON, updateTime)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkCompleted indicates an expected call of MarkCompleted.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) MarkCompleted(ctx, id, resultJSON, confidence, confidenceDetailJSON, updateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompleted", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).MarkCompleted), ctx, id, resultJSON, confidence, confidenceDetailJSON, updateTime)
}

// MarkFailed mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) MarkFailed(ctx context.Context, id, failureDetail string, updateTime int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, failureDetail, updateTime)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) MarkFailed(ctx, id, failureDetail, updateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).MarkFailed), ctx, id, failureDetail, updateTime)
}

// MarkRunning mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) MarkRunning(ctx context.Context, id string, updateTime int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRunning", ctx, id, updateTime)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkRunning indicates an expected call of MarkRunning.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) MarkRunning(ctx, id, updateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRunning", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).MarkRunning), ctx, id, updateTime)
}

// SetAgentTaskID mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) SetAgentTaskID(ctx context.Context, id, agentTaskID string, updateTime int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAgentTaskID", ctx, id, agentTaskID, updateTime)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAgentTaskID indicates an expected call of SetAgentTaskID.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) SetAgentTaskID(ctx, id, agentTaskID, updateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAgentTaskID", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).SetAgentTaskID), ctx, id, agentTaskID, updateTime)
}

// SetApplied mocks base method.
func (m *MockSemanticUnderstandingTaskAccess) SetApplied(ctx context.Context, tx *sql.Tx, id string, applied bool, appliedTime int64, applyDetailJSON string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetApplied", ctx, tx, id, applied, appliedTime, applyDetailJSON)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetApplied indicates an expected call of SetApplied.
func (mr *MockSemanticUnderstandingTaskAccessMockRecorder) SetApplied(ctx, tx, id, applied, appliedTime, applyDetailJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetApplied", reflect.TypeOf((*MockSemanticUnderstandingTaskAccess)(nil).SetApplied), ctx, tx, id, applied, appliedTime, applyDetailJSON)
}
