// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/logic_view_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/logic_view_service.go -destination ../interfaces/mock/mock_logic_view_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockLogicViewService is a mock of LogicViewService interface.
type MockLogicViewService struct {
	ctrl     *gomock.Controller
	recorder *MockLogicViewServiceMockRecorder
	isgomock struct{}
}

// MockLogicViewServiceMockRecorder is the mock recorder for MockLogicViewService.
type MockLogicViewServiceMockRecorder struct {
	mock *MockLogicViewService
}

// NewMockLogicViewService creates a new mock instance.
func NewMockLogicViewService(ctrl *gomock.Controller) *MockLogicViewService {
	mock := &MockLogicViewService{ctrl: ctrl}
	mock.recorder = &MockLogicViewServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogicViewService) EXPECT() *MockLogicViewServiceMockRecorder {
	return m.recorder
}

// QueryWithPaging mocks base method.
func (m *MockLogicViewService) QueryWithPaging(ctx context.Context, resource *interfaces.Resource, params *interfaces.ResourceDataQueryParams) (*interfaces.ResourceDataQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWithPaging", ctx, resource, params)
	ret0, _ := ret[0].(*interfaces.ResourceDataQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWithPaging indicates an expected call of QueryWithPaging.
func (mr *MockLogicViewServiceMockRecorder) QueryWithPaging(ctx, resource, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithPaging", reflect.TypeOf((*MockLogicViewService)(nil).QueryWithPaging), ctx, resource, params)
}
