"""Stable Model Factory error envelopes.

The dictionaries remain mutable for compatibility with legacy validation code.
Client-facing text is replaced from the locale catalog before a response leaves
the service, while these defaults keep internal errors in English.
"""

from app.commons.i18n.en_us import error_messages as _EN_US_MESSAGES


_DEFAULT_ERROR = {
    "description": "Request failed.",
    "detail": "The request could not be completed.",
    "solution": "Check the request or contact an administrator.",
}


def _new_error(code):
    message = _EN_US_MESSAGES.get(code, _DEFAULT_ERROR)
    return {
        "code": code,
        "description": message.get("description", _DEFAULT_ERROR["description"]),
        "detail": message.get("detail", _DEFAULT_ERROR["detail"]),
        "solution": message.get("solution", _DEFAULT_ERROR["solution"]),
        "link": "",
    }


_ERROR_CODES = {
    "DataBaseError": "ModelFactory.Mydb.DataBase.ParameterError",
    "LLMSourceError": "ModelFactory.ConnectController.LLMSource.ParameterError",
    "LLMUsedError": "ModelFactory.ConnectController.LLMUsed.ParameterError",
    "LLMParamError": "ModelFactory.ConnectController.LLMUsed.ParameterError",
    "LLMRemoveError": "ModelFactory.ConnectController.LLMRemove.ParameterError",
    "LLMDeployError": "ModelFactory.ConnectController.LLMDeploy.ParameterError",
    "LLMAddError": "ModelFactory.ConnectController.LLMAdd.ParameterError",
    "LLMAdd2Error": "ModelFactory.ConnectController.LLMAdd.ParameterError",
    "LLMEditError": "ModelFactory.ConnectController.LLMEdit.ParameterError",
    "LLMEdit2Error": "ModelFactory.ConnectController.LLMEdit.ParameterError",
    "LLMEdit3Error": "ModelFactory.ConnectController.LLMEdit.ParameterError",
    "LLMEdit4Error": "ModelFactory.ConnectController.LLMEdit.NameError",
    "LLMCheckError": "ModelFactory.ConnectController.LLMCheck.ParameterError",
    "LLMTestError": "ModelFactory.ConnectController.LLMTest.ParameterError",
    "PromptItemSourceError": "ModelFactory.PromptController.PromptItemSource.ParameterError",
    "PromptSourceError": "ModelFactory.PromptController.PromptSource.ParameterError",
    "PromptLLMSourceError": "ModelFactory.PromptController.PromptLLMSourceError.ParameterError",
    "PromptTemplateSource": "ModelFactory.PromptController.PromptTemplateSource.ParameterError",
    "PromptCheck": "ModelFactory.PromptController.PromptCheck.ParameterError",
    "PromptUsed": "ModelFactory.PromptController.PromptUsed.ParameterError",
    "PromptItemAddError1": "ModelFactory.PromptController.PromptItemAdd.ParameterError",
    "PromptItemAddError2": "ModelFactory.PromptController.PromptItemAdd.NameError",
    "PromptItemEditError1": "ModelFactory.PromptController.PromptItemEdit.ParameterError",
    "PromptItemEditError2": "ModelFactory.PromptController.PromptItemEdit.NameError",
    "PromptTypeAddError1": "ModelFactory.PromptController.PromptTypeAdd.ParameterError",
    "PromptTypeAddError2": "ModelFactory.PromptController.PromptTypeAdd.NameError",
    "PromptTypeEditError1": "ModelFactory.PromptController.PromptTypeEdit.ParameterError",
    "PromptTypeEditError2": "ModelFactory.PromptController.PromptTypeEdit.NameError",
    "PromptAddError1": "ModelFactory.PromptController.PromptAdd.ParameterError",
    "PromptAddError2": "ModelFactory.PromptController.PromptAdd.NameError",
    "PromptNameEditError1": "ModelFactory.PromptController.PromptNameEdit.ParameterError",
    "PromptNameEditError2": "ModelFactory.PromptController.PromptNameEdit.NameError",
    "PromptEditError1": "ModelFactory.PromptController.PromptEdit.ParameterError",
    "PromptTemplateEditError1": "ModelFactory.PromptController.PromptTemplateEdit.ParameterError",
    "PromptDeployError1": "ModelFactory.PromptController.PromptDeploy.ParameterError",
    "PromptUndeployError1": "ModelFactory.PromptController.PromptUndeploy.ParameterError",
    "PromptRunError1": "ModelFactory.PromptController.PromptRun.ParameterError",
    "PromptTemplateRunError1": "ModelFactory.PromptController.PromptTemplateRun.ParameterError",
    "PromptConpletionError1": "ModelFactory.PromptController.PromptConpletion.ParameterError",
    "AutoGenerationError1": "ModelFactory.PromptController.AutoGeneration.ParameterError",
    "PromptCodeError1": "ModelFactory.PromptController.PromptCode.ParameterError",
    "PromptDeleteError1": "ModelFactory.PromptController.PromptDelete.ParameterError",
    "PromptMoveError": "ModelFactory.PromptController.PromptMove.ParameterError",
    "PromptDefaultLLMError": "ModelFactory.PromptController.PromptDefaultLLMError",
    "ModelError": "ModelFactory.LLM.Error",
    "BatchAddPromptError": "ModelFactory.PromptController.BatchAddPrompt.Error",
    "ModelTimeoutError": "ModelFactory.LLM.ModelTimeoutError",
    "ModelFactory_BenchmarkController_AddBenchmarkConfig_RepeatedNames_Error": "ModelFactory.BenchmarkController.AddBenchmarkConfig.RepeatedNames",
    "ModelFactory_BenchmarkController_AddBenchmarkConfig_UnknownError_Error": "ModelFactory.BenchmarkController.AddBenchmarkConfig.UnknownError",
    "ModelFactory_MyPymysqlPool_Connection_ConnectError_Error": "ModelFactory.MyPymysqlPool.Connection.ConnectError",
    "ModelFactory_Router_ParamError_ParamMissing_Error": "ModelFactory.Router.ParamError.ParamMissing",
    "ModelFactory_Router_ParamError_FormatError_Error": "ModelFactory.Router.ParamError.FormatError",
    "ModelFactory_Router_ParamError_TypeError_Error": "ModelFactory.Router.ParamError.TypeError",
    "ModelFactory_BenchmarkController_EditBenchmarkConfig_RepeatedNames_Error": "ModelFactory.BenchmarkController.EditBenchmarkConfig.RepeatedNames",
    "ModelFactory_BenchmarkController_EditBenchmarkConfig_UnknownError_Error": "ModelFactory.BenchmarkController.AddBenchmarkConfig.UnknownError",
    "ModelFactory_BenchmarkController_EditBenchmarkConfig_TaskIDNotExist_Error": "ModelFactory.BenchmarkController.EditBenchmarkConfig.TaskIDNotExist",
    "ModelFactory_BenchmarkController_DeleteBenchmarkConfig_UnknownError_Error": "ModelFactory.BenchmarkController.DeleteBenchmarkConfig.UnknownError",
    "ModelFactory_BenchmarkController_PublishBenchmarkConfig_UnknownError_Error": "ModelFactory.BenchmarkController.PublishBenchmarkConfig.UnknownError",
    "ModelFactory_BenchmarkController_EditBenchmarkConfig_IDNotExist_Error": "ModelFactory.BenchmarkController.EditBenchmarkConfig.IDNotExist",
    "ModelFactory_BenchmarkController_EditBenchmarkConfig_ConfigPublished_Error": "ModelFactory.BenchmarkController.EditBenchmarkConfig.ConfigPublished",
    "ModelFactory_BenchmarkController_PublishBenchmarkConfig_IdNotExist_Error": "ModelFactory.BenchmarkController.PublishBenchmarkConfig.IdNotExist",
    "ModelFactory_BenchmarkController_GetBenchmarkConfig_UnknownError_Error": "ModelFactory.BenchmarkController.GetBenchmarkConfig.UnknownError",
    "ModelFactory_BenchmarkController_GetBenchmarkConfig_IDNotExist_Error": "ModelFactory.BenchmarkController.GetBenchmarkConfig.IDNotExist",
    "ModelFactory_BenchmarkController_GetBenchmarkConfigList_UnknownError_Error": "ModelFactory.BenchmarkController.GetBenchmarkConfigList.UnknownError",
    "ModelFactory_BenchmarkController_CopyConfig_UnknownError_Error": "ModelFactory.BenchmarkController.CopyConfig.UnknownError",
    "ModelFactory_BenchmarkController_CopyConfig_IdNotExist_Error": "ModelFactory.BenchmarkController.CopyConfig.IdNotExist",
    "ModelFactory_BenchmarkController_CopyConfig_ConfigNotPublished_Error": "ModelFactory.BenchmarkController.CopyConfig.ConfigNotPublished",
    "ModelFactory_BenchmarkController_AddMetric_UnknownError_Error": "ModelFactory.BenchmarkController.AddMetric.UnknownError",
    "ModelFactory_BenchmarkController_EditMetric_UnknownError_Error": "ModelFactory.BenchmarkController.EditMetric.UnknownError",
    "ModelFactory_BenchmarkController_AddMetric_PathNotExist_Error": "ModelFactory.BenchmarkController.AddMetric.PathNotExist",
    "ModelFactory_BenchmarkController_EditMetric_ColorNotExist_Error": "ModelFactory.BenchmarkController.EditMetric.ColorNotExist",
    "ModelFactory_BenchmarkController_DeleteMetric_UnknownError_Error": "ModelFactory.BenchmarkController.DeleteMetric.UnknownError",
    "ModelFactory_BenchmarkController_GetMetric_UnknownError_Error": "ModelFactory.BenchmarkController.GetMetric.UnknownError",
    "ModelFactory_BenchmarkController_DeleteMetric_MetricIsUsed_Error": "ModelFactory.BenchmarkController.DeleteMetric.MetricIsUsed",
    "ModelFactory_BenchmarkController_GetMetric_IdNotExist_Error": "ModelFactory.BenchmarkController.GetMetric.IdNotExist",
    "ModelFactory_BenchmarkController_GetMetricList_UnknownError_Error": "ModelFactory.BenchmarkController.GetMetricList.UnknownError",
    "ModelFactory_BenchmarkController_FilePreview_UnknownError_Error": "ModelFactory.BenchmarkController.FilePreview.UnknownError",
    "ModelFactory_BenchmarkController_GetMetricTemplate_UnknownError_Error": "ModelFactory.BenchmarkController.GetMetricTemplate.UnknownError",
    "ModelFactory_BenchmarkController_UploadFileStart_UnknownError_Error": "ModelFactory.BenchmarkController.UploadFileStart.UnknownError",
    "ModelFactory_BenchmarkController_UploadFileStart_ConnectError_Error": "ModelFactory.BenchmarkController.UploadFileStart.ConnectError",
    "ModelFactory_BenchmarkController_Download_ConnectError_Error": "ModelFactory.BenchmarkController.Download.ConnectError",
    "ModelFactory_BenchmarkController_Download_UnknownError_Error": "ModelFactory.BenchmarkController.Download.UnknownError",
    "ModelFactory_BenchmarkController_FilePreview_ConnectError_Error": "ModelFactory.BenchmarkController.FilePreview.ConnectError",
    "ModelFactory_BenchmarkController_UploadFileComplete_UnknownError_Error": "ModelFactory.BenchmarkController.UploadFileComplete.UnknownError",
    "ModelFactory_BenchmarkController_ParseMetric_UnknownError_Error": "ModelFactory.BenchmarkController.ParseMetric.UnknownError",
    "ModelFactory_BenchmarkController_ParseMetric_ParseError_Error": "ModelFactory.BenchmarkController.ParseMetric.ParseError",
    "ModelFactory_BenchmarkController_ParseMetric_NameEmpty_Error": "ModelFactory.BenchmarkController.ParseMetric.NameEmpty",
    "ModelFactory_BenchmarkController_ParseMetric_NameTooLong_Error": "ModelFactory.BenchmarkController.ParseMetric.NameTooLong",
    "ModelFactory_BenchmarkController_ParseMetric_NameFormatError_Error": "ModelFactory.BenchmarkController.ParseMetric.NameFormatError",
    "ModelFactory_BenchmarkController_GetAdapterTemplate_UnknownError_Error": "ModelFactory.BenchmarkController.GetAdapterTemplate.UnknownError",
    "ModelFactory_BenchmarkController_DeleteFile_UnknownError_Error": "ModelFactory.BenchmarkController.DeleteFile.UnknownError",
    "ModelFactory_BenchmarkController_DeleteFile_ConnectError_Error": "ModelFactory.BenchmarkController.DeleteFile.ConnectError",
    "ModelFactory_BenchmarkController_PublishBenchmarkConfig_IncompleteConfiguration_Error": "ModelFactory.BenchmarkController.PublishBenchmarkConfig.IncompleteConfiguration",
    "ModelFactory_BenchmarkController_GetSelectList_UnknownError_Error": "ModelFactory.BenchmarkController.GetSelectList.UnknownError",
    "ModelFactory_BenchmarkController_GetMetricOutputMap_UnknownError_Error": "ModelFactory.BenchmarkController.GetMetricOutputMap.UnknownError",
    "ModelFactory_BenchmarkController_AddMetric_RepeatedNames_Error": "ModelFactory.BenchmarkController.AddMetric.RepeatedNames",
    "ModelFactory_BenchmarkController_AddMetric_PromptNotFound_Error": "ModelFactory.BenchmarkController.AddMetric.PromptNotFound",
    "ModelFactory_BenchmarkController_EditMetric_RepeatedNames_Error": "ModelFactory.BenchmarkController.EditMetric.RepeatedNames",
    "ModelFactory_DataSet_PreviewError": "ModelFactory.DataSet.PreviewError",
    "ModelFactory_BenchmarkController_ParseMetric_FileEmpty_Error": "ModelFactory.BenchmarkController.ParseMetric.FileEmpty",
    "ModelFactory_BenchmarkController_DeleteBenchmarkConfig_IDNotExist_Error": "ModelFactory.BenchmarkController.DeleteBenchmarkConfig.IDNotExist",
    "ModelFactory_BenchmarkController_DeleteMetric_IlligalId_Error": "ModelFactory.BenchmarkController.DeleteMetric.IlligalId",
    "ModelFactory_BenchmarkController_ConfigNameUsed_UnknownError_Error": "ModelFactory.BenchmarkController.ConfigNameUsed.UnknownError",
    "ModelFactory_BenchmarkController_ConfigUsedByRunningTask_UnknownError_Error": "ModelFactory.BenchmarkController.ConfigUsedByRunningTask.UnknownError",
    "ModelFactory_BenchmarkController_DownloadInlineMetric_UnknownError_Error": "ModelFactory.BenchmarkController.DownloadInlineMetric.UnknownError",
    "ModelFactory_BenchmarkController_GetConfigByIdList_UnknownError_Error": "ModelFactory.BenchmarkController.GetConfigByIdList.UnknownError",
    "ModelFactory_BenchmarkController_GetMetricByIdList_UnknownError_Error": "ModelFactory.BenchmarkController.GetMetricByIdList.UnknownError",
    "ModelFactory_ModelQuotaController_ModelQuotaConfig_ModelIsAlreadyExist_Error": "ModelFactory.ModelQuotaController.ModelQuotaConfig.ModelIsAlreadyExist",
    "ModelFactory_ModelQuotaController_ModelQuotaConfig_ModelConfigNotFound_Error": "ModelFactory.ModelQuotaController.ModelQuotaConfig.ModelConfigNotFound",
    "ModelFactory_ModelQuotaController_ModelConfig_ModelNotFound_Error": "ModelFactory.ModelQuotaController.ModelConfig.ModelNotFound",
    "ModelFactory_ModelQuotaController_UserModelConfig_NoLeftSpace_Error": "ModelFactory.ModelQuotaController.UserModelConfig.NoLeftSpace",
    "ModelFactory_ModelQuotaController_UserModelConfig_InputNoLeftSpace_Error": "ModelFactory.ModelQuotaController.UserModelConfig.InputNoLeftSpace",
    "ModelFactory_ModelQuotaController_UserModelConfig_OutputNoLeftSpace_Error": "ModelFactory.ModelQuotaController.UserModelConfig.OutputNoLeftSpace",
    "ModelFactory_ModelQuotaController_UserModelConfig_PermissionError_Error": "ModelFactory.ModelQuotaController.UserModelConfig.PermissionError",
    "ModelFactory_ModelQuotaController_UserModelQuotaConfig_ModelConfigIsAlreadyExist_Error": "ModelFactory.ModelQuotaController.UserModelQuotaConfig.ModelIsAlreadyExist",
    "ModelFactory_ModelQuotaController_UserModelQuotaConfig_ModelConfigNotFound_Error": "ModelFactory.ModelQuotaController.UserModelQuotaConfig.ModelNotFound",
    "ModelFactory_ModelQuotaController_AddModelQuotaConfig_UnknownError_Error": "ModelFactory.ModelQuotaController.AddModelQuotaConfig.UnknownError",
    "ModelFactory_ModelQuotaController_AddUserModelQuotaConfig_UnknownError_Error": "ModelFactory.ModelQuotaController.AddUserModelQuotaConfig.UnknownError",
    "UnknownError": "ModelFactory.LLM.UnknownError",
    "EncodeError": "ModelFactory.LLM.EncodeError",
    "DecodeError": "ModelFactory.LLM.DecodeError",
    "EncodeParaError": "ModelFactory.PromptController.EncodeEndPoint.ParameterError",
    "ModelFactory_BenchmarkController_ConfigDatasetViaTemplate_UnknownError_Error": "ModelFactory.BenchmarkController.ConfigDatasetViaTemplate.UnknownError",
    "ModelFactory_BenchmarkController_ConfigDatasetViaTemplate_FileFormatError_Error": "ModelFactory.BenchmarkController.ConfigDatasetViaTemplate.FileFormatError",
    "ModelFactory_BenchmarkController_ConfigDatasetViaTemplate_ConfigTemplateNotExists_Error": "ModelFactory.BenchmarkController.ConfigDatasetViaTemplate.ConfigTemplateNotExists",
    "ModelFactory_BenchmarkController_GetTemplateDatasetFile_UnknownError_Error": "ModelFactory.BenchmarkController.GetTemplateDatasetFile.UnknownError",
    "ModelFactory_BenchmarkController_GetTemplateDatasetFile_ConfigTemplateNotExists_Error": "ModelFactory.BenchmarkController.GetTemplateDatasetFile.ConfigTemplateNotExists",
    "ModelFactory_BenchmarkController_ConfigDatasetViaTemplate_RepeatedNames_Error": "ModelFactory.BenchmarkController.ConfigDatasetViaTemplate.RepeatedNames",
    "DecodeParaError": "ModelFactory.PromptController.DecodeEndPoint.ParameterError",
    "LLMConfigParaError": "ModelFactory.ModelController.LLMConfig.ParameterError",
    "ModelFactory_BenchmarkController_ModelConfig_UnknownError_Error": "ModelFactory.BenchmarkController.ModelConfig.UnknownError",
    "ModelFactory_ModelController_Model_CanNotDelete_Error": "ModelFactory.ModelController.Model.CanNotDelete",
    "LimitsError": "ModelFactory.LimitsError",
    "ModelFactory_ModelUsedAuditController_GetModelArchivingList_OssNotAvailable_Error": "ModelFactory.ModelUsedAuditController.GetModelArchivingList.OssNotAvailable",
    "ModelFactory_ModelController_Model_ConnectError_Error": "ModelFactory.ModelController.Model.ConnectError",
    "ModelFactory_ModelController_Model_Error_Error": "ModelFactory.ModelController.Model.Error",
    "ModelFactory_ModelController_TestModel_Error_Error": "ModelFactory.ModelController.TestModel.Error",
    "ModelFactory_SmallModelRouter_AddSmallModel_ParamError": "ModelFactory.SmallModelRouter.AddSmallModel.ParameterError",
    "ModelFactory_SmallModelController_AddSmallModel_ModelNameDuplicateError": "ModelFactory.SmallModelController.AddSmallModel.ModelNameDuplicateError",
    "ModelFactory_SmallModelController_AddSmallModel_AudioNeedResultURLError": "ModelFactory.SmallModelController.AddSmallModel.AudioNeedResultURLError",
    "ModelFactory_SmallModelController_AddSmallModel_UnknownError": "ModelFactory.SmallModelController.AddSmallModel.UnknownError",
    "ModelFactory_SmallModelRouter_SmallModelList_ParamError": "ModelFactory.SmallModelRouter.SmallModelList.ParameterError",
    "ModelFactory_SmallModelController_SmallModelList_UnknownError": "ModelFactory.SmallModelController.SmallModelList.UnknownError",
    "ModelFactory_SmallModelRouter_SmallModelRun_ParamError": "ModelFactory.SmallModelRouter.SmallModelRun.ParameterError",
    "ModelFactory_SmallModelController_SmallModelRun_ModelNotFoundError": "ModelFactory.SmallModelController.SmallModelRun.ModelNotFoundError",
    "ModelFactory_SmallModelController_SmallModelRun_ModelInferError": "ModelFactory.SmallModelController.SmallModelRun.ModelInferError",
    "ModelFactory_SmallModelController_SmallModelRun_UnknownError": "ModelFactory.SmallModelController.SmallModelRun.UnknownError",
    "ModelFactory_SmallModelRouter_AsyncResult_ParamError": "ModelFactory.SmallModelRouter.AsyncResult.ParameterError",
    "ModelFactory_SmallModelController_AsyncResult_ModelNotFoundError": "ModelFactory.SmallModelController.AsyncResult.ModelNotFoundError",
    "ModelFactory_SmallModelController_AsyncResult_GetResultError": "ModelFactory.SmallModelController.AsyncResult.GetResultError",
    "ModelFactory_SmallModelController_AsyncResult_UnknownError": "ModelFactory.SmallModelController.AsyncResult.UnknownError",
    "ModelFactory_SmallModelRouter_ModelApiDoc_ParamError": "ModelFactory.SmallModelRouter.ModelApiDoc.ParameterError",
    "ModelFactory_SmallModelController_ModelApiDoc_ModelNotFoundError": "ModelFactory.SmallModelController.ModelApiDoc.ModelNotFoundError",
    "ModelFactory_SmallModelController_ModelApiDoc_UnknownError": "ModelFactory.SmallModelController.ModelApiDoc.UnknownError",
    "ModelFactory_CotRouter_AddCotRouter_ParamError": "ModelFactory.CotRouter.AddCotRouter.ParamError",
    "ModelFactory_CotController_AddCot_UnknownError": "ModelFactory.CotController.AddCot.UnknownError",
    "ModelFactory_CotController_GetCot_UnknownError": "ModelFactory.CotController.GetCot.UnknownError",
    "ModelFactory_CotController_AddCot_MissingContentError": "ModelFactory.CotController.AddCot.MissingContentError",
    "ModelFactory_CotController_AddCot_KgIdNotExist": "ModelFactory.CotController.AddCot.KgIdNotExist",
    "ModelFactory_CotController_AddCot_IndexNameNotExist": "ModelFactory.CotController.AddCot.IndexNameNotExist",
    "ModelFactory_CotRouter_WriteCotRouter_ParamError": "ModelFactory.CotRouter.WriteCotRouter.ParamError",
    "ModelFactory_CotController_WriteCot_EmbeddingError": "ModelFactory.CotController.WriteCot.EmbeddingError",
    "ModelFactory_CotController_WriteCot_UnknownError": "ModelFactory.CotController.WriteCot.UnknownError",
    "ModelFactory_ExternalSmallModel_UnknownError": "ModelFactory.ExternalSmallModel.UnknownError",
    "ModelFactory_ExternalSmallModel_AddModel_RepeatedNames_Error": "ModelFactory.ExternalSmallModel.AddModel.RepeatedNames",
    "ModelFactory_ExternalSmallModel_EditModel_RepeatedNames_Error": "ModelFactory.ExternalSmallModel.EditModel.RepeatedNames",
    "ModelFactory_ExternalSmallModel_GetInfo_IdNotExist_Error": "ModelFactory.ExternalSmallModel.GetInfo.IdNotExist",
    "ModelFactory_ExternalSmallModel_Used_NameNotExist": "ModelFactory.ExternalSmallModel.Used.NameNotExist",
    "ModelFactory_ExternalSmallModel_Used_ConnectError": "ModelFactory.ExternalSmallModel.Used.ConnectError",
    "ModelFactory_ExternalSmallModel_Used_ModelError": "ModelFactory.ExternalSmallModel.Used.ModelError",
    "ModelFactory_ExternalSmallModel_EditModel_IdNotExist_Error": "ModelFactory.ExternalSmallModel.EditModel.IdNotExist",
    "IdValueIsEmpty": "IdValueIsEmpty ",
    "UnauthorizedError": "Unauthorized",
    "HydraServiceError": "HydraServiceError",
    "UserManagementError": "UserManagementServiceError",
    "NotPermissionError": "NotPermission",
    "DeletePermissionResuorceError": "DeletePermissionResuorceError",
    "ModelQuotaControllerUserModelConfigNoLeftSpaceError": "ModelNager.ModelQuotaController.UserModelConfig.NoLeftSpace",
}


globals().update({name: _new_error(code) for name, code in _ERROR_CODES.items()})
__all__ = list(_ERROR_CODES)
