server:
  runMode: release
  httpPort: 13018
  language: zh-CN
  readTimeOut: 120
  writeTimeOut: 120
  viewDataTimeout: 5m
  defaultSmallModelEnabled: true
  filteredCrossJoinMaxEdgeExpand: 10000
log:
  logLevel: debug
  developMode: false
  maxAge: 100
  maxBackups: 20
  maxSize: 100
otel:
  service_name: "ontology-query"
  environment: "production"
  otlp_endpoint: "otelcol-contrib:4318"
  trace:
    enabled: false
    sampling_rate: 1.0
  log:
    enabled: false
    level: "info"

depServices:
  class-443:
    ingressClass: class-443
  rds:
    host: localhost
    port: 30006
    user: test
    password: testpwd
    type: MariaDB
  opensearch:
    host: localhost
    port: 30000
    protocol: http
    user: test
    password: testpwd 
  authorization-private:
    host: localhost
    port: 30920
    protocol: http
  user-management: 
    host: localhost
    port:  30981
    protocol: http
  hydra-public:
    host: localhost
    port: 4444
    protocol: http
  hydra-admin:
    host: localhost
    port: 4445
    protocol: http
  model-factory:
    host: localhost
    port: 9898
    protocol: http
  vega-backend:
    host: localhost
    port: 13014
    protocol: http
  bkn-backend:
    host: localhost
    port: 13014
    protocol: http
  agent-operator-integration:
    host: localhost
    port: 9000
    protocol: http
  mf-model-manager:
    host: localhost
    port: 9899
    protocol: http
  mf-model-api:
    host: localhost
    port: 9898
    protocol: http
