// Copyright openbkn.ai
//
// Licensed under the Apache License, Version 2.0. See the LICENSE file in the project root for details.

package logics

import (
	"strings"

	"vega-backend/interfaces"
)

// BuildIndexName returns the managed OpenSearch index name for a build task.
func BuildIndexName(resourceID string, buildTaskID string) string {
	return interfaces.BUILD_PREFIX + "-" + resourceID + "-" + buildTaskID
}

// ParseBuildIndexName parses a managed build index name into its Resource and Build Task IDs.
// Both IDs are generated by Vega and must not contain '-'.
func ParseBuildIndexName(indexName string) (resourceID string, buildTaskID string, ok bool) {
	prefix := interfaces.BUILD_PREFIX + "-"
	if !strings.HasPrefix(indexName, prefix) {
		return "", "", false
	}
	parts := strings.Split(strings.TrimPrefix(indexName, prefix), "-")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", false
	}
	return parts[0], parts[1], true
}
