// Copyright openbkn.ai
//
// Licensed under the OpenBKN License. See LICENSE-OPENBKN.txt in the project root.

// Package knlogicpropertyresolver
// file: dynamic_params_llm.go
// desc: metric/tool dynamic parameter generation is handled by mf-model-api.
//
//	prompt is extracted from the original agent definition and built-in (see prompts/ directory). It is released with the service and is no longer dependent on.
//	Manually imported agent in agent-factory.
package knlogicpropertyresolver

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/openbkn-ai/bkn-foundry/adp/context-loader/agent-retrieval/server/interfaces"
	"github.com/openbkn-ai/bkn-foundry/adp/context-loader/agent-retrieval/server/utils"
)

//go:embed prompts/metric_dynamic_params.md
var metricDynamicParamsPrompt string

//go:embed prompts/tool_dynamic_params.md
var toolDynamicParamsPrompt string

// The sampling parameters generated by dynamic parameters have the same value as the rerank_llm configuration by default (temperature=0 / top_k=2 / top_p=0.5):
// What we want here is deterministic output of structured JSON, not divergence. top_p / top_k must be set explicitly - leave empty to give Go zero value,
// However, mf-model-api requires 0 < top_p <= 1, top_k ≥ 1, and zero value is directly 400 (issue #450).
const (
	// dynamicParamsMaxTokens is sufficient for dynamic parameter generation.
	dynamicParamsMaxTokens   = 2000
	dynamicParamsTemperature = 0.0
	dynamicParamsTopK        = 2
	dynamicParamsTopP        = 0.5
)

// dynamicParamsLLM generates metric and ToolBox-tool dynamic parameters.
// Do not specify a model: mf-model-api parses the system default large model when model is empty (t_llm_model.f_default=1,
// Set globally by the administrator through the mf-model-manager /llm/default/edit interface), the same mechanism as the small model, and zero configuration on the service side.
type dynamicParamsLLM struct {
	logger        interfaces.Logger
	mfModelClient interfaces.DrivenMFModelAPIClient
	toolClient    interfaces.DrivenOperatorIntegration
}

// newDynamicParamsLLM Builds a direct LLM dynamic parameter generator.
func newDynamicParamsLLM(
	logger interfaces.Logger,
	mfModelClient interfaces.DrivenMFModelAPIClient,
	toolClient interfaces.DrivenOperatorIntegration,
) *dynamicParamsLLM {
	return &dynamicParamsLLM{logger: logger, mfModelClient: mfModelClient, toolClient: toolClient}
}

// GenerateMetricParams is directly connected to LLM to generate metric type dynamic parameters.
// The return value is semantically aligned with the original agent: successfully returns dynamicParams (the top key is logic_property.name),
// MissingParams is returned when the model determines that parameters are missing; the two are mutually exclusive.
func (d *dynamicParamsLLM) GenerateMetricParams(
	ctx context.Context,
	req *interfaces.MetricDynamicParamsGeneratorReq,
	llmModel string,
) (dynamicParams map[string]any, missingParams *interfaces.MissingPropertyParams, err error) {
	userJSON := utils.ObjectToJSON(req)
	d.logger.WithContext(ctx).Infof("  ├─ [直连LLM] Metric 入参: query=%s", userJSON)

	resultStr, err := d.chatJSON(ctx, metricDynamicParamsPrompt, userJSON, llmModel)
	if err != nil {
		d.logger.WithContext(ctx).Errorf("  ├─ [直连LLM] ❌ Metric Chat 失败: %v", err)
		return nil, nil, err
	}

	var rawResult map[string]any
	if err = json.Unmarshal([]byte(resultStr), &rawResult); err != nil {
		d.logger.WithContext(ctx).Errorf("  ├─ [直连LLM] ❌ Metric JSON 解析失败: %v, raw=%s", err, resultStr)
		return nil, nil, fmt.Errorf("unmarshal metric llm result failed: %w", err)
	}

	if errorMsg, ok := rawResult["_error"].(string); ok {
		missingParams = newMissingParams(req.LogicProperty.Name, errorMsg)
		d.logger.WithContext(ctx).Warnf("  └─ [直连LLM] ⚠️ Metric 缺参: %s", errorMsg)
		return nil, missingParams, nil
	}

	d.logger.WithContext(ctx).Debugf("  └─ [直连LLM] ✅ Metric 成功: %+v", rawResult)
	return rawResult, nil, nil
}

// GenerateToolParams generates dynamic parameters from the selected ToolBox tool schema.
func (d *dynamicParamsLLM) GenerateToolParams(
	ctx context.Context,
	req *interfaces.ToolDynamicParamsGeneratorReq,
	llmModel string,
) (dynamicParams map[string]any, missingParams *interfaces.MissingPropertyParams, err error) {
	var toolSchema string
	if req.BoxID != "" && req.ToolID != "" {
		tool, toolErr := d.toolClient.GetToolDetail(ctx, &interfaces.GetToolDetailRequest{
			BoxID: req.BoxID, ToolID: req.ToolID,
		})
		if toolErr != nil {
			d.logger.WithContext(ctx).Warnf("  ├─ [LLM] tool schema lookup failed(box_id=%s, tool_id=%s): %v",
				req.BoxID, req.ToolID, toolErr)
		} else if tool != nil {
			toolSchema = utils.ObjectToJSON(tool.Metadata.APISpec)
		}
	}

	userMsg := fmt.Sprintf("【输入】\n%s\n\n【工具的 Schema 信息】\n%s", utils.ObjectToJSON(req), toolSchema)
	d.logger.WithContext(ctx).Infof("  ├─ [LLM] Tool input: property=%s, box_id=%s, tool_id=%s",
		req.LogicProperty.Name, req.BoxID, req.ToolID)

	resultStr, err := d.chatJSON(ctx, toolDynamicParamsPrompt, userMsg, llmModel)
	if err != nil {
		d.logger.WithContext(ctx).Errorf("  ├─ [LLM] Tool chat failed: %v", err)
		return nil, nil, err
	}

	var rawResult map[string]any
	if err = json.Unmarshal([]byte(resultStr), &rawResult); err != nil {
		d.logger.WithContext(ctx).Errorf("  ├─ [LLM] Tool JSON parsing failed: %v, raw=%s", err, resultStr)
		return nil, nil, fmt.Errorf("unmarshal tool llm result failed: %w", err)
	}

	if errorMsg, ok := rawResult["_error"].(string); ok {
		missingParams = newMissingParams(req.LogicProperty.Name, errorMsg)
		d.logger.WithContext(ctx).Warnf("  └─ [LLM] Tool missing parameters: %s", errorMsg)
		return nil, missingParams, nil
	}

	d.logger.WithContext(ctx).Debugf("  └─ [LLM] Tool generated parameters: %+v", rawResult)
	return rawResult, nil, nil
}

// chatJSON General conversation: system=prompt, user=input JSON; returns the first JSON object extracted from the model output.
// model is per-request coverage (only specified for testing/verification); empty => mf-model-api parses the system default large model.
func (d *dynamicParamsLLM) chatJSON(ctx context.Context, systemPrompt, userJSON, model string) (string, error) {
	req := &interfaces.LLMChatReq{
		Model: model, // Empty => mf-model-api uses the system default large model.
		Messages: []interfaces.LLMMessage{
			{Role: "system", Content: systemPrompt},
			{Role: "user", Content: userJSON},
		},
		Temperature: dynamicParamsTemperature,
		TopK:        dynamicParamsTopK,
		TopP:        dynamicParamsTopP,
		MaxTokens:   dynamicParamsMaxTokens,
	}
	content, err := d.mfModelClient.Chat(ctx, req)
	if err != nil {
		return "", err
	}
	return extractJSONObject(content)
}

// extractJSONObject Extracts the first {...} JSON fragment from the model output, stripping ```json fences and extra text.
// Align the parseResultFromAgentV1Answer behavior of the original agent.
func extractJSONObject(s string) (string, error) {
	start := strings.Index(s, "{")
	end := strings.LastIndex(s, "}")
	if start == -1 || end == -1 || end < start {
		return "", fmt.Errorf("no JSON object found in LLM output: %s", s)
	}
	jsonStr := s[start : end+1]
	// Handle escaped newlines/quotes (some models will return escape strings)
	if strings.Contains(jsonStr, "\\n") || strings.Contains(jsonStr, "\\\"") {
		jsonStr = strings.ReplaceAll(jsonStr, "\\n", "\n")
		jsonStr = strings.ReplaceAll(jsonStr, "\\\"", "\"")
	}
	return jsonStr, nil
}

// newMissingParams constructs the missing parameter result and directly transparently transmits the error message generated by the model.
func newMissingParams(propertyName, errorMsg string) *interfaces.MissingPropertyParams {
	return &interfaces.MissingPropertyParams{
		Property: propertyName,
		ErrorMsg: errorMsg,
	}
}
