// Code generated by MockGen. DO NOT EDIT.
// Source: driven_operator_integration.go
//
// Generated by this command:
//
//	mockgen -source=driven_operator_integration.go -destination=../mocks/driven_operator_integration.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/openbkn-ai/bkn-foundry/adp/context-loader/agent-retrieval/server/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockDrivenOperatorIntegration is a mock of DrivenOperatorIntegration interface.
type MockDrivenOperatorIntegration struct {
	ctrl     *gomock.Controller
	recorder *MockDrivenOperatorIntegrationMockRecorder
	isgomock struct{}
}

// MockDrivenOperatorIntegrationMockRecorder is the mock recorder for MockDrivenOperatorIntegration.
type MockDrivenOperatorIntegrationMockRecorder struct {
	mock *MockDrivenOperatorIntegration
}

// NewMockDrivenOperatorIntegration creates a new mock instance.
func NewMockDrivenOperatorIntegration(ctrl *gomock.Controller) *MockDrivenOperatorIntegration {
	mock := &MockDrivenOperatorIntegration{ctrl: ctrl}
	mock.recorder = &MockDrivenOperatorIntegrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrivenOperatorIntegration) EXPECT() *MockDrivenOperatorIntegrationMockRecorder {
	return m.recorder
}

// CallMCPTool mocks base method.
func (m *MockDrivenOperatorIntegration) CallMCPTool(ctx context.Context, req *interfaces.CallMCPToolRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallMCPTool", ctx, req)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallMCPTool indicates an expected call of CallMCPTool.
func (mr *MockDrivenOperatorIntegrationMockRecorder) CallMCPTool(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallMCPTool", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).CallMCPTool), ctx, req)
}

// ExecuteFunction mocks base method.
func (m *MockDrivenOperatorIntegration) ExecuteFunction(ctx context.Context, req *interfaces.ExecuteFunctionRequest) (*interfaces.ExecuteFunctionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteFunction", ctx, req)
	ret0, _ := ret[0].(*interfaces.ExecuteFunctionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteFunction indicates an expected call of ExecuteFunction.
func (mr *MockDrivenOperatorIntegrationMockRecorder) ExecuteFunction(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteFunction", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).ExecuteFunction), ctx, req)
}

// ExecutePublishedTool mocks base method.
func (m *MockDrivenOperatorIntegration) ExecutePublishedTool(ctx context.Context, req *interfaces.ExecutePublishedToolRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePublishedTool", ctx, req)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecutePublishedTool indicates an expected call of ExecutePublishedTool.
func (mr *MockDrivenOperatorIntegrationMockRecorder) ExecutePublishedTool(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePublishedTool", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).ExecutePublishedTool), ctx, req)
}

// ExecuteSkill mocks base method.
func (m *MockDrivenOperatorIntegration) ExecuteSkill(ctx context.Context, req *interfaces.ExecuteSkillRequest) (*interfaces.ExecuteSkillResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteSkill", ctx, req)
	ret0, _ := ret[0].(*interfaces.ExecuteSkillResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteSkill indicates an expected call of ExecuteSkill.
func (mr *MockDrivenOperatorIntegrationMockRecorder) ExecuteSkill(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteSkill", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).ExecuteSkill), ctx, req)
}

// GetMCPToolDetail mocks base method.
func (m *MockDrivenOperatorIntegration) GetMCPToolDetail(ctx context.Context, req *interfaces.GetMCPToolDetailRequest) (*interfaces.GetMCPToolDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMCPToolDetail", ctx, req)
	ret0, _ := ret[0].(*interfaces.GetMCPToolDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMCPToolDetail indicates an expected call of GetMCPToolDetail.
func (mr *MockDrivenOperatorIntegrationMockRecorder) GetMCPToolDetail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMCPToolDetail", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).GetMCPToolDetail), ctx, req)
}

// GetSkillContent mocks base method.
func (m *MockDrivenOperatorIntegration) GetSkillContent(ctx context.Context, skillID string) (*interfaces.GetSkillContentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkillContent", ctx, skillID)
	ret0, _ := ret[0].(*interfaces.GetSkillContentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkillContent indicates an expected call of GetSkillContent.
func (mr *MockDrivenOperatorIntegrationMockRecorder) GetSkillContent(ctx, skillID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkillContent", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).GetSkillContent), ctx, skillID)
}

// GetToolDetail mocks base method.
func (m *MockDrivenOperatorIntegration) GetToolDetail(ctx context.Context, req *interfaces.GetToolDetailRequest) (*interfaces.GetToolDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolDetail", ctx, req)
	ret0, _ := ret[0].(*interfaces.GetToolDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToolDetail indicates an expected call of GetToolDetail.
func (mr *MockDrivenOperatorIntegrationMockRecorder) GetToolDetail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolDetail", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).GetToolDetail), ctx, req)
}

// ListSkills mocks base method.
func (m *MockDrivenOperatorIntegration) ListSkills(ctx context.Context, req *interfaces.ListSkillsRequest) (*interfaces.ListSkillsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkills", ctx, req)
	ret0, _ := ret[0].(*interfaces.ListSkillsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkills indicates an expected call of ListSkills.
func (mr *MockDrivenOperatorIntegrationMockRecorder) ListSkills(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkills", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).ListSkills), ctx, req)
}

// ListPublishedToolboxes mocks base method.
func (m *MockDrivenOperatorIntegration) ListPublishedToolboxes(ctx context.Context, req *interfaces.ListPublishedToolboxesRequest) (*interfaces.ListPublishedToolboxesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublishedToolboxes", ctx, req)
	ret0, _ := ret[0].(*interfaces.ListPublishedToolboxesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublishedToolboxes indicates an expected call of ListPublishedToolboxes.
func (mr *MockDrivenOperatorIntegrationMockRecorder) ListPublishedToolboxes(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublishedToolboxes", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).ListPublishedToolboxes), ctx, req)
}

// ListPublishedTools mocks base method.
func (m *MockDrivenOperatorIntegration) ListPublishedTools(ctx context.Context, req *interfaces.ListPublishedToolsRequest) (*interfaces.ListPublishedToolsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublishedTools", ctx, req)
	ret0, _ := ret[0].(*interfaces.ListPublishedToolsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublishedTools indicates an expected call of ListPublishedTools.
func (mr *MockDrivenOperatorIntegrationMockRecorder) ListPublishedTools(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublishedTools", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).ListPublishedTools), ctx, req)
}

// ReadSkillFile mocks base method.
func (m *MockDrivenOperatorIntegration) ReadSkillFile(ctx context.Context, req *interfaces.ReadSkillFileRequest) (*interfaces.ReadSkillFileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSkillFile", ctx, req)
	ret0, _ := ret[0].(*interfaces.ReadSkillFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSkillFile indicates an expected call of ReadSkillFile.
func (mr *MockDrivenOperatorIntegrationMockRecorder) ReadSkillFile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSkillFile", reflect.TypeOf((*MockDrivenOperatorIntegration)(nil).ReadSkillFile), ctx, req)
}
