// Code generated by MockGen. DO NOT EDIT.
// Source: drivenadapters.go
//
// Generated by this command:
//
//	mockgen -source=drivenadapters.go -destination=../mocks/drivenadapters.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/kowell-ai/adp/context-loader/agent-retrieval/server/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockHydra is a mock of Hydra interface.
type MockHydra struct {
	ctrl     *gomock.Controller
	recorder *MockHydraMockRecorder
	isgomock struct{}
}

// MockHydraMockRecorder is the mock recorder for MockHydra.
type MockHydraMockRecorder struct {
	mock *MockHydra
}

// NewMockHydra creates a new mock instance.
func NewMockHydra(ctrl *gomock.Controller) *MockHydra {
	mock := &MockHydra{ctrl: ctrl}
	mock.recorder = &MockHydraMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHydra) EXPECT() *MockHydraMockRecorder {
	return m.recorder
}

// Introspect mocks base method.
func (m *MockHydra) Introspect(ctx context.Context, token string) (*interfaces.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Introspect", ctx, token)
	ret0, _ := ret[0].(*interfaces.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Introspect indicates an expected call of Introspect.
func (mr *MockHydraMockRecorder) Introspect(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Introspect", reflect.TypeOf((*MockHydra)(nil).Introspect), ctx, token)
}

// MockDrivenMFModelAPIClient is a mock of DrivenMFModelAPIClient interface.
type MockDrivenMFModelAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockDrivenMFModelAPIClientMockRecorder
	isgomock struct{}
}

// MockDrivenMFModelAPIClientMockRecorder is the mock recorder for MockDrivenMFModelAPIClient.
type MockDrivenMFModelAPIClientMockRecorder struct {
	mock *MockDrivenMFModelAPIClient
}

// NewMockDrivenMFModelAPIClient creates a new mock instance.
func NewMockDrivenMFModelAPIClient(ctrl *gomock.Controller) *MockDrivenMFModelAPIClient {
	mock := &MockDrivenMFModelAPIClient{ctrl: ctrl}
	mock.recorder = &MockDrivenMFModelAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrivenMFModelAPIClient) EXPECT() *MockDrivenMFModelAPIClientMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockDrivenMFModelAPIClient) Chat(ctx context.Context, req *interfaces.LLMChatReq) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockDrivenMFModelAPIClientMockRecorder) Chat(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockDrivenMFModelAPIClient)(nil).Chat), ctx, req)
}

// Rerank mocks base method.
func (m *MockDrivenMFModelAPIClient) Rerank(ctx context.Context, query string, documents []string) (*interfaces.RerankResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rerank", ctx, query, documents)
	ret0, _ := ret[0].(*interfaces.RerankResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rerank indicates an expected call of Rerank.
func (mr *MockDrivenMFModelAPIClientMockRecorder) Rerank(ctx, query, documents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rerank", reflect.TypeOf((*MockDrivenMFModelAPIClient)(nil).Rerank), ctx, query, documents)
}
