// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kowell-ai/kowell-core/decision-agent/agent-backend/agent-factory/src/port/driven/idbaccess (interfaces: IDBAccBaseRepo)
//
// Generated by this command:
//
//	mockgen -package idbaccessmock -destination ./idbaccessmock/base.go github.com/kowell-ai/kowell-core/decision-agent/agent-backend/agent-factory/src/port/driven/idbaccess IDBAccBaseRepo
//

// Package idbaccessmock is a generated GoMock package.
package idbaccessmock

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/kweaver-ai/proton-rds-sdk-go/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockIDBAccBaseRepo is a mock of IDBAccBaseRepo interface.
type MockIDBAccBaseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIDBAccBaseRepoMockRecorder
	isgomock struct{}
}

// MockIDBAccBaseRepoMockRecorder is the mock recorder for MockIDBAccBaseRepo.
type MockIDBAccBaseRepoMockRecorder struct {
	mock *MockIDBAccBaseRepo
}

// NewMockIDBAccBaseRepo creates a new mock instance.
func NewMockIDBAccBaseRepo(ctrl *gomock.Controller) *MockIDBAccBaseRepo {
	mock := &MockIDBAccBaseRepo{ctrl: ctrl}
	mock.recorder = &MockIDBAccBaseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDBAccBaseRepo) EXPECT() *MockIDBAccBaseRepoMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockIDBAccBaseRepo) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockIDBAccBaseRepoMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockIDBAccBaseRepo)(nil).BeginTx), ctx)
}

// GetDB mocks base method.
func (m *MockIDBAccBaseRepo) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockIDBAccBaseRepoMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockIDBAccBaseRepo)(nil).GetDB))
}
