// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/port/driven/idbaccess (interfaces: IBizDomainAgentRelRepo)
//
// Generated by this command:
//
//	mockgen -package idbaccessmock -destination ./idbaccessmock/biz_domain_agent_rel.go github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/port/driven/idbaccess IBizDomainAgentRelRepo
//

// Package idbaccessmock is a generated GoMock package.
package idbaccessmock

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/kweaver-ai/proton-rds-sdk-go/sqlx"
	dapo "github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/infra/persistence/dapo"
	gomock "go.uber.org/mock/gomock"
)

// MockIBizDomainAgentRelRepo is a mock of IBizDomainAgentRelRepo interface.
type MockIBizDomainAgentRelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIBizDomainAgentRelRepoMockRecorder
	isgomock struct{}
}

// MockIBizDomainAgentRelRepoMockRecorder is the mock recorder for MockIBizDomainAgentRelRepo.
type MockIBizDomainAgentRelRepoMockRecorder struct {
	mock *MockIBizDomainAgentRelRepo
}

// NewMockIBizDomainAgentRelRepo creates a new mock instance.
func NewMockIBizDomainAgentRelRepo(ctrl *gomock.Controller) *MockIBizDomainAgentRelRepo {
	mock := &MockIBizDomainAgentRelRepo{ctrl: ctrl}
	mock.recorder = &MockIBizDomainAgentRelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBizDomainAgentRelRepo) EXPECT() *MockIBizDomainAgentRelRepoMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockIBizDomainAgentRelRepo) BatchCreate(ctx context.Context, tx *sql.Tx, pos []*dapo.BizDomainAgentRelPo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, tx, pos)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockIBizDomainAgentRelRepoMockRecorder) BatchCreate(ctx, tx, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockIBizDomainAgentRelRepo)(nil).BatchCreate), ctx, tx, pos)
}

// BeginTx mocks base method.
func (m *MockIBizDomainAgentRelRepo) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockIBizDomainAgentRelRepoMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockIBizDomainAgentRelRepo)(nil).BeginTx), ctx)
}

// DeleteByAgentID mocks base method.
func (m *MockIBizDomainAgentRelRepo) DeleteByAgentID(ctx context.Context, tx *sql.Tx, agentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByAgentID", ctx, tx, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByAgentID indicates an expected call of DeleteByAgentID.
func (mr *MockIBizDomainAgentRelRepoMockRecorder) DeleteByAgentID(ctx, tx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByAgentID", reflect.TypeOf((*MockIBizDomainAgentRelRepo)(nil).DeleteByAgentID), ctx, tx, agentID)
}

// DeleteByBizDomainID mocks base method.
func (m *MockIBizDomainAgentRelRepo) DeleteByBizDomainID(ctx context.Context, tx *sql.Tx, bizDomainID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByBizDomainID", ctx, tx, bizDomainID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByBizDomainID indicates an expected call of DeleteByBizDomainID.
func (mr *MockIBizDomainAgentRelRepoMockRecorder) DeleteByBizDomainID(ctx, tx, bizDomainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByBizDomainID", reflect.TypeOf((*MockIBizDomainAgentRelRepo)(nil).DeleteByBizDomainID), ctx, tx, bizDomainID)
}

// GetByAgentID mocks base method.
func (m *MockIBizDomainAgentRelRepo) GetByAgentID(ctx context.Context, tx *sql.Tx, agentID string) ([]*dapo.BizDomainAgentRelPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAgentID", ctx, tx, agentID)
	ret0, _ := ret[0].([]*dapo.BizDomainAgentRelPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAgentID indicates an expected call of GetByAgentID.
func (mr *MockIBizDomainAgentRelRepoMockRecorder) GetByAgentID(ctx, tx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAgentID", reflect.TypeOf((*MockIBizDomainAgentRelRepo)(nil).GetByAgentID), ctx, tx, agentID)
}

// GetByBizDomainID mocks base method.
func (m *MockIBizDomainAgentRelRepo) GetByBizDomainID(ctx context.Context, tx *sql.Tx, bizDomainID string) ([]*dapo.BizDomainAgentRelPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBizDomainID", ctx, tx, bizDomainID)
	ret0, _ := ret[0].([]*dapo.BizDomainAgentRelPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBizDomainID indicates an expected call of GetByBizDomainID.
func (mr *MockIBizDomainAgentRelRepoMockRecorder) GetByBizDomainID(ctx, tx, bizDomainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBizDomainID", reflect.TypeOf((*MockIBizDomainAgentRelRepo)(nil).GetByBizDomainID), ctx, tx, bizDomainID)
}

// GetDB mocks base method.
func (m *MockIBizDomainAgentRelRepo) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockIBizDomainAgentRelRepoMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockIBizDomainAgentRelRepo)(nil).GetDB))
}
