// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/port/driven/idbaccess (interfaces: IDataAgentTplRepo)
//
// Generated by this command:
//
//	mockgen -package idbaccessmock -destination ./idbaccessmock/da_config_tpl.go github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/port/driven/idbaccess IDataAgentTplRepo
//

// Package idbaccessmock is a generated GoMock package.
package idbaccessmock

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/kweaver-ai/proton-rds-sdk-go/sqlx"
	cdaenum "github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/domain/enum/cdaenum"
	dapo "github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/infra/persistence/dapo"
	gomock "go.uber.org/mock/gomock"
)

// MockIDataAgentTplRepo is a mock of IDataAgentTplRepo interface.
type MockIDataAgentTplRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIDataAgentTplRepoMockRecorder
	isgomock struct{}
}

// MockIDataAgentTplRepoMockRecorder is the mock recorder for MockIDataAgentTplRepo.
type MockIDataAgentTplRepoMockRecorder struct {
	mock *MockIDataAgentTplRepo
}

// NewMockIDataAgentTplRepo creates a new mock instance.
func NewMockIDataAgentTplRepo(ctrl *gomock.Controller) *MockIDataAgentTplRepo {
	mock := &MockIDataAgentTplRepo{ctrl: ctrl}
	mock.recorder = &MockIDataAgentTplRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDataAgentTplRepo) EXPECT() *MockIDataAgentTplRepoMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockIDataAgentTplRepo) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockIDataAgentTplRepoMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).BeginTx), ctx)
}

// Create mocks base method.
func (m *MockIDataAgentTplRepo) Create(ctx context.Context, tx *sql.Tx, po *dapo.DataAgentTplPo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, po)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIDataAgentTplRepoMockRecorder) Create(ctx, tx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).Create), ctx, tx, po)
}

// Delete mocks base method.
func (m *MockIDataAgentTplRepo) Delete(ctx context.Context, tx *sql.Tx, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIDataAgentTplRepoMockRecorder) Delete(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).Delete), ctx, tx, id)
}

// ExistsByID mocks base method.
func (m *MockIDataAgentTplRepo) ExistsByID(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByID", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByID indicates an expected call of ExistsByID.
func (mr *MockIDataAgentTplRepoMockRecorder) ExistsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByID", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).ExistsByID), ctx, id)
}

// ExistsByKey mocks base method.
func (m *MockIDataAgentTplRepo) ExistsByKey(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByKey", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByKey indicates an expected call of ExistsByKey.
func (mr *MockIDataAgentTplRepoMockRecorder) ExistsByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByKey", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).ExistsByKey), ctx, key)
}

// ExistsByKeyExcludeID mocks base method.
func (m *MockIDataAgentTplRepo) ExistsByKeyExcludeID(ctx context.Context, key string, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByKeyExcludeID", ctx, key, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByKeyExcludeID indicates an expected call of ExistsByKeyExcludeID.
func (mr *MockIDataAgentTplRepoMockRecorder) ExistsByKeyExcludeID(ctx, key, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByKeyExcludeID", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).ExistsByKeyExcludeID), ctx, key, id)
}

// ExistsByName mocks base method.
func (m *MockIDataAgentTplRepo) ExistsByName(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByName", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByName indicates an expected call of ExistsByName.
func (mr *MockIDataAgentTplRepoMockRecorder) ExistsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByName", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).ExistsByName), ctx, name)
}

// ExistsByNameExcludeID mocks base method.
func (m *MockIDataAgentTplRepo) ExistsByNameExcludeID(ctx context.Context, name string, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByNameExcludeID", ctx, name, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByNameExcludeID indicates an expected call of ExistsByNameExcludeID.
func (mr *MockIDataAgentTplRepoMockRecorder) ExistsByNameExcludeID(ctx, name, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByNameExcludeID", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).ExistsByNameExcludeID), ctx, name, id)
}

// GetAllIDs mocks base method.
func (m *MockIDataAgentTplRepo) GetAllIDs(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllIDs", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllIDs indicates an expected call of GetAllIDs.
func (mr *MockIDataAgentTplRepoMockRecorder) GetAllIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllIDs", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).GetAllIDs), ctx)
}

// GetByID mocks base method.
func (m *MockIDataAgentTplRepo) GetByID(ctx context.Context, id int64) (*dapo.DataAgentTplPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dapo.DataAgentTplPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIDataAgentTplRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).GetByID), ctx, id)
}

// GetByIDS mocks base method.
func (m *MockIDataAgentTplRepo) GetByIDS(ctx context.Context, ids []int64) ([]*dapo.DataAgentTplPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDS", ctx, ids)
	ret0, _ := ret[0].([]*dapo.DataAgentTplPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDS indicates an expected call of GetByIDS.
func (mr *MockIDataAgentTplRepoMockRecorder) GetByIDS(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDS", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).GetByIDS), ctx, ids)
}

// GetByIDWithTx mocks base method.
func (m *MockIDataAgentTplRepo) GetByIDWithTx(ctx context.Context, tx *sql.Tx, id int64) (*dapo.DataAgentTplPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithTx", ctx, tx, id)
	ret0, _ := ret[0].(*dapo.DataAgentTplPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithTx indicates an expected call of GetByIDWithTx.
func (mr *MockIDataAgentTplRepoMockRecorder) GetByIDWithTx(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithTx", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).GetByIDWithTx), ctx, tx, id)
}

// GetByKey mocks base method.
func (m *MockIDataAgentTplRepo) GetByKey(ctx context.Context, key string) (*dapo.DataAgentTplPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, key)
	ret0, _ := ret[0].(*dapo.DataAgentTplPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockIDataAgentTplRepoMockRecorder) GetByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).GetByKey), ctx, key)
}

// GetByKeyWithTx mocks base method.
func (m *MockIDataAgentTplRepo) GetByKeyWithTx(ctx context.Context, tx *sql.Tx, key string) (*dapo.DataAgentTplPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKeyWithTx", ctx, tx, key)
	ret0, _ := ret[0].(*dapo.DataAgentTplPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKeyWithTx indicates an expected call of GetByKeyWithTx.
func (mr *MockIDataAgentTplRepoMockRecorder) GetByKeyWithTx(ctx, tx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKeyWithTx", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).GetByKeyWithTx), ctx, tx, key)
}

// GetByKeys mocks base method.
func (m *MockIDataAgentTplRepo) GetByKeys(ctx context.Context, keys []string) ([]*dapo.DataAgentTplPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKeys", ctx, keys)
	ret0, _ := ret[0].([]*dapo.DataAgentTplPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKeys indicates an expected call of GetByKeys.
func (mr *MockIDataAgentTplRepoMockRecorder) GetByKeys(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKeys", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).GetByKeys), ctx, keys)
}

// GetDB mocks base method.
func (m *MockIDataAgentTplRepo) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockIDataAgentTplRepoMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).GetDB))
}

// GetMapByIDs mocks base method.
func (m *MockIDataAgentTplRepo) GetMapByIDs(ctx context.Context, ids []int64) (map[int64]*dapo.DataAgentTplPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapByIDs", ctx, ids)
	ret0, _ := ret[0].(map[int64]*dapo.DataAgentTplPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapByIDs indicates an expected call of GetMapByIDs.
func (mr *MockIDataAgentTplRepoMockRecorder) GetMapByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapByIDs", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).GetMapByIDs), ctx, ids)
}

// Update mocks base method.
func (m *MockIDataAgentTplRepo) Update(ctx context.Context, tx *sql.Tx, po *dapo.DataAgentTplPo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, po)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIDataAgentTplRepoMockRecorder) Update(ctx, tx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).Update), ctx, tx, po)
}

// UpdateStatus mocks base method.
func (m *MockIDataAgentTplRepo) UpdateStatus(ctx context.Context, tx *sql.Tx, status cdaenum.Status, id int64, uid string, publishedAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, tx, status, id, uid, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockIDataAgentTplRepoMockRecorder) UpdateStatus(ctx, tx, status, id, uid, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockIDataAgentTplRepo)(nil).UpdateStatus), ctx, tx, status, id, uid, publishedAt)
}
