// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kowell-ai/kowell-core/decision-agent/agent-backend/agent-factory/src/port/driven/idbaccess (interfaces: IPersonalSpaceRepo)
//
// Generated by this command:
//
//	mockgen -package idbaccessmock -destination ./idbaccessmock/personal_space.go github.com/kowell-ai/kowell-core/decision-agent/agent-backend/agent-factory/src/port/driven/idbaccess IPersonalSpaceRepo
//

// Package idbaccessmock is a generated GoMock package.
package idbaccessmock

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	psdbarg "github.com/kowell-ai/kowell-core/decision-agent/agent-backend/agent-factory/src/drivenadapter/dbaccess/personalspacedbacc/psdbarg"
	dapo "github.com/kowell-ai/kowell-core/decision-agent/agent-backend/agent-factory/src/infra/persistence/dapo"
	sqlx "github.com/kweaver-ai/proton-rds-sdk-go/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockIPersonalSpaceRepo is a mock of IPersonalSpaceRepo interface.
type MockIPersonalSpaceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIPersonalSpaceRepoMockRecorder
	isgomock struct{}
}

// MockIPersonalSpaceRepoMockRecorder is the mock recorder for MockIPersonalSpaceRepo.
type MockIPersonalSpaceRepoMockRecorder struct {
	mock *MockIPersonalSpaceRepo
}

// NewMockIPersonalSpaceRepo creates a new mock instance.
func NewMockIPersonalSpaceRepo(ctrl *gomock.Controller) *MockIPersonalSpaceRepo {
	mock := &MockIPersonalSpaceRepo{ctrl: ctrl}
	mock.recorder = &MockIPersonalSpaceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPersonalSpaceRepo) EXPECT() *MockIPersonalSpaceRepoMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockIPersonalSpaceRepo) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockIPersonalSpaceRepoMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockIPersonalSpaceRepo)(nil).BeginTx), ctx)
}

// GetDB mocks base method.
func (m *MockIPersonalSpaceRepo) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockIPersonalSpaceRepoMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockIPersonalSpaceRepo)(nil).GetDB))
}

// ListPersonalSpaceAgent mocks base method.
func (m *MockIPersonalSpaceRepo) ListPersonalSpaceAgent(ctx context.Context, arg *psdbarg.AgentListArg) ([]*dapo.DataAgentPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPersonalSpaceAgent", ctx, arg)
	ret0, _ := ret[0].([]*dapo.DataAgentPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPersonalSpaceAgent indicates an expected call of ListPersonalSpaceAgent.
func (mr *MockIPersonalSpaceRepoMockRecorder) ListPersonalSpaceAgent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPersonalSpaceAgent", reflect.TypeOf((*MockIPersonalSpaceRepo)(nil).ListPersonalSpaceAgent), ctx, arg)
}

// ListPersonalSpaceTpl mocks base method.
func (m *MockIPersonalSpaceRepo) ListPersonalSpaceTpl(ctx context.Context, arg *psdbarg.TplListArg) ([]*dapo.DataAgentTplPo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPersonalSpaceTpl", ctx, arg)
	ret0, _ := ret[0].([]*dapo.DataAgentTplPo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPersonalSpaceTpl indicates an expected call of ListPersonalSpaceTpl.
func (mr *MockIPersonalSpaceRepoMockRecorder) ListPersonalSpaceTpl(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPersonalSpaceTpl", reflect.TypeOf((*MockIPersonalSpaceRepo)(nil).ListPersonalSpaceTpl), ctx, arg)
}
