// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/port/driven/idbaccess (interfaces: IVisitHistoryRepo)
//
// Generated by this command:
//
//	mockgen -package idbaccessmock -destination ./idbaccessmock/visit_history.go github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/port/driven/idbaccess IVisitHistoryRepo
//

// Package idbaccessmock is a generated GoMock package.
package idbaccessmock

import (
	context "context"
	reflect "reflect"

	dapo "github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/infra/persistence/dapo"
	gomock "go.uber.org/mock/gomock"
)

// MockIVisitHistoryRepo is a mock of IVisitHistoryRepo interface.
type MockIVisitHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIVisitHistoryRepoMockRecorder
	isgomock struct{}
}

// MockIVisitHistoryRepoMockRecorder is the mock recorder for MockIVisitHistoryRepo.
type MockIVisitHistoryRepoMockRecorder struct {
	mock *MockIVisitHistoryRepo
}

// NewMockIVisitHistoryRepo creates a new mock instance.
func NewMockIVisitHistoryRepo(ctrl *gomock.Controller) *MockIVisitHistoryRepo {
	mock := &MockIVisitHistoryRepo{ctrl: ctrl}
	mock.recorder = &MockIVisitHistoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIVisitHistoryRepo) EXPECT() *MockIVisitHistoryRepoMockRecorder {
	return m.recorder
}

// IncVisitCount mocks base method.
func (m *MockIVisitHistoryRepo) IncVisitCount(ctx context.Context, po *dapo.VisitHistoryPO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncVisitCount", ctx, po)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncVisitCount indicates an expected call of IncVisitCount.
func (mr *MockIVisitHistoryRepoMockRecorder) IncVisitCount(ctx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncVisitCount", reflect.TypeOf((*MockIVisitHistoryRepo)(nil).IncVisitCount), ctx, po)
}
