#!/usr/bin/env python3
# Copyright (c) 2026 OpenBKN
# SPDX-License-Identifier: LicenseRef-OpenBKN
# Licensed under the OpenBKN License, a modified Apache 2.0 with Additional
# Conditions. See LICENSE-OPENBKN.txt in the repository root for the full text.

"""Verify OpenBKN license markers in BKN Trace authored source and config files."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
TRACE_ROOT = Path("bkn-trace")
REQUIRED_MARKERS = (
    "Copyright (c) 2026 OpenBKN",
    "SPDX-License-Identifier: LicenseRef-OpenBKN",
    "Licensed under the OpenBKN License",
)
COMMENTABLE_SUFFIXES = {
    ".go",
    ".py",
    ".sh",
    ".sql",
    ".toml",
    ".tpl",
    ".yaml",
    ".yml",
}
COMMENTABLE_NAMES = {"Dockerfile", "Makefile"}
EXCLUDED_FILES = {
    # Generated by Swagger tooling; modify its generator instead of this output.
    Path("bkn-trace/agent-observability/docs/swagger/docs.go"),
}


def is_commentable(path: Path) -> bool:
    # Applied migrations are checksum-protected deployment artifacts. A comment
    # would mutate their schema bytes and invalidate the durable ledger.
    if path.match("bkn-trace/agent-observability/migrations/mariadb/*/init.sql"):
        return False
    return (
        "/templates/" in path.as_posix()
        or path.name in COMMENTABLE_NAMES
        or path.suffix in COMMENTABLE_SUFFIXES
    )


def validate_content(path: Path, content: str) -> list[str]:
    lines = content.splitlines()
    if lines and lines[0].startswith("#!"):
        lines = lines[1:]

    if path.suffix == ".tpl" or "/templates/" in path.as_posix():
        header = "\n".join(lines[:6])
        if header.startswith("{{- /*") and "*/ -}}" in header and all(
            marker in header for marker in REQUIRED_MARKERS
        ):
            return []
    else:
        prefix = "--" if path.suffix == ".sql" else ("//" if path.suffix == ".go" else "#")
        header = lines[:4]
        if all(
            any(line.startswith(prefix) and marker in line for line in header)
            for marker in REQUIRED_MARKERS
        ):
            return []
    return ["missing OpenBKN license header"]


def tracked_trace_files() -> list[Path]:
    result = subprocess.run(
        ["git", "ls-files", "bkn-trace"],
        cwd=ROOT,
        capture_output=True,
        check=True,
        text=True,
    )
    return [Path(line) for line in result.stdout.splitlines()]


def main() -> int:
    failures: list[str] = []
    for path in tracked_trace_files():
        if path in EXCLUDED_FILES or not is_commentable(path):
            continue
        errors = validate_content(path, (ROOT / path).read_text(encoding="utf-8"))
        failures.extend(f"{path}: {error}" for error in errors)

    if failures:
        print("BKN Trace files missing required OpenBKN license markers:", file=sys.stderr)
        print("\n".join(f"- {failure}" for failure in failures), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
