# Copyright openbkn.ai
#
# Licensed under the Apache License, Version 2.0.
# See the LICENSE file in the project root for details.

"""Sandbox stub for BKN capabilities, generated by Context Loader.

_configure(event) injects credentials and lifecycle context before execution.
"""

import json
import os
import pathlib
import urllib.request

_CFG = {}
_SESSION = {}

# /workspace is shared by all calls. Create and enter a conversation-specific
# subdirectory so scripts can use relative paths without crossing sessions.
WORKDIR = pathlib.Path("/workspace")

# The MCP endpoint is in-cluster. A inherited proxy would make urllib issue an
# absolute-form request that the gateway rejects, so disable proxies explicitly.
_OPENER = urllib.request.build_opener(urllib.request.ProxyHandler({}))


class ToolError(RuntimeError):
    """A tool invocation failed; message contains the server response."""


def _configure(event):
    """Inject MCP endpoint, credentials, and lifecycle context; prepare workdir."""
    global WORKDIR
    _CFG.update(event)
    _SESSION.clear()

    # Use an ASCII-only normalization instead of a hash. run_shell must derive
    # the same directory outside this stub, and Python's isalnum accepts Unicode
    # while the Go implementation intentionally does not.
    _SAFE = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"
    conversation = str((event.get("bkn") or {}).get("conversation_id") or "").strip()
    safe = "".join(c if c in _SAFE else "-" for c in conversation)[:64]
    candidate = pathlib.Path("/workspace") / ("conv-" + safe if safe else "shared")
    try:
        candidate.mkdir(parents=True, exist_ok=True)
        os.chdir(candidate)
        WORKDIR = candidate
    except OSError:
        # Keep the script runnable when the sandbox workdir is not writable.
        WORKDIR = pathlib.Path(os.getcwd())


def _rpc(method, params=None, notify=False):
    body = {"jsonrpc": "2.0", "method": method}
    if params is not None:
        body["params"] = params
    if not notify:
        body["id"] = _SESSION.get("seq", 0) + 1
        _SESSION["seq"] = body["id"]
    headers = {
    "Content-Type": "application/json",
    "Accept": "application/json, text/event-stream",
    "Accept-Language": _CFG.get("locale", "zh-CN"),
    "Authorization": "Bearer " + _CFG["token"],
    }
    if _SESSION.get("id"):
        headers["Mcp-Session-Id"] = _SESSION["id"]
    request = urllib.request.Request(
        _CFG["mcp"], data=json.dumps(body).encode(),
        headers=headers, method="POST",
    )
    response = _OPENER.open(request, timeout=_CFG.get("timeout", 120))
    if not _SESSION.get("id"):
        _SESSION["id"] = response.headers.get("Mcp-Session-Id")
    raw = response.read().decode()
    if not raw.strip():
        return None
    for line in raw.splitlines():
        if line.startswith("data: "):
            return json.loads(line[6:])
    return json.loads(raw)


def _ensure_session():
    """Reuse one MCP session per execution and initialize it at most once."""
    if _SESSION.get("ready"):
        return
    _rpc("initialize", {
        "protocolVersion": "2025-06-18",
        "capabilities": {},
        "clientInfo": {"name": "bkn-sandbox", "version": "1"},
    })
    _rpc("notifications/initialized", {}, notify=True)
    _SESSION["ready"] = True


def _call(tool, args):
    """Call an MCP tool, omitting None so the server applies schema defaults."""
    _ensure_session()
    payload = {k: v for k, v in args.items() if v is not None}
    # Business tools require bkn_context, which the caller supplies implicitly.
    if _CFG.get("bkn"):
        payload["bkn_context"] = _CFG["bkn"]

    result = _rpc("tools/call", {"name": tool, "arguments": payload})["result"]
    text = "".join(c["text"] for c in result["content"] if c["type"] == "text")
    if result.get("isError") or result.get("is_error"):
        raise ToolError(tool + ": " + text)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Return non-JSON representations, such as response_format=toon, unchanged.
        return text
