// Copyright openbkn.ai
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// ptc-stub prints the sandbox side capability of PTC to the standard output for the check-in product to be completed during the build period.
//
// The sandbox image requires a copy of the BKN capability surface (infra/sandbox/runtime/sandbox_sdk/_bkn_tools.py),
// But that Python was not handwritten, it was rendered from the MCP tool directory. Only one copy of the rendering rule is allowed:
// The server reports the same hash as toolkit_version on GET /mcp/info, built by
// this same BuildPTCToolkit, so a stale image is visible by comparing the two.
// The returned stub is byte-for-byte identical. Use Python to implement rendering again, and create a second copy that will drift separately.
// Rules - that's what moving rendering to the server eliminates.
//
// Usage:
//
//	go run ./cmd/ptc-stub > .../sandbox_sdk/_bkn_tools.py
//	go run ./cmd/ptc-stub --version # only print content hash.
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/openbkn-ai/bkn-foundry/adp/context-loader/agent-retrieval/server/driveradapters/mcp"
)

// endpoint only affects the self-describing address field in the tool directory and does not affect the function definition of stub; it does not affect the build period.
// The actual request can be based on a clear placeholder value to prevent the address of a certain machine from being mixed into the product.
const buildTimeEndpoint = "http://agent-retrieval/api/agent-retrieval/v1/mcp"

// The same goes for sandboxPort: the sandbox return address is covered by _configure(event) at runtime, and the one in the product is just.
// Default value. Hard-coded into the cluster service port, consistent with defaultPTCServicePort.
const sandboxPort = 30779

func main() {
	versionOnly := flag.Bool("version", false, "只打印工具面内容哈希")
	flag.Parse()

	toolkit, err := mcp.BuildPTCToolkit(buildTimeEndpoint, sandboxPort)
	if err != nil {
		fmt.Fprintf(os.Stderr, "render PTC stub: %v\n", err)
		os.Exit(1)
	}

	if *versionOnly {
		fmt.Println(toolkit.Version)
		return
	}

	// The version is written into the product: the sandbox side reports which version it has installed accordingly, and can check the server at a glance when there is a problem.
	fmt.Printf("# Code generated by cmd/ptc-stub. DO NOT EDIT.\n")
	fmt.Printf("# 重新生成：make -C infra/sandbox bkn-tools\n")
	fmt.Printf("__toolkit_version__ = %q\n\n", toolkit.Version)
	fmt.Print(toolkit.Stub)
}
