// Copyright openbkn.ai
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// ptc-stub 把 PTC 的沙箱侧能力面打到标准输出，供构建期落成签入产物。
//
// 沙箱镜像需要一份 BKN 能力面（infra/sandbox/runtime/sandbox_sdk/_bkn_tools.py），
// 但那份 Python 不是手写的，是由 MCP 工具目录渲染出来的。渲染规则只允许有一份：
// 线上 GET /mcp/ptc/toolkit 与这里走的是同一个 BuildPTCToolkit，因此产物与端点
// 返回的 stub 逐字节相同。用 Python 再实现一遍渲染，就又造出了会各自漂移的第二份
// 规则——那正是把渲染搬到服务端要消灭的东西。
//
// 用法：
//
//	go run ./cmd/ptc-stub > .../sandbox_sdk/_bkn_tools.py
//	go run ./cmd/ptc-stub --version     # 只打印内容哈希
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/openbkn-ai/bkn-foundry/adp/context-loader/agent-retrieval/server/driveradapters/mcp"
)

// endpoint 只影响工具目录里自描述的地址字段，不影响 stub 的函数定义；构建期没有
// 真实请求可依据，给一个明确的占位值，免得产物里混进某台机器的地址。
const buildTimeEndpoint = "http://agent-retrieval/api/agent-retrieval/v1/mcp"

// sandboxPort 同理：沙箱回访地址在运行时由 _configure(event) 覆盖，产物里那份只是
// 默认值。写死成集群内服务端口，与 defaultPTCServicePort 一致。
const sandboxPort = 30779

func main() {
	versionOnly := flag.Bool("version", false, "只打印工具面内容哈希")
	flag.Parse()

	toolkit, err := mcp.BuildPTCToolkit(buildTimeEndpoint, sandboxPort)
	if err != nil {
		fmt.Fprintf(os.Stderr, "render PTC stub: %v\n", err)
		os.Exit(1)
	}

	if *versionOnly {
		fmt.Println(toolkit.Version)
		return
	}

	// 版本写进产物：沙箱侧据此报告自己装配的是哪一版，出问题时能一眼对上服务端。
	fmt.Printf("# Code generated by cmd/ptc-stub. DO NOT EDIT.\n")
	fmt.Printf("# 重新生成：make -C infra/sandbox bkn-tools\n")
	fmt.Printf("__toolkit_version__ = %q\n\n", toolkit.Version)
	fmt.Print(toolkit.Stub)
}
