// Copyright openbkn.ai
//
// Licensed under the OpenBKN License. See LICENSE-OPENBKN.txt in the project root.

package mcp

import (
	"slices"
	"testing"

	"github.com/openbkn-ai/bkn-foundry/adp/context-loader/agent-retrieval/server/logics/knskills"
)

// TestExecuteSkillOnlyAppearsWhenEnabled focuses on the default state of that command execution channel.
//
// execute_skill sends the shell generated by the model into the sandbox. By default, it must be neither in tools/list nor.
// /mcp/info——"Not opened" must look the same as "Not compiled in", otherwise it will be open to any detector.
// Broadcast this service to be able to execute commands.
func TestExecuteSkillOnlyAppearsWhenEnabled(t *testing.T) {
	noExtensions(t)

	if slices.Contains(assembledNames(t), toolKeyExecuteSkill) {
		t.Fatalf("execute_skill 在未开启时出现在 tools/list")
	}
	info, err := BuildMCPInfo("https://example.invalid/mcp")
	if err != nil {
		t.Fatalf("BuildMCPInfo: %v", err)
	}
	for _, tool := range info.Tools {
		if tool.Name == toolKeyExecuteSkill {
			t.Fatalf("execute_skill 在未开启时出现在 /mcp/info")
		}
	}

	t.Setenv(knskills.ExecuteEnabledEnv, "true")

	if !slices.Contains(assembledNames(t), toolKeyExecuteSkill) {
		t.Fatalf("开启后 execute_skill 仍未出现在 tools/list")
	}
	info, err = BuildMCPInfo("https://example.invalid/mcp")
	if err != nil {
		t.Fatalf("BuildMCPInfo: %v", err)
	}
	found := false
	for _, tool := range info.Tools {
		if tool.Name == toolKeyExecuteSkill {
			found = true
		}
	}
	if !found {
		t.Fatalf("开启后 execute_skill 仍未出现在 /mcp/info")
	}
}

// The schema of the TestSkillToolsAdvertiseSchemas three reading tools must be able to be loaded and not empty——.
// LoadToolSchemas during assembly has panic semantics, and leaked files will explode when the service starts.
func TestSkillToolsAdvertiseSchemas(t *testing.T) {
	noExtensions(t)

	locale := loadMCPLocaleBundle(mcpLocaleFromEnv())
	for _, key := range []string{toolKeyListSkills, toolKeyGetSkillContent, toolKeyReadSkillFile, toolKeyExecuteSkill} {
		in, out := tryLoadToolSchemas(locale, key)
		if len(in) == 0 {
			t.Fatalf("%s 缺 input_schema", key)
		}
		if len(out) == 0 {
			t.Fatalf("%s 缺 output_schema", key)
		}
	}
}
