apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  SAFE_HTTP_ADDR: ":{{ .Values.service.ports.port }}"
  SAFE_SEED_ON_START: {{ .Values.config.seedOnStart | quote }}
  SAFE_DB_TYPE: {{ .Values.config.db.type | quote }}
  SAFE_DB_HOST: {{ .Values.config.db.host | quote }}
  SAFE_DB_PORT: {{ .Values.config.db.port | quote }}
  SAFE_DB_USER: {{ .Values.config.db.user | quote }}
  SAFE_DB_PASSWORD: {{ .Values.config.db.password | quote }}
  SAFE_DB_NAME: {{ .Values.config.db.name | quote }}
  SAFE_HYDRA_ADMIN_URL: {{ .Values.config.hydra.adminURL | quote }}
  SAFE_HYDRA_PUBLIC_URL: {{ .Values.config.hydra.publicURL | quote }}
  SAFE_LDAP_URL: {{ .Values.config.ldap.url | quote }}
  SAFE_LDAP_BIND_DN: {{ .Values.config.ldap.bindDN | quote }}
  SAFE_LDAP_BIND_PASSWORD: {{ .Values.config.ldap.bindPassword | quote }}
  SAFE_LDAP_BASE_DN: {{ .Values.config.ldap.baseDN | quote }}
  SAFE_LDAP_USER_FILTER: {{ .Values.config.ldap.userFilter | quote }}
  GIN_MODE: "release"
