// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/action_type_service.go
//
// Generated by this command:
//
//	mockgen -source interfaces/action_type_service.go -destination interfaces/mock/mock_action_type_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	interfaces "bkn-backend/interfaces"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockActionTypeService is a mock of ActionTypeService interface.
type MockActionTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockActionTypeServiceMockRecorder
	isgomock struct{}
}

// MockActionTypeServiceMockRecorder is the mock recorder for MockActionTypeService.
type MockActionTypeServiceMockRecorder struct {
	mock *MockActionTypeService
}

// NewMockActionTypeService creates a new mock instance.
func NewMockActionTypeService(ctrl *gomock.Controller) *MockActionTypeService {
	mock := &MockActionTypeService{ctrl: ctrl}
	mock.recorder = &MockActionTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionTypeService) EXPECT() *MockActionTypeServiceMockRecorder {
	return m.recorder
}

// CheckActionTypeExistByID mocks base method.
func (m *MockActionTypeService) CheckActionTypeExistByID(ctx context.Context, knID, branch, atID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckActionTypeExistByID", ctx, knID, branch, atID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckActionTypeExistByID indicates an expected call of CheckActionTypeExistByID.
func (mr *MockActionTypeServiceMockRecorder) CheckActionTypeExistByID(ctx, knID, branch, atID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckActionTypeExistByID", reflect.TypeOf((*MockActionTypeService)(nil).CheckActionTypeExistByID), ctx, knID, branch, atID)
}

// CheckActionTypeExistByName mocks base method.
func (m *MockActionTypeService) CheckActionTypeExistByName(ctx context.Context, knID, branch, atName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckActionTypeExistByName", ctx, knID, branch, atName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckActionTypeExistByName indicates an expected call of CheckActionTypeExistByName.
func (mr *MockActionTypeServiceMockRecorder) CheckActionTypeExistByName(ctx, knID, branch, atName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckActionTypeExistByName", reflect.TypeOf((*MockActionTypeService)(nil).CheckActionTypeExistByName), ctx, knID, branch, atName)
}

// CreateActionTypes mocks base method.
func (m *MockActionTypeService) CreateActionTypes(ctx context.Context, tx *sql.Tx, actionTypes []*interfaces.ActionType, mode string, strictMode bool) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActionTypes", ctx, tx, actionTypes, mode, strictMode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActionTypes indicates an expected call of CreateActionTypes.
func (mr *MockActionTypeServiceMockRecorder) CreateActionTypes(ctx, tx, actionTypes, mode, strictMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActionTypes", reflect.TypeOf((*MockActionTypeService)(nil).CreateActionTypes), ctx, tx, actionTypes, mode, strictMode)
}

// DeleteActionTypesByIDs mocks base method.
func (m *MockActionTypeService) DeleteActionTypesByIDs(ctx context.Context, tx *sql.Tx, knID, branch string, atIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActionTypesByIDs", ctx, tx, knID, branch, atIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActionTypesByIDs indicates an expected call of DeleteActionTypesByIDs.
func (mr *MockActionTypeServiceMockRecorder) DeleteActionTypesByIDs(ctx, tx, knID, branch, atIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActionTypesByIDs", reflect.TypeOf((*MockActionTypeService)(nil).DeleteActionTypesByIDs), ctx, tx, knID, branch, atIDs)
}

// DeleteActionTypesByKnID mocks base method.
func (m *MockActionTypeService) DeleteActionTypesByKnID(ctx context.Context, tx *sql.Tx, knID, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActionTypesByKnID", ctx, tx, knID, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActionTypesByKnID indicates an expected call of DeleteActionTypesByKnID.
func (mr *MockActionTypeServiceMockRecorder) DeleteActionTypesByKnID(ctx, tx, knID, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActionTypesByKnID", reflect.TypeOf((*MockActionTypeService)(nil).DeleteActionTypesByKnID), ctx, tx, knID, branch)
}

// GetActionTypeIDsByKnID mocks base method.
func (m *MockActionTypeService) GetActionTypeIDsByKnID(ctx context.Context, knID, branch string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionTypeIDsByKnID", ctx, knID, branch)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionTypeIDsByKnID indicates an expected call of GetActionTypeIDsByKnID.
func (mr *MockActionTypeServiceMockRecorder) GetActionTypeIDsByKnID(ctx, knID, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionTypeIDsByKnID", reflect.TypeOf((*MockActionTypeService)(nil).GetActionTypeIDsByKnID), ctx, knID, branch)
}

// GetActionTypesByIDs mocks base method.
func (m *MockActionTypeService) GetActionTypesByIDs(ctx context.Context, knID, branch string, atIDs []string) ([]*interfaces.ActionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionTypesByIDs", ctx, knID, branch, atIDs)
	ret0, _ := ret[0].([]*interfaces.ActionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionTypesByIDs indicates an expected call of GetActionTypesByIDs.
func (mr *MockActionTypeServiceMockRecorder) GetActionTypesByIDs(ctx, knID, branch, atIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionTypesByIDs", reflect.TypeOf((*MockActionTypeService)(nil).GetActionTypesByIDs), ctx, knID, branch, atIDs)
}

// InsertDatasetData mocks base method.
func (m *MockActionTypeService) InsertDatasetData(ctx context.Context, actionTypes []*interfaces.ActionType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDatasetData", ctx, actionTypes)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertDatasetData indicates an expected call of InsertDatasetData.
func (mr *MockActionTypeServiceMockRecorder) InsertDatasetData(ctx, actionTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDatasetData", reflect.TypeOf((*MockActionTypeService)(nil).InsertDatasetData), ctx, actionTypes)
}

// ListActionTypeSummaries mocks base method.
func (m *MockActionTypeService) ListActionTypeSummaries(ctx context.Context, query interfaces.ActionTypesQueryParams) ([]*interfaces.ActionType, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActionTypeSummaries", ctx, query)
	ret0, _ := ret[0].([]*interfaces.ActionType)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActionTypeSummaries indicates an expected call of ListActionTypeSummaries.
func (mr *MockActionTypeServiceMockRecorder) ListActionTypeSummaries(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActionTypeSummaries", reflect.TypeOf((*MockActionTypeService)(nil).ListActionTypeSummaries), ctx, query)
}

// ListActionTypes mocks base method.
func (m *MockActionTypeService) ListActionTypes(ctx context.Context, query interfaces.ActionTypesQueryParams) ([]*interfaces.ActionType, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActionTypes", ctx, query)
	ret0, _ := ret[0].([]*interfaces.ActionType)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActionTypes indicates an expected call of ListActionTypes.
func (mr *MockActionTypeServiceMockRecorder) ListActionTypes(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActionTypes", reflect.TypeOf((*MockActionTypeService)(nil).ListActionTypes), ctx, query)
}

// SearchActionTypes mocks base method.
func (m *MockActionTypeService) SearchActionTypes(ctx context.Context, query *interfaces.ConceptsQuery) (interfaces.ActionTypes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchActionTypes", ctx, query)
	ret0, _ := ret[0].(interfaces.ActionTypes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchActionTypes indicates an expected call of SearchActionTypes.
func (mr *MockActionTypeServiceMockRecorder) SearchActionTypes(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchActionTypes", reflect.TypeOf((*MockActionTypeService)(nil).SearchActionTypes), ctx, query)
}

// UpdateActionType mocks base method.
func (m *MockActionTypeService) UpdateActionType(ctx context.Context, tx *sql.Tx, actionType *interfaces.ActionType, strictMode bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActionType", ctx, tx, actionType, strictMode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActionType indicates an expected call of UpdateActionType.
func (mr *MockActionTypeServiceMockRecorder) UpdateActionType(ctx, tx, actionType, strictMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActionType", reflect.TypeOf((*MockActionTypeService)(nil).UpdateActionType), ctx, tx, actionType, strictMode)
}

// ValidateActionTypes mocks base method.
func (m *MockActionTypeService) ValidateActionTypes(ctx context.Context, knID, branch string, actionTypes []*interfaces.ActionType, strictMode bool, batch *interfaces.BatchIDIndex, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateActionTypes", ctx, knID, branch, actionTypes, strictMode, batch, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateActionTypes indicates an expected call of ValidateActionTypes.
func (mr *MockActionTypeServiceMockRecorder) ValidateActionTypes(ctx, knID, branch, actionTypes, strictMode, batch, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateActionTypes", reflect.TypeOf((*MockActionTypeService)(nil).ValidateActionTypes), ctx, knID, branch, actionTypes, strictMode, batch, mode)
}
