// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/kn_proxy.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/kn_proxy.go -destination ../interfaces/mock/mock_kn_proxy.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	interfaces "bkn-backend/interfaces"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKNProxyAccess is a mock of KNProxyAccess interface.
type MockKNProxyAccess struct {
	ctrl     *gomock.Controller
	recorder *MockKNProxyAccessMockRecorder
	isgomock struct{}
}

// MockKNProxyAccessMockRecorder is the mock recorder for MockKNProxyAccess.
type MockKNProxyAccessMockRecorder struct {
	mock *MockKNProxyAccess
}

// NewMockKNProxyAccess creates a new mock instance.
func NewMockKNProxyAccess(ctrl *gomock.Controller) *MockKNProxyAccess {
	mock := &MockKNProxyAccess{ctrl: ctrl}
	mock.recorder = &MockKNProxyAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKNProxyAccess) EXPECT() *MockKNProxyAccessMockRecorder {
	return m.recorder
}

// DeletePublishedSnapshot mocks base method.
func (m *MockKNProxyAccess) DeletePublishedSnapshot(ctx context.Context, knID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePublishedSnapshot", ctx, knID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePublishedSnapshot indicates an expected call of DeletePublishedSnapshot.
func (mr *MockKNProxyAccessMockRecorder) DeletePublishedSnapshot(ctx, knID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePublishedSnapshot", reflect.TypeOf((*MockKNProxyAccess)(nil).DeletePublishedSnapshot), ctx, knID)
}

// Ensure mocks base method.
func (m *MockKNProxyAccess) Ensure(ctx context.Context, mapping *interfaces.KNProxyAccount) (*interfaces.KNProxyAccount, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ensure", ctx, mapping)
	ret0, _ := ret[0].(*interfaces.KNProxyAccount)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Ensure indicates an expected call of Ensure.
func (mr *MockKNProxyAccessMockRecorder) Ensure(ctx, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ensure", reflect.TypeOf((*MockKNProxyAccess)(nil).Ensure), ctx, mapping)
}

// Get mocks base method.
func (m *MockKNProxyAccess) Get(ctx context.Context, knID string) (*interfaces.KNProxyAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, knID)
	ret0, _ := ret[0].(*interfaces.KNProxyAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKNProxyAccessMockRecorder) Get(ctx, knID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKNProxyAccess)(nil).Get), ctx, knID)
}

// List mocks base method.
func (m *MockKNProxyAccess) List(ctx context.Context) ([]*interfaces.KNProxyAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*interfaces.KNProxyAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockKNProxyAccessMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockKNProxyAccess)(nil).List), ctx)
}

// ListProxyConflicts mocks base method.
func (m *MockKNProxyAccess) ListProxyConflicts(ctx context.Context) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProxyConflicts", ctx)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProxyConflicts indicates an expected call of ListProxyConflicts.
func (mr *MockKNProxyAccessMockRecorder) ListProxyConflicts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProxyConflicts", reflect.TypeOf((*MockKNProxyAccess)(nil).ListProxyConflicts), ctx)
}

// MarkSyncFailed mocks base method.
func (m *MockKNProxyAccess) MarkSyncFailed(ctx context.Context, knID string, generation int64, lockOwner, lastError string, updatedAt int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSyncFailed", ctx, knID, generation, lockOwner, lastError, updatedAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkSyncFailed indicates an expected call of MarkSyncFailed.
func (mr *MockKNProxyAccessMockRecorder) MarkSyncFailed(ctx, knID, generation, lockOwner, lastError, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSyncFailed", reflect.TypeOf((*MockKNProxyAccess)(nil).MarkSyncFailed), ctx, knID, generation, lockOwner, lastError, updatedAt)
}

// ReleaseLock mocks base method.
func (m *MockKNProxyAccess) ReleaseLock(ctx context.Context, knID, owner string, updatedAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseLock", ctx, knID, owner, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseLock indicates an expected call of ReleaseLock.
func (mr *MockKNProxyAccessMockRecorder) ReleaseLock(ctx, knID, owner, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseLock", reflect.TypeOf((*MockKNProxyAccess)(nil).ReleaseLock), ctx, knID, owner, updatedAt)
}

// RenewLock mocks base method.
func (m *MockKNProxyAccess) RenewLock(ctx context.Context, knID, owner string, now, lockUntil int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewLock", ctx, knID, owner, now, lockUntil)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenewLock indicates an expected call of RenewLock.
func (mr *MockKNProxyAccessMockRecorder) RenewLock(ctx, knID, owner, now, lockUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewLock", reflect.TypeOf((*MockKNProxyAccess)(nil).RenewLock), ctx, knID, owner, now, lockUntil)
}

// ReplacePublishedSnapshotAndMarkReady mocks base method.
func (m *MockKNProxyAccess) ReplacePublishedSnapshotAndMarkReady(ctx context.Context, knID string, generation int64, lockOwner, snapshotVersion string, sources []interfaces.ProxyGrantSourceSpec, updatedAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePublishedSnapshotAndMarkReady", ctx, knID, generation, lockOwner, snapshotVersion, sources, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplacePublishedSnapshotAndMarkReady indicates an expected call of ReplacePublishedSnapshotAndMarkReady.
func (mr *MockKNProxyAccessMockRecorder) ReplacePublishedSnapshotAndMarkReady(ctx, knID, generation, lockOwner, snapshotVersion, sources, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePublishedSnapshotAndMarkReady", reflect.TypeOf((*MockKNProxyAccess)(nil).ReplacePublishedSnapshotAndMarkReady), ctx, knID, generation, lockOwner, snapshotVersion, sources, updatedAt)
}

// ListPublishedSources mocks base method.
func (m *MockKNProxyAccess) ListPublishedSources(ctx context.Context, knID string, bindings []interfaces.KNProxyBindingRef) ([]interfaces.ProxyGrantSourceSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublishedSources", ctx, knID, bindings)
	ret0, _ := ret[0].([]interfaces.ProxyGrantSourceSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublishedSources indicates an expected call of ListPublishedSources.
func (mr *MockKNProxyAccessMockRecorder) ListPublishedSources(ctx, knID, bindings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublishedSources", reflect.TypeOf((*MockKNProxyAccess)(nil).ListPublishedSources), ctx, knID, bindings)
}

// ReplacePublishedBindingsAndMarkReady mocks base method.
func (m *MockKNProxyAccess) ReplacePublishedBindingsAndMarkReady(ctx context.Context, knID string, generation int64, lockOwner, snapshotVersion string, bindings []interfaces.KNProxyBindingRef, sources []interfaces.ProxyGrantSourceSpec, updatedAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePublishedBindingsAndMarkReady", ctx, knID, generation, lockOwner, snapshotVersion, bindings, sources, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplacePublishedBindingsAndMarkReady indicates an expected call of ReplacePublishedBindingsAndMarkReady.
func (mr *MockKNProxyAccessMockRecorder) ReplacePublishedBindingsAndMarkReady(ctx, knID, generation, lockOwner, snapshotVersion, bindings, sources, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePublishedBindingsAndMarkReady", reflect.TypeOf((*MockKNProxyAccess)(nil).ReplacePublishedBindingsAndMarkReady), ctx, knID, generation, lockOwner, snapshotVersion, bindings, sources, updatedAt)
}

// ReserveSyncGeneration mocks base method.
func (m *MockKNProxyAccess) ReserveSyncGeneration(ctx context.Context, knID, lockOwner string, updatedAt int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveSyncGeneration", ctx, knID, lockOwner, updatedAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveSyncGeneration indicates an expected call of ReserveSyncGeneration.
func (mr *MockKNProxyAccessMockRecorder) ReserveSyncGeneration(ctx, knID, lockOwner, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveSyncGeneration", reflect.TypeOf((*MockKNProxyAccess)(nil).ReserveSyncGeneration), ctx, knID, lockOwner, updatedAt)
}

// ResolvePublishedBinding mocks base method.
func (m *MockKNProxyAccess) ResolvePublishedBinding(ctx context.Context, knID string, binding interfaces.KNProxyBinding) (*interfaces.KNProxyBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePublishedBinding", ctx, knID, binding)
	ret0, _ := ret[0].(*interfaces.KNProxyBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePublishedBinding indicates an expected call of ResolvePublishedBinding.
func (mr *MockKNProxyAccessMockRecorder) ResolvePublishedBinding(ctx, knID, binding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePublishedBinding", reflect.TypeOf((*MockKNProxyAccess)(nil).ResolvePublishedBinding), ctx, knID, binding)
}

// ResolvePublishedBindings mocks base method.
func (m *MockKNProxyAccess) ResolvePublishedBindings(ctx context.Context, knID string, bindings []interfaces.KNProxyBinding) ([]interfaces.KNProxyBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePublishedBindings", ctx, knID, bindings)
	ret0, _ := ret[0].([]interfaces.KNProxyBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePublishedBindings indicates an expected call of ResolvePublishedBindings.
func (mr *MockKNProxyAccessMockRecorder) ResolvePublishedBindings(ctx, knID, bindings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePublishedBindings", reflect.TypeOf((*MockKNProxyAccess)(nil).ResolvePublishedBindings), ctx, knID, bindings)
}

// SetLifecycle mocks base method.
func (m *MockKNProxyAccess) SetLifecycle(ctx context.Context, knID, lifecycleStatus string, updatedAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLifecycle", ctx, knID, lifecycleStatus, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLifecycle indicates an expected call of SetLifecycle.
func (mr *MockKNProxyAccessMockRecorder) SetLifecycle(ctx, knID, lifecycleStatus, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLifecycle", reflect.TypeOf((*MockKNProxyAccess)(nil).SetLifecycle), ctx, knID, lifecycleStatus, updatedAt)
}

// SetPending mocks base method.
func (m *MockKNProxyAccess) SetPending(ctx context.Context, tx *sql.Tx, knID, modelVersion, grantorID, lockOwner string, updatedAt int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPending", ctx, tx, knID, modelVersion, grantorID, lockOwner, updatedAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPending indicates an expected call of SetPending.
func (mr *MockKNProxyAccessMockRecorder) SetPending(ctx, tx, knID, modelVersion, grantorID, lockOwner, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPending", reflect.TypeOf((*MockKNProxyAccess)(nil).SetPending), ctx, tx, knID, modelVersion, grantorID, lockOwner, updatedAt)
}

// TryAcquireLock mocks base method.
func (m *MockKNProxyAccess) TryAcquireLock(ctx context.Context, knID, owner string, now, lockUntil int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryAcquireLock", ctx, knID, owner, now, lockUntil)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryAcquireLock indicates an expected call of TryAcquireLock.
func (mr *MockKNProxyAccessMockRecorder) TryAcquireLock(ctx, knID, owner, now, lockUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryAcquireLock", reflect.TypeOf((*MockKNProxyAccess)(nil).TryAcquireLock), ctx, knID, owner, now, lockUntil)
}

// MockKNProxyBindingResolver is a mock of KNProxyBindingResolver interface.
type MockKNProxyBindingResolver struct {
	ctrl     *gomock.Controller
	recorder *MockKNProxyBindingResolverMockRecorder
	isgomock struct{}
}

// MockKNProxyBindingResolverMockRecorder is the mock recorder for MockKNProxyBindingResolver.
type MockKNProxyBindingResolverMockRecorder struct {
	mock *MockKNProxyBindingResolver
}

// NewMockKNProxyBindingResolver creates a new mock instance.
func NewMockKNProxyBindingResolver(ctrl *gomock.Controller) *MockKNProxyBindingResolver {
	mock := &MockKNProxyBindingResolver{ctrl: ctrl}
	mock.recorder = &MockKNProxyBindingResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKNProxyBindingResolver) EXPECT() *MockKNProxyBindingResolverMockRecorder {
	return m.recorder
}

// ResolveKNProxyBindings mocks base method.
func (m *MockKNProxyBindingResolver) ResolveKNProxyBindings(ctx context.Context, knID string, bindings []interfaces.KNProxyBinding) (*interfaces.KNProxyAccount, []interfaces.KNProxyBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveKNProxyBindings", ctx, knID, bindings)
	ret0, _ := ret[0].(*interfaces.KNProxyAccount)
	ret1, _ := ret[1].([]interfaces.KNProxyBinding)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResolveKNProxyBindings indicates an expected call of ResolveKNProxyBindings.
func (mr *MockKNProxyBindingResolverMockRecorder) ResolveKNProxyBindings(ctx, knID, bindings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveKNProxyBindings", reflect.TypeOf((*MockKNProxyBindingResolver)(nil).ResolveKNProxyBindings), ctx, knID, bindings)
}

// MockManagedProxyAccess is a mock of ManagedProxyAccess interface.
type MockManagedProxyAccess struct {
	ctrl     *gomock.Controller
	recorder *MockManagedProxyAccessMockRecorder
	isgomock struct{}
}

// MockManagedProxyAccessMockRecorder is the mock recorder for MockManagedProxyAccess.
type MockManagedProxyAccessMockRecorder struct {
	mock *MockManagedProxyAccess
}

// NewMockManagedProxyAccess creates a new mock instance.
func NewMockManagedProxyAccess(ctrl *gomock.Controller) *MockManagedProxyAccess {
	mock := &MockManagedProxyAccess{ctrl: ctrl}
	mock.recorder = &MockManagedProxyAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagedProxyAccess) EXPECT() *MockManagedProxyAccessMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockManagedProxyAccess) Archive(ctx context.Context, proxyAccountID string) (*interfaces.ManagedProxyAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, proxyAccountID)
	ret0, _ := ret[0].(*interfaces.ManagedProxyAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Archive indicates an expected call of Archive.
func (mr *MockManagedProxyAccessMockRecorder) Archive(ctx, proxyAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockManagedProxyAccess)(nil).Archive), ctx, proxyAccountID)
}

// CheckGrant mocks base method.
func (m *MockManagedProxyAccess) CheckGrant(ctx context.Context, proxyAccountID, grantorID string, source interfaces.ProxyGrantSourceSpec) (interfaces.ProxyGrantCheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckGrant", ctx, proxyAccountID, grantorID, source)
	ret0, _ := ret[0].(interfaces.ProxyGrantCheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckGrant indicates an expected call of CheckGrant.
func (mr *MockManagedProxyAccessMockRecorder) CheckGrant(ctx, proxyAccountID, grantorID, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckGrant", reflect.TypeOf((*MockManagedProxyAccess)(nil).CheckGrant), ctx, proxyAccountID, grantorID, source)
}

// CheckGrantDelta mocks base method.
func (m *MockManagedProxyAccess) CheckGrantDelta(ctx context.Context, proxyAccountID, grantorID string, upserts, removals []interfaces.ProxyGrantSourceSpec) (interfaces.ProxyGrantBatchCheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckGrantDelta", ctx, proxyAccountID, grantorID, upserts, removals)
	ret0, _ := ret[0].(interfaces.ProxyGrantBatchCheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckGrantDelta indicates an expected call of CheckGrantDelta.
func (mr *MockManagedProxyAccessMockRecorder) CheckGrantDelta(ctx, proxyAccountID, grantorID, upserts, removals any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckGrantDelta", reflect.TypeOf((*MockManagedProxyAccess)(nil).CheckGrantDelta), ctx, proxyAccountID, grantorID, upserts, removals)
}

// CheckGrants mocks base method.
func (m *MockManagedProxyAccess) CheckGrants(ctx context.Context, proxyAccountID, grantorID string, sources []interfaces.ProxyGrantSourceSpec) (interfaces.ProxyGrantBatchCheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckGrants", ctx, proxyAccountID, grantorID, sources)
	ret0, _ := ret[0].(interfaces.ProxyGrantBatchCheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckGrants indicates an expected call of CheckGrants.
func (mr *MockManagedProxyAccessMockRecorder) CheckGrants(ctx, proxyAccountID, grantorID, sources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckGrants", reflect.TypeOf((*MockManagedProxyAccess)(nil).CheckGrants), ctx, proxyAccountID, grantorID, sources)
}

// Create mocks base method.
func (m *MockManagedProxyAccess) Create(ctx context.Context, knID, name string) (*interfaces.ManagedProxyAccount, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, knID, name)
	ret0, _ := ret[0].(*interfaces.ManagedProxyAccount)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockManagedProxyAccessMockRecorder) Create(ctx, knID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockManagedProxyAccess)(nil).Create), ctx, knID, name)
}

// Disable mocks base method.
func (m *MockManagedProxyAccess) Disable(ctx context.Context, proxyAccountID string) (*interfaces.ManagedProxyAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, proxyAccountID)
	ret0, _ := ret[0].(*interfaces.ManagedProxyAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Disable indicates an expected call of Disable.
func (mr *MockManagedProxyAccessMockRecorder) Disable(ctx, proxyAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockManagedProxyAccess)(nil).Disable), ctx, proxyAccountID)
}

// ReconcileGrants mocks base method.
func (m *MockManagedProxyAccess) ReconcileGrants(ctx context.Context, proxyAccountID, requestedBy string) (interfaces.ProxyGrantReconcileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileGrants", ctx, proxyAccountID, requestedBy)
	ret0, _ := ret[0].(interfaces.ProxyGrantReconcileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileGrants indicates an expected call of ReconcileGrants.
func (mr *MockManagedProxyAccessMockRecorder) ReconcileGrants(ctx, proxyAccountID, requestedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileGrants", reflect.TypeOf((*MockManagedProxyAccess)(nil).ReconcileGrants), ctx, proxyAccountID, requestedBy)
}

// Restore mocks base method.
func (m *MockManagedProxyAccess) Restore(ctx context.Context, proxyAccountID string) (*interfaces.ManagedProxyAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, proxyAccountID)
	ret0, _ := ret[0].(*interfaces.ManagedProxyAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockManagedProxyAccessMockRecorder) Restore(ctx, proxyAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockManagedProxyAccess)(nil).Restore), ctx, proxyAccountID)
}

// SyncGrants mocks base method.
func (m *MockManagedProxyAccess) SyncGrants(ctx context.Context, proxyAccountID, grantorID string, syncGeneration int64, snapshotVersion string, sources []interfaces.ProxyGrantSourceSpec) (interfaces.ProxyGrantSyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncGrants", ctx, proxyAccountID, grantorID, syncGeneration, snapshotVersion, sources)
	ret0, _ := ret[0].(interfaces.ProxyGrantSyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncGrants indicates an expected call of SyncGrants.
func (mr *MockManagedProxyAccessMockRecorder) SyncGrants(ctx, proxyAccountID, grantorID, syncGeneration, snapshotVersion, sources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncGrants", reflect.TypeOf((*MockManagedProxyAccess)(nil).SyncGrants), ctx, proxyAccountID, grantorID, syncGeneration, snapshotVersion, sources)
}

// SyncGrantDelta mocks base method.
func (m *MockManagedProxyAccess) SyncGrantDelta(ctx context.Context, proxyAccountID, grantorID string, syncGeneration int64, baseSnapshotVersion, targetSnapshotVersion string, upserts, removals []interfaces.ProxyGrantSourceSpec) (interfaces.ProxyGrantSyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncGrantDelta", ctx, proxyAccountID, grantorID, syncGeneration, baseSnapshotVersion, targetSnapshotVersion, upserts, removals)
	ret0, _ := ret[0].(interfaces.ProxyGrantSyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncGrantDelta indicates an expected call of SyncGrantDelta.
func (mr *MockManagedProxyAccessMockRecorder) SyncGrantDelta(ctx, proxyAccountID, grantorID, syncGeneration, baseSnapshotVersion, targetSnapshotVersion, upserts, removals any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncGrantDelta", reflect.TypeOf((*MockManagedProxyAccess)(nil).SyncGrantDelta), ctx, proxyAccountID, grantorID, syncGeneration, baseSnapshotVersion, targetSnapshotVersion, upserts, removals)
}
