// Code generated by MockGen. DO NOT EDIT.
// Source: risk_type_service.go
//
// Generated by this command:
//
//	mockgen -source risk_type_service.go -destination mock/mock_risk_type_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	interfaces "github.com/openbkn-ai/bkn-foundry/adp/bkn/bkn-backend/server/interfaces"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRiskTypeService is a mock of RiskTypeService interface.
type MockRiskTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockRiskTypeServiceMockRecorder
	isgomock struct{}
}

// MockRiskTypeServiceMockRecorder is the mock recorder for MockRiskTypeService.
type MockRiskTypeServiceMockRecorder struct {
	mock *MockRiskTypeService
}

// NewMockRiskTypeService creates a new mock instance.
func NewMockRiskTypeService(ctrl *gomock.Controller) *MockRiskTypeService {
	mock := &MockRiskTypeService{ctrl: ctrl}
	mock.recorder = &MockRiskTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRiskTypeService) EXPECT() *MockRiskTypeServiceMockRecorder {
	return m.recorder
}

// CheckRiskTypeExistByID mocks base method.
func (m *MockRiskTypeService) CheckRiskTypeExistByID(ctx context.Context, knID, branch, rtID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRiskTypeExistByID", ctx, knID, branch, rtID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckRiskTypeExistByID indicates an expected call of CheckRiskTypeExistByID.
func (mr *MockRiskTypeServiceMockRecorder) CheckRiskTypeExistByID(ctx, knID, branch, rtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRiskTypeExistByID", reflect.TypeOf((*MockRiskTypeService)(nil).CheckRiskTypeExistByID), ctx, knID, branch, rtID)
}

// CheckRiskTypeExistByName mocks base method.
func (m *MockRiskTypeService) CheckRiskTypeExistByName(ctx context.Context, knID, branch, rtName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRiskTypeExistByName", ctx, knID, branch, rtName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckRiskTypeExistByName indicates an expected call of CheckRiskTypeExistByName.
func (mr *MockRiskTypeServiceMockRecorder) CheckRiskTypeExistByName(ctx, knID, branch, rtName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRiskTypeExistByName", reflect.TypeOf((*MockRiskTypeService)(nil).CheckRiskTypeExistByName), ctx, knID, branch, rtName)
}

// CreateRiskTypes mocks base method.
func (m *MockRiskTypeService) CreateRiskTypes(ctx context.Context, tx *sql.Tx, riskTypes []*interfaces.RiskType, mode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRiskTypes", ctx, tx, riskTypes, mode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRiskTypes indicates an expected call of CreateRiskTypes.
func (mr *MockRiskTypeServiceMockRecorder) CreateRiskTypes(ctx, tx, riskTypes, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRiskTypes", reflect.TypeOf((*MockRiskTypeService)(nil).CreateRiskTypes), ctx, tx, riskTypes, mode)
}

// DeleteRiskTypesByIDs mocks base method.
func (m *MockRiskTypeService) DeleteRiskTypesByIDs(ctx context.Context, tx *sql.Tx, knID, branch string, rtIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRiskTypesByIDs", ctx, tx, knID, branch, rtIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRiskTypesByIDs indicates an expected call of DeleteRiskTypesByIDs.
func (mr *MockRiskTypeServiceMockRecorder) DeleteRiskTypesByIDs(ctx, tx, knID, branch, rtIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRiskTypesByIDs", reflect.TypeOf((*MockRiskTypeService)(nil).DeleteRiskTypesByIDs), ctx, tx, knID, branch, rtIDs)
}

// DeleteRiskTypesByKnID mocks base method.
func (m *MockRiskTypeService) DeleteRiskTypesByKnID(ctx context.Context, tx *sql.Tx, knID, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRiskTypesByKnID", ctx, tx, knID, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRiskTypesByKnID indicates an expected call of DeleteRiskTypesByKnID.
func (mr *MockRiskTypeServiceMockRecorder) DeleteRiskTypesByKnID(ctx, tx, knID, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRiskTypesByKnID", reflect.TypeOf((*MockRiskTypeService)(nil).DeleteRiskTypesByKnID), ctx, tx, knID, branch)
}

// GetAllRiskTypesByKnID mocks base method.
func (m *MockRiskTypeService) GetAllRiskTypesByKnID(ctx context.Context, knID, branch string) ([]*interfaces.RiskType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRiskTypesByKnID", ctx, knID, branch)
	ret0, _ := ret[0].([]*interfaces.RiskType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRiskTypesByKnID indicates an expected call of GetAllRiskTypesByKnID.
func (mr *MockRiskTypeServiceMockRecorder) GetAllRiskTypesByKnID(ctx, knID, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRiskTypesByKnID", reflect.TypeOf((*MockRiskTypeService)(nil).GetAllRiskTypesByKnID), ctx, knID, branch)
}

// GetRiskTypesByIDs mocks base method.
func (m *MockRiskTypeService) GetRiskTypesByIDs(ctx context.Context, knID, branch string, rtIDs []string) ([]*interfaces.RiskType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRiskTypesByIDs", ctx, knID, branch, rtIDs)
	ret0, _ := ret[0].([]*interfaces.RiskType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRiskTypesByIDs indicates an expected call of GetRiskTypesByIDs.
func (mr *MockRiskTypeServiceMockRecorder) GetRiskTypesByIDs(ctx, knID, branch, rtIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRiskTypesByIDs", reflect.TypeOf((*MockRiskTypeService)(nil).GetRiskTypesByIDs), ctx, knID, branch, rtIDs)
}

// InsertDatasetData mocks base method.
func (m *MockRiskTypeService) InsertDatasetData(ctx context.Context, riskTypes []*interfaces.RiskType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDatasetData", ctx, riskTypes)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertDatasetData indicates an expected call of InsertDatasetData.
func (mr *MockRiskTypeServiceMockRecorder) InsertDatasetData(ctx, riskTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDatasetData", reflect.TypeOf((*MockRiskTypeService)(nil).InsertDatasetData), ctx, riskTypes)
}

// ListRiskTypes mocks base method.
func (m *MockRiskTypeService) ListRiskTypes(ctx context.Context, query interfaces.RiskTypesQueryParams) ([]*interfaces.RiskType, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRiskTypes", ctx, query)
	ret0, _ := ret[0].([]*interfaces.RiskType)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRiskTypes indicates an expected call of ListRiskTypes.
func (mr *MockRiskTypeServiceMockRecorder) ListRiskTypes(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRiskTypes", reflect.TypeOf((*MockRiskTypeService)(nil).ListRiskTypes), ctx, query)
}

// SearchRiskTypes mocks base method.
func (m *MockRiskTypeService) SearchRiskTypes(ctx context.Context, query *interfaces.ConceptsQuery) (interfaces.RiskTypes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRiskTypes", ctx, query)
	ret0, _ := ret[0].(interfaces.RiskTypes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRiskTypes indicates an expected call of SearchRiskTypes.
func (mr *MockRiskTypeServiceMockRecorder) SearchRiskTypes(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRiskTypes", reflect.TypeOf((*MockRiskTypeService)(nil).SearchRiskTypes), ctx, query)
}

// UpdateRiskType mocks base method.
func (m *MockRiskTypeService) UpdateRiskType(ctx context.Context, tx *sql.Tx, riskType *interfaces.RiskType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRiskType", ctx, tx, riskType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRiskType indicates an expected call of UpdateRiskType.
func (mr *MockRiskTypeServiceMockRecorder) UpdateRiskType(ctx, tx, riskType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRiskType", reflect.TypeOf((*MockRiskTypeService)(nil).UpdateRiskType), ctx, tx, riskType)
}
