// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/object_data_stats_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/object_data_stats_service.go -destination ../interfaces/mock/mock_object_data_stats_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	interfaces "bkn-backend/interfaces"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectDataStatsService is a mock of ObjectDataStatsService interface.
type MockObjectDataStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockObjectDataStatsServiceMockRecorder
	isgomock struct{}
}

// MockObjectDataStatsServiceMockRecorder is the mock recorder for MockObjectDataStatsService.
type MockObjectDataStatsServiceMockRecorder struct {
	mock *MockObjectDataStatsService
}

// NewMockObjectDataStatsService creates a new mock instance.
func NewMockObjectDataStatsService(ctrl *gomock.Controller) *MockObjectDataStatsService {
	mock := &MockObjectDataStatsService{ctrl: ctrl}
	mock.recorder = &MockObjectDataStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectDataStatsService) EXPECT() *MockObjectDataStatsServiceMockRecorder {
	return m.recorder
}

// ObjectDataStats mocks base method.
func (m *MockObjectDataStatsService) ObjectDataStats(ctx context.Context, req interfaces.ObjectDataStatsRequest) (*interfaces.ObjectDataStatsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObjectDataStats", ctx, req)
	ret0, _ := ret[0].(*interfaces.ObjectDataStatsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ObjectDataStats indicates an expected call of ObjectDataStats.
func (mr *MockObjectDataStatsServiceMockRecorder) ObjectDataStats(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectDataStats", reflect.TypeOf((*MockObjectDataStatsService)(nil).ObjectDataStats), ctx, req)
}
