// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/capability_binding_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/capability_binding_service.go -destination ../interfaces/mock/mock_capability_binding_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	interfaces "bkn-backend/interfaces"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCapabilityBindingService is a mock of CapabilityBindingService interface.
type MockCapabilityBindingService struct {
	ctrl     *gomock.Controller
	recorder *MockCapabilityBindingServiceMockRecorder
	isgomock struct{}
}

// MockCapabilityBindingServiceMockRecorder is the mock recorder for MockCapabilityBindingService.
type MockCapabilityBindingServiceMockRecorder struct {
	mock *MockCapabilityBindingService
}

// NewMockCapabilityBindingService creates a new mock instance.
func NewMockCapabilityBindingService(ctrl *gomock.Controller) *MockCapabilityBindingService {
	mock := &MockCapabilityBindingService{ctrl: ctrl}
	mock.recorder = &MockCapabilityBindingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapabilityBindingService) EXPECT() *MockCapabilityBindingServiceMockRecorder {
	return m.recorder
}

// AttachCapabilities mocks base method.
func (m *MockCapabilityBindingService) AttachCapabilities(ctx context.Context, tx *sql.Tx, knID, branch string, entries []*interfaces.AttachCapabilityEntry) ([]*interfaces.CapabilityBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachCapabilities", ctx, tx, knID, branch, entries)
	ret0, _ := ret[0].([]*interfaces.CapabilityBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachCapabilities indicates an expected call of AttachCapabilities.
func (mr *MockCapabilityBindingServiceMockRecorder) AttachCapabilities(ctx, tx, knID, branch, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachCapabilities", reflect.TypeOf((*MockCapabilityBindingService)(nil).AttachCapabilities), ctx, tx, knID, branch, entries)
}

// DeleteCapabilitiesByKnID mocks base method.
func (m *MockCapabilityBindingService) DeleteCapabilitiesByKnID(ctx context.Context, tx *sql.Tx, knID, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCapabilitiesByKnID", ctx, tx, knID, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCapabilitiesByKnID indicates an expected call of DeleteCapabilitiesByKnID.
func (mr *MockCapabilityBindingServiceMockRecorder) DeleteCapabilitiesByKnID(ctx, tx, knID, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCapabilitiesByKnID", reflect.TypeOf((*MockCapabilityBindingService)(nil).DeleteCapabilitiesByKnID), ctx, tx, knID, branch)
}

// DetachCapabilities mocks base method.
func (m *MockCapabilityBindingService) DetachCapabilities(ctx context.Context, tx *sql.Tx, knID, branch string, bindingIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachCapabilities", ctx, tx, knID, branch, bindingIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetachCapabilities indicates an expected call of DetachCapabilities.
func (mr *MockCapabilityBindingServiceMockRecorder) DetachCapabilities(ctx, tx, knID, branch, bindingIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachCapabilities", reflect.TypeOf((*MockCapabilityBindingService)(nil).DetachCapabilities), ctx, tx, knID, branch, bindingIDs)
}

// GetCapabilityTotalsByType mocks base method.
func (m *MockCapabilityBindingService) GetCapabilityTotalsByType(ctx context.Context, knID, branch string) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCapabilityTotalsByType", ctx, knID, branch)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCapabilityTotalsByType indicates an expected call of GetCapabilityTotalsByType.
func (mr *MockCapabilityBindingServiceMockRecorder) GetCapabilityTotalsByType(ctx, knID, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCapabilityTotalsByType", reflect.TypeOf((*MockCapabilityBindingService)(nil).GetCapabilityTotalsByType), ctx, knID, branch)
}

// ListCapabilities mocks base method.
func (m *MockCapabilityBindingService) ListCapabilities(ctx context.Context, query interfaces.CapabilityBindingsQueryParams) (*interfaces.CapabilityBindingsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCapabilities", ctx, query)
	ret0, _ := ret[0].(*interfaces.CapabilityBindingsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCapabilities indicates an expected call of ListCapabilities.
func (mr *MockCapabilityBindingServiceMockRecorder) ListCapabilities(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCapabilities", reflect.TypeOf((*MockCapabilityBindingService)(nil).ListCapabilities), ctx, query)
}
