// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/vega_backend_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/vega_backend_access.go -destination ../interfaces/mock/mock_vega_backend_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	interfaces "bkn-backend/interfaces"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVegaBackendAccess is a mock of VegaBackendAccess interface.
type MockVegaBackendAccess struct {
	ctrl     *gomock.Controller
	recorder *MockVegaBackendAccessMockRecorder
	isgomock struct{}
}

// MockVegaBackendAccessMockRecorder is the mock recorder for MockVegaBackendAccess.
type MockVegaBackendAccessMockRecorder struct {
	mock *MockVegaBackendAccess
}

// NewMockVegaBackendAccess creates a new mock instance.
func NewMockVegaBackendAccess(ctrl *gomock.Controller) *MockVegaBackendAccess {
	mock := &MockVegaBackendAccess{ctrl: ctrl}
	mock.recorder = &MockVegaBackendAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVegaBackendAccess) EXPECT() *MockVegaBackendAccessMockRecorder {
	return m.recorder
}

// CreateCatalog mocks base method.
func (m *MockVegaBackendAccess) CreateCatalog(ctx context.Context, req *interfaces.CatalogRequest) (*interfaces.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCatalog", ctx, req)
	ret0, _ := ret[0].(*interfaces.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCatalog indicates an expected call of CreateCatalog.
func (mr *MockVegaBackendAccessMockRecorder) CreateCatalog(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCatalog", reflect.TypeOf((*MockVegaBackendAccess)(nil).CreateCatalog), ctx, req)
}

// CreateResource mocks base method.
func (m *MockVegaBackendAccess) CreateResource(ctx context.Context, req *interfaces.VegaResource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResource", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateResource indicates an expected call of CreateResource.
func (mr *MockVegaBackendAccessMockRecorder) CreateResource(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResource", reflect.TypeOf((*MockVegaBackendAccess)(nil).CreateResource), ctx, req)
}

// DeleteDatasetDocumentByID mocks base method.
func (m *MockVegaBackendAccess) DeleteDatasetDocumentByID(ctx context.Context, datasetID, docID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDatasetDocumentByID", ctx, datasetID, docID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDatasetDocumentByID indicates an expected call of DeleteDatasetDocumentByID.
func (mr *MockVegaBackendAccessMockRecorder) DeleteDatasetDocumentByID(ctx, datasetID, docID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDatasetDocumentByID", reflect.TypeOf((*MockVegaBackendAccess)(nil).DeleteDatasetDocumentByID), ctx, datasetID, docID)
}

// DeleteDatasetDocumentsByQuery mocks base method.
func (m *MockVegaBackendAccess) DeleteDatasetDocumentsByQuery(ctx context.Context, datasetID string, filterCondition map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDatasetDocumentsByQuery", ctx, datasetID, filterCondition)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDatasetDocumentsByQuery indicates an expected call of DeleteDatasetDocumentsByQuery.
func (mr *MockVegaBackendAccessMockRecorder) DeleteDatasetDocumentsByQuery(ctx, datasetID, filterCondition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDatasetDocumentsByQuery", reflect.TypeOf((*MockVegaBackendAccess)(nil).DeleteDatasetDocumentsByQuery), ctx, datasetID, filterCondition)
}

// DeleteResource mocks base method.
func (m *MockVegaBackendAccess) DeleteResource(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResource", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResource indicates an expected call of DeleteResource.
func (mr *MockVegaBackendAccessMockRecorder) DeleteResource(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResource", reflect.TypeOf((*MockVegaBackendAccess)(nil).DeleteResource), ctx, id)
}

// GetCatalogByID mocks base method.
func (m *MockVegaBackendAccess) GetCatalogByID(ctx context.Context, id string) (*interfaces.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCatalogByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCatalogByID indicates an expected call of GetCatalogByID.
func (mr *MockVegaBackendAccessMockRecorder) GetCatalogByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCatalogByID", reflect.TypeOf((*MockVegaBackendAccess)(nil).GetCatalogByID), ctx, id)
}

// GetResourceByID mocks base method.
func (m *MockVegaBackendAccess) GetResourceByID(ctx context.Context, id string) (*interfaces.VegaResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.VegaResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceByID indicates an expected call of GetResourceByID.
func (mr *MockVegaBackendAccessMockRecorder) GetResourceByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceByID", reflect.TypeOf((*MockVegaBackendAccess)(nil).GetResourceByID), ctx, id)
}

// QueryResourceData mocks base method.
func (m *MockVegaBackendAccess) QueryResourceData(ctx context.Context, resourceID string, params *interfaces.ResourceDataQueryParams) (*interfaces.DatasetQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryResourceData", ctx, resourceID, params)
	ret0, _ := ret[0].(*interfaces.DatasetQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryResourceData indicates an expected call of QueryResourceData.
func (mr *MockVegaBackendAccessMockRecorder) QueryResourceData(ctx, resourceID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryResourceData", reflect.TypeOf((*MockVegaBackendAccess)(nil).QueryResourceData), ctx, resourceID, params)
}

// RawQuery mocks base method.
func (m *MockVegaBackendAccess) RawQuery(ctx context.Context, req *interfaces.RawQueryRequest) (*interfaces.RawQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawQuery", ctx, req)
	ret0, _ := ret[0].(*interfaces.RawQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawQuery indicates an expected call of RawQuery.
func (mr *MockVegaBackendAccessMockRecorder) RawQuery(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawQuery", reflect.TypeOf((*MockVegaBackendAccess)(nil).RawQuery), ctx, req)
}

// WriteDatasetDocuments mocks base method.
func (m *MockVegaBackendAccess) WriteDatasetDocuments(ctx context.Context, datasetID string, documents []map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteDatasetDocuments", ctx, datasetID, documents)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteDatasetDocuments indicates an expected call of WriteDatasetDocuments.
func (mr *MockVegaBackendAccessMockRecorder) WriteDatasetDocuments(ctx, datasetID, documents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteDatasetDocuments", reflect.TypeOf((*MockVegaBackendAccess)(nil).WriteDatasetDocuments), ctx, datasetID, documents)
}
