// Copyright openbkn.ai
// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Package knrerank knowledge rearrangement module.
// Sort the input candidate concept list by relevance and filter out concepts that are irrelevant to the problem.
package knrerank

import (
	"bytes"
	"context"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"text/template"

	"github.com/openbkn-ai/bkn-foundry/adp/context-loader/agent-retrieval/server/infra/config"
	"github.com/openbkn-ai/bkn-foundry/adp/context-loader/agent-retrieval/server/interfaces"
)

// rerankPromptTemplate rerank prompt word template.
// Variable description:
//
//	{{.Intent}} - user intent (optional)
//	{{.Question}} - user question.
//	{{.Concepts}} - list of concepts (dynamically generated by code)
//
// rerankPromptTemplateStr reorder prompt word template string.
const rerankPromptTemplateStr = `{{if .Intent}}用户的意图是：{{.Intent}}
{{end}}问题: {{.Question}}
请仔细分析以下概念列表，只返回与上述问题相关的概念编号。对于与问题无关的概念，请完全忽略，不要在输出中包含它们。请按照与问题相关性从高到低的顺序返回概念编号。
概念列表:{{.Concepts}}
请只返回与问题相关的概念编号，按照相关性排序，以列表形式返回，例如：[3, 1, 5]，都不相关，返回[]`

const (
	promptBufferBaseSize       = 350
	promptBufferPerConceptSize = 100
)

// Precompile the template and execute panic during init to ensure that the template is correct.
var rerankTemplate = template.Must(template.New("rerank").Parse(rerankPromptTemplateStr))

// promptData template rendering data structure.
type promptData struct {
	Intent   string // User intent (optional)
	Question string // User issues.
	Concepts string // concept list.
}

// KnowledgeReranker Knowledge Reranker.
type KnowledgeReranker struct {
	mfModelClient interfaces.DrivenMFModelAPIClient
	logger        interfaces.Logger
	config        *config.RerankLLMConfig
}

// Singleton support.
var (
	rerankerOnce sync.Once
	rerankerInst *KnowledgeReranker
)

// NewKnowledgeReranker Gets a single instance of the knowledge reranker.
func NewKnowledgeReranker(
	mfModelClient interfaces.DrivenMFModelAPIClient,
	logger interfaces.Logger,
) *KnowledgeReranker {
	rerankerOnce.Do(func() {
		conf := config.NewConfigLoader()
		rerankerInst = &KnowledgeReranker{
			mfModelClient: mfModelClient,
			logger:        logger,
			config:        &conf.RerankLLM,
		}
	})
	return rerankerInst
}

// Rerank Main Entrance: Rerank Concepts.
func (r *KnowledgeReranker) Rerank(ctx context.Context, req *interfaces.KnowledgeRerankReq) ([]*interfaces.ConceptResult, error) {
	if len(req.KnowledgeConcepts) == 0 {
		return []*interfaces.ConceptResult{}, nil
	}

	// Distributed based on action type.
	switch req.Action {
	case interfaces.KnowledgeRerankActionVector:
		return r.rerankByVector(ctx, req)
	case interfaces.KnowledgeRerankActionLLM, interfaces.KnowledgeRerankActionDefault, "":
		return r.rerankByLLM(ctx, req)
	default:
		// Use LLM mode by default.
		return r.rerankByLLM(ctx, req)
	}
}

// rerankByLLM Use LLM for reranking.
func (r *KnowledgeReranker) rerankByLLM(ctx context.Context, req *interfaces.KnowledgeRerankReq) ([]*interfaces.ConceptResult, error) {
	concepts := req.KnowledgeConcepts
	question := ""
	var intents []interface{}

	if req.QueryUnderstanding != nil {
		question = req.QueryUnderstanding.OriginQuery
		if len(req.QueryUnderstanding.Intent) > 0 {
			for _, intent := range req.QueryUnderstanding.Intent {
				intents = append(intents, intent)
			}
		}
	}

	// Obtain account information (for header transparent transmission)
	accountID := ""
	accountType := "user"

	// batch processing.
	batchSize := 128
	allIndices := []int{}
	seen := make(map[int]bool)

	for i := 0; i < len(concepts); i += batchSize {
		end := i + batchSize
		if end > len(concepts) {
			end = len(concepts)
		}
		batchConcepts := concepts[i:end]
		batchStartIndex := i

		// BuildPrompt.
		prompt := r.buildPrompt(question, batchConcepts, intents)

		// Call LLM (req.LLMModel is overridden by per-request; it is the default large model of the empty walking system)
		indices, err := r.processLLMBatch(ctx, prompt, accountID, accountType, req.LLMModel)
		if err != nil {
			r.logger.WithContext(ctx).Warnf("[KnowledgeReranker#rerankByLLM] Batch %d failed: %v", i/batchSize+1, err)
			// When the batch fails, no index is added (downgrade processing)
			continue
		}

		// Convert to global index.
		for _, idx := range indices {
			globalIdx := idx + batchStartIndex
			if globalIdx >= 0 && globalIdx < len(concepts) && !seen[globalIdx] {
				allIndices = append(allIndices, globalIdx)
				seen[globalIdx] = true
			}
		}
	}

	// Record the index collection returned by LLM.
	llmReturnedIndices := make(map[int]bool)
	for _, idx := range allIndices {
		llmReturnedIndices[idx] = true
	}

	// Supplement unselected indexes (maintain original order)
	for i := 0; i < len(concepts); i++ {
		if !seen[i] {
			allIndices = append(allIndices, i)
		}
	}

	// Construction results: binary scoring.
	results := make([]*interfaces.ConceptResult, len(concepts))
	for i, idx := range allIndices {
		concept := concepts[idx]
		// Deep copy concept.
		result := *concept
		if llmReturnedIndices[idx] {
			result.RerankScore = 1.0 // Concepts selected by LLM.
		} else {
			result.RerankScore = 0.0 // unchecked concept.
		}
		results[i] = &result
	}

	r.logger.WithContext(ctx).Infof("[KnowledgeReranker#rerankByLLM] Reranked %d concepts, %d selected",
		len(concepts), len(llmReturnedIndices))

	return results, nil
}

// rerankByVector uses vector services for reordering.
func (r *KnowledgeReranker) rerankByVector(ctx context.Context, req *interfaces.KnowledgeRerankReq) ([]*interfaces.ConceptResult, error) {
	concepts := req.KnowledgeConcepts
	question := ""
	if req.QueryUnderstanding != nil {
		question = req.QueryUnderstanding.OriginQuery
	}

	// Formatting concepts for text slicing.
	documents := make([]string, len(concepts))
	for i, concept := range concepts {
		text, err := r.formatConceptText(concept)
		if err != nil {
			r.logger.WithContext(ctx).Warnf("[KnowledgeReranker#rerankByVector] Format concept failed: %v", err)
			documents[i] = concept.ConceptName // Fall back to the name.
		} else {
			documents[i] = text
		}
	}

	// Call the vector reranking service (req.VectorModel is the default reranker configured for out-of-the-box model management, see #842)
	resp, err := r.mfModelClient.Rerank(ctx, question, documents, req.VectorModel)
	if err != nil {
		r.logger.WithContext(ctx).Errorf("[KnowledgeReranker#rerankByVector] Rerank service failed: %v", err)
		// Demotion: Return to the original order, all scores are 0.
		results := make([]*interfaces.ConceptResult, len(concepts))
		for i, concept := range concepts {
			result := *concept
			result.RerankScore = 0.0
			results[i] = &result
		}
		return results, nil
	}

	// Create an index-to-score mapping.
	scoreMap := make(map[int]float64)
	for _, result := range resp.Results {
		scoreMap[result.Index] = result.RelevanceScore
	}

	// Build results and sort by score.
	type scoredConcept struct {
		concept *interfaces.ConceptResult
		score   float64
	}
	scored := make([]scoredConcept, len(concepts))
	for i, concept := range concepts {
		result := *concept
		if score, ok := scoreMap[i]; ok {
			result.RerankScore = score
		} else {
			result.RerankScore = 0.0
		}
		scored[i] = scoredConcept{concept: &result, score: result.RerankScore}
	}

	// Sort by score descending.
	sort.Slice(scored, func(i, j int) bool {
		return scored[i].score > scored[j].score
	})

	// Extract results.
	results := make([]*interfaces.ConceptResult, len(scored))
	for i, s := range scored {
		results[i] = s.concept
	}

	r.logger.WithContext(ctx).Infof("[KnowledgeReranker#rerankByVector] Reranked %d concepts", len(concepts))

	return results, nil
}

// buildPrompt build reorderPrompt.
func (r *KnowledgeReranker) buildPrompt(question string, concepts []*interfaces.ConceptResult, intents []interface{}) string {
	// 1. Build a concept list.
	conceptsList := r.buildConceptsList(concepts)

	// 2. Format intent text.
	intentText := ""
	if len(intents) > 0 {
		intentText = r.formatIntentsText(intents)
	}

	// 3. Render template.
	data := promptData{
		Intent:   intentText,
		Question: question,
		Concepts: conceptsList,
	}

	var buf bytes.Buffer
	buf.Grow(promptBufferBaseSize + len(concepts)*promptBufferPerConceptSize)

	if err := rerankTemplate.Execute(&buf, data); err != nil {
		r.logger.Errorf("[KnowledgeReranker#buildPrompt] Template execution failed: %v", err)
		// Downgrade: The template is precompiled and the data is a pure string. There are very few errors. A simplified version is returned here.
		return fmt.Sprintf("问题: %s\n概念列表:%s", question, conceptsList)
	}

	return buf.String()
}

// buildConceptsList build concept list string.
func (r *KnowledgeReranker) buildConceptsList(concepts []*interfaces.ConceptResult) string {
	var builder strings.Builder
	builder.Grow(len(concepts) * promptBufferPerConceptSize)

	for i, concept := range concepts {
		text, err := r.formatConceptText(concept)
		if err != nil {
			text = concept.ConceptName // Fall back to the name.
		}
		fmt.Fprintf(&builder, "\n[%d] %s", i+1, text)
	}

	return builder.String()
}

// formatConceptText formats a concept into natural language text.
func (r *KnowledgeReranker) formatConceptText(concept *interfaces.ConceptResult) (string, error) {
	conceptType := string(concept.ConceptType)
	conceptName := concept.ConceptName

	// Validaterequiredfield.
	if conceptType == "" || conceptName == "" {
		return "", fmt.Errorf("概念缺少必要的类型或名称信息")
	}

	var text strings.Builder
	text.WriteString(fmt.Sprintf("我们有一个'%s'的概念", conceptName))

	// Add conceptual details - type assertion required.
	if concept.ConceptDetail != nil {
		conceptDetail, ok := concept.ConceptDetail.(map[string]interface{})
		if ok {
			// Process the comment field - directly splice "described as xxx".
			if comment, ok := conceptDetail["comment"].(string); ok && comment != "" {
				text.WriteString(fmt.Sprintf("，描述为%s", comment))
			}

			// Process the comment field under data_properties - put it into the attribute description array.
			var attrDescriptions []string
			if dataProps, ok := conceptDetail["data_properties"].([]interface{}); ok {
				for _, prop := range dataProps {
					if propMap, ok := prop.(map[string]interface{}); ok {
						if propComment, ok := propMap["comment"].(string); ok && propComment != "" {
							attrDescriptions = append(attrDescriptions, propComment)
						}
					}
				}
			}

			if len(attrDescriptions) > 0 {
				text.WriteString("，具有")
				text.WriteString(strings.Join(attrDescriptions, "，"))
			}
		}
	}

	text.WriteString("。")
	return text.String(), nil
}

// formatIntentsText formats a list of intents as text.
func (r *KnowledgeReranker) formatIntentsText(intents []interface{}) string {
	if len(intents) == 0 {
		return ""
	}

	var intentTexts []string
	for i, intent := range intents {
		intentMap, ok := intent.(map[string]interface{})
		if !ok {
			continue
		}

		querySegment, _ := intentMap["query_segment"].(string)
		if querySegment == "" {
			continue
		}

		var parts []string
		parts = append(parts, fmt.Sprintf("意图%d是关于'%s'", i+1, querySegment))

		if confidence, ok := intentMap["confidence"].(float64); ok && confidence > 0 {
			parts = append(parts, fmt.Sprintf("置信度为%v", confidence))
		}

		if reasoning, ok := intentMap["reasoning"].(string); ok && reasoning != "" {
			parts = append(parts, fmt.Sprintf("推理说明：%s", reasoning))
		}

		// Processing Related Concepts - Fallback Logic.
		if relatedConcepts, ok := intentMap["related_concepts"].([]interface{}); ok && len(relatedConcepts) > 0 {
			var names []string
			for _, rc := range relatedConcepts {
				rcMap, ok := rc.(map[string]interface{})
				if !ok {
					continue
				}
				// Get concept_name first, if it does not exist, get concept_id.
				name := ""
				if n, ok := rcMap["concept_name"].(string); ok && n != "" {
					name = n
				} else if id, ok := rcMap["concept_id"].(string); ok && id != "" {
					name = id
				}
				if name != "" {
					names = append(names, name)
				}
			}
			if len(names) > 0 {
				parts = append(parts, fmt.Sprintf("相关概念包括：%s", strings.Join(names, ", ")))
			}
		}

		intentTexts = append(intentTexts, strings.Join(parts, "，"))
	}

	if len(intentTexts) == 0 {
		return ""
	}

	return strings.Join(intentTexts, "；") + "。"
}

// processLLMBatch processes a single LLM batch; model comes from per-request coverage, and when it is empty, it is handed over to mf-model-api to parse the system default large model.
func (r *KnowledgeReranker) processLLMBatch(ctx context.Context, prompt, accountID, accountType, model string) ([]int, error) {
	// Build message.
	messages := []interfaces.LLMMessage{
		{
			Role:    "system",
			Content: "你是一个智能概念筛选和排序助手。你能够根据用户提出的问题，从概念列表中筛选出相关的概念，并按照相关性进行排序，只返回相关概念的编号。",
		},
		{
			Role:    "user",
			Content: prompt,
		},
	}

	// Build request. model is per-request coverage (req.LLMModel); empty => mf-model-api uses the system default large model and does not pin the model name in configmap.
	req := &interfaces.LLMChatReq{
		Model:            model,
		Messages:         messages,
		Temperature:      r.config.Temperature,
		TopK:             r.config.TopK,
		TopP:             r.config.TopP,
		FrequencyPenalty: r.config.FrequencyPenalty,
		PresencePenalty:  r.config.PresencePenalty,
		MaxTokens:        r.config.MaxTokens,
		Stream:           true,
		AccountID:        accountID,
		AccountType:      accountType,
	}

	// Call LLM.
	content, err := r.mfModelClient.Chat(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("LLM call failed: %w", err)
	}

	r.logger.WithContext(ctx).Debugf("[KnowledgeReranker#processLLMBatch] LLM response: %s", content)

	// Parse the response.
	return r.parseIndices(content)
}

// parseIndices parses a list of indices from an LLM response.
func (r *KnowledgeReranker) parseIndices(content string) ([]int, error) {
	// Prioritize matching JSON array format [1, 2, 3]
	arrayRegex := regexp.MustCompile(`\[([0-9,\s]+)\]`)
	match := arrayRegex.FindStringSubmatch(content)
	if len(match) > 1 {
		indicesStr := match[1]
		return r.parseNumberList(indicesStr)
	}

	// Downgrade: match all numbers.
	numberRegex := regexp.MustCompile(`\d+`)
	matches := numberRegex.FindAllString(content, -1)
	if len(matches) == 0 {
		return []int{}, nil
	}

	var indices []int
	for _, m := range matches {
		n, err := strconv.Atoi(m)
		if err == nil && n > 0 {
			indices = append(indices, n-1) // Convert to 0-based indexing.
		}
	}

	return indices, nil
}

// parseNumberList parses a comma separated list of numbers.
func (r *KnowledgeReranker) parseNumberList(s string) ([]int, error) {
	var indices []int
	parts := strings.Split(s, ",")
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		n, err := strconv.Atoi(p)
		if err != nil {
			continue
		}
		if n > 0 {
			indices = append(indices, n-1) // Convert to 0-based indexing.
		}
	}
	return indices, nil
}
