// Code generated by MockGen. DO NOT EDIT.
// Source: ./personal_space_svc.go
//
// Generated by this command:
//
//	mockgen -source=./personal_space_svc.go -destination ./v3portdrivermock/personal_space_svc.go -package v3portdrivermock
//

// Package v3portdrivermock is a generated GoMock package.
package v3portdrivermock

import (
	context "context"
	reflect "reflect"

	personalspacereq "github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/driveradapter/api/rdto/personal_space/personalspacereq"
	personalspaceresp "github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/driveradapter/api/rdto/personal_space/personalspaceresp"
	gomock "go.uber.org/mock/gomock"
)

// MockIPersonalSpaceService is a mock of IPersonalSpaceService interface.
type MockIPersonalSpaceService struct {
	ctrl     *gomock.Controller
	recorder *MockIPersonalSpaceServiceMockRecorder
	isgomock struct{}
}

// MockIPersonalSpaceServiceMockRecorder is the mock recorder for MockIPersonalSpaceService.
type MockIPersonalSpaceServiceMockRecorder struct {
	mock *MockIPersonalSpaceService
}

// NewMockIPersonalSpaceService creates a new mock instance.
func NewMockIPersonalSpaceService(ctrl *gomock.Controller) *MockIPersonalSpaceService {
	mock := &MockIPersonalSpaceService{ctrl: ctrl}
	mock.recorder = &MockIPersonalSpaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPersonalSpaceService) EXPECT() *MockIPersonalSpaceServiceMockRecorder {
	return m.recorder
}

// AgentList mocks base method.
func (m *MockIPersonalSpaceService) AgentList(ctx context.Context, req *personalspacereq.AgentListReq) (*personalspaceresp.AgentListResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentList", ctx, req)
	ret0, _ := ret[0].(*personalspaceresp.AgentListResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentList indicates an expected call of AgentList.
func (mr *MockIPersonalSpaceServiceMockRecorder) AgentList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentList", reflect.TypeOf((*MockIPersonalSpaceService)(nil).AgentList), ctx, req)
}

// AgentTplList mocks base method.
func (m *MockIPersonalSpaceService) AgentTplList(ctx context.Context, req *personalspacereq.AgentTplListReq) (*personalspaceresp.AgentTplListResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentTplList", ctx, req)
	ret0, _ := ret[0].(*personalspaceresp.AgentTplListResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentTplList indicates an expected call of AgentTplList.
func (mr *MockIPersonalSpaceServiceMockRecorder) AgentTplList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentTplList", reflect.TypeOf((*MockIPersonalSpaceService)(nil).AgentTplList), ctx, req)
}
