// Code generated by MockGen. DO NOT EDIT.
// Source: ./release.go
//
// Generated by this command:
//
//	mockgen -source=./release.go -destination ./v3portdrivermock/release.go -package v3portdrivermock
//

// Package v3portdrivermock is a generated GoMock package.
package v3portdrivermock

import (
	context "context"
	reflect "reflect"

	auditlogdto "github.com/kowell-ai/kowell-core/decision-agent/agent-backend/agent-factory/src/driveradapter/api/auditlogdto"
	releasereq "github.com/kowell-ai/kowell-core/decision-agent/agent-backend/agent-factory/src/driveradapter/api/rdto/release/releasereq"
	releaseresp "github.com/kowell-ai/kowell-core/decision-agent/agent-backend/agent-factory/src/driveradapter/api/rdto/release/releaseresp"
	gomock "go.uber.org/mock/gomock"
)

// MockIReleaseSvc is a mock of IReleaseSvc interface.
type MockIReleaseSvc struct {
	ctrl     *gomock.Controller
	recorder *MockIReleaseSvcMockRecorder
	isgomock struct{}
}

// MockIReleaseSvcMockRecorder is the mock recorder for MockIReleaseSvc.
type MockIReleaseSvcMockRecorder struct {
	mock *MockIReleaseSvc
}

// NewMockIReleaseSvc creates a new mock instance.
func NewMockIReleaseSvc(ctrl *gomock.Controller) *MockIReleaseSvc {
	mock := &MockIReleaseSvc{ctrl: ctrl}
	mock.recorder = &MockIReleaseSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReleaseSvc) EXPECT() *MockIReleaseSvcMockRecorder {
	return m.recorder
}

// GetPublishHistoryInfo mocks base method.
func (m *MockIReleaseSvc) GetPublishHistoryInfo(ctx context.Context, req any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishHistoryInfo", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishHistoryInfo indicates an expected call of GetPublishHistoryInfo.
func (mr *MockIReleaseSvcMockRecorder) GetPublishHistoryInfo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishHistoryInfo", reflect.TypeOf((*MockIReleaseSvc)(nil).GetPublishHistoryInfo), ctx, req)
}

// GetPublishHistoryList mocks base method.
func (m *MockIReleaseSvc) GetPublishHistoryList(ctx context.Context, agentID string) (releaseresp.HistoryListResp, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishHistoryList", ctx, agentID)
	ret0, _ := ret[0].(releaseresp.HistoryListResp)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPublishHistoryList indicates an expected call of GetPublishHistoryList.
func (mr *MockIReleaseSvcMockRecorder) GetPublishHistoryList(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishHistoryList", reflect.TypeOf((*MockIReleaseSvc)(nil).GetPublishHistoryList), ctx, agentID)
}

// GetPublishInfo mocks base method.
func (m *MockIReleaseSvc) GetPublishInfo(ctx context.Context, agentID string) (*releaseresp.PublishInfoResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishInfo", ctx, agentID)
	ret0, _ := ret[0].(*releaseresp.PublishInfoResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishInfo indicates an expected call of GetPublishInfo.
func (mr *MockIReleaseSvcMockRecorder) GetPublishInfo(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishInfo", reflect.TypeOf((*MockIReleaseSvc)(nil).GetPublishInfo), ctx, agentID)
}

// Publish mocks base method.
func (m *MockIReleaseSvc) Publish(ctx context.Context, req *releasereq.PublishReq) (*releaseresp.PublishUpsertResp, auditlogdto.AgentPublishAuditLogInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, req)
	ret0, _ := ret[0].(*releaseresp.PublishUpsertResp)
	ret1, _ := ret[1].(auditlogdto.AgentPublishAuditLogInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Publish indicates an expected call of Publish.
func (mr *MockIReleaseSvcMockRecorder) Publish(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockIReleaseSvc)(nil).Publish), ctx, req)
}

// UnPublish mocks base method.
func (m *MockIReleaseSvc) UnPublish(ctx context.Context, agentID string) (auditlogdto.AgentUnPublishAuditLogInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnPublish", ctx, agentID)
	ret0, _ := ret[0].(auditlogdto.AgentUnPublishAuditLogInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnPublish indicates an expected call of UnPublish.
func (mr *MockIReleaseSvcMockRecorder) UnPublish(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnPublish", reflect.TypeOf((*MockIReleaseSvc)(nil).UnPublish), ctx, agentID)
}

// UpdatePublishInfo mocks base method.
func (m *MockIReleaseSvc) UpdatePublishInfo(ctx context.Context, agentID string, req *releasereq.UpdatePublishInfoReq) (*releaseresp.PublishUpsertResp, auditlogdto.AgentModifyPublishAuditLogInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePublishInfo", ctx, agentID, req)
	ret0, _ := ret[0].(*releaseresp.PublishUpsertResp)
	ret1, _ := ret[1].(auditlogdto.AgentModifyPublishAuditLogInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdatePublishInfo indicates an expected call of UpdatePublishInfo.
func (mr *MockIReleaseSvcMockRecorder) UpdatePublishInfo(ctx, agentID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePublishInfo", reflect.TypeOf((*MockIReleaseSvc)(nil).UpdatePublishInfo), ctx, agentID, req)
}
