// Code generated by MockGen. DO NOT EDIT.
// Source: ./square.go
//
// Generated by this command:
//
//	mockgen -source=./square.go -destination ./v3portdrivermock/square.go -package v3portdrivermock
//

// Package v3portdrivermock is a generated GoMock package.
package v3portdrivermock

import (
	context "context"
	reflect "reflect"

	squarereq "github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/driveradapter/api/rdto/square/squarereq"
	squareresp "github.com/openbkn-ai/bkn-foundry/decision-agent/agent-backend/agent-factory/src/driveradapter/api/rdto/square/squareresp"
	gomock "go.uber.org/mock/gomock"
)

// MockISquareSvc is a mock of ISquareSvc interface.
type MockISquareSvc struct {
	ctrl     *gomock.Controller
	recorder *MockISquareSvcMockRecorder
	isgomock struct{}
}

// MockISquareSvcMockRecorder is the mock recorder for MockISquareSvc.
type MockISquareSvcMockRecorder struct {
	mock *MockISquareSvc
}

// NewMockISquareSvc creates a new mock instance.
func NewMockISquareSvc(ctrl *gomock.Controller) *MockISquareSvc {
	mock := &MockISquareSvc{ctrl: ctrl}
	mock.recorder = &MockISquareSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISquareSvc) EXPECT() *MockISquareSvcMockRecorder {
	return m.recorder
}

// CheckAndGetID mocks base method.
func (m *MockISquareSvc) CheckAndGetID(ctx context.Context, agentID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndGetID", ctx, agentID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAndGetID indicates an expected call of CheckAndGetID.
func (mr *MockISquareSvcMockRecorder) CheckAndGetID(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndGetID", reflect.TypeOf((*MockISquareSvc)(nil).CheckAndGetID), ctx, agentID)
}

// GetAgentInfo mocks base method.
func (m *MockISquareSvc) GetAgentInfo(ctx context.Context, agentInfoReq *squarereq.AgentInfoReq) (*squareresp.AgentMarketAgentInfoResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentInfo", ctx, agentInfoReq)
	ret0, _ := ret[0].(*squareresp.AgentMarketAgentInfoResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentInfo indicates an expected call of GetAgentInfo.
func (mr *MockISquareSvcMockRecorder) GetAgentInfo(ctx, agentInfoReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentInfo", reflect.TypeOf((*MockISquareSvc)(nil).GetAgentInfo), ctx, agentInfoReq)
}

// GetAgentInfoByIDOrKey mocks base method.
func (m *MockISquareSvc) GetAgentInfoByIDOrKey(ctx context.Context, agentInfoReq *squarereq.AgentInfoReq) (*squareresp.AgentMarketAgentInfoResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentInfoByIDOrKey", ctx, agentInfoReq)
	ret0, _ := ret[0].(*squareresp.AgentMarketAgentInfoResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentInfoByIDOrKey indicates an expected call of GetAgentInfoByIDOrKey.
func (mr *MockISquareSvcMockRecorder) GetAgentInfoByIDOrKey(ctx, agentInfoReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentInfoByIDOrKey", reflect.TypeOf((*MockISquareSvc)(nil).GetAgentInfoByIDOrKey), ctx, agentInfoReq)
}

// GetRecentAgentList mocks base method.
func (m *MockISquareSvc) GetRecentAgentList(ctx context.Context, req squarereq.AgentSquareRecentAgentReq) (squareresp.RecentListAgentResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentAgentList", ctx, req)
	ret0, _ := ret[0].(squareresp.RecentListAgentResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentAgentList indicates an expected call of GetRecentAgentList.
func (mr *MockISquareSvcMockRecorder) GetRecentAgentList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentAgentList", reflect.TypeOf((*MockISquareSvc)(nil).GetRecentAgentList), ctx, req)
}

// IsAgentExists mocks base method.
func (m *MockISquareSvc) IsAgentExists(ctx context.Context, agentID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAgentExists", ctx, agentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAgentExists indicates an expected call of IsAgentExists.
func (mr *MockISquareSvcMockRecorder) IsAgentExists(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAgentExists", reflect.TypeOf((*MockISquareSvc)(nil).IsAgentExists), ctx, agentID)
}
