// Copyright openbkn.ai
// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

package driveradapters

import (
	"context"
	"net/http"

	"github.com/openbkn-ai/bkn-foundry/comm-go/rest"

	berrors "bkn-backend/errors"
	"bkn-backend/interfaces"
)

func rejectClientSpecifiedChildIDs(ctx context.Context, mode string, ids ...string) *rest.HTTPError {
	if mode != interfaces.ImportMode_Normal {
		return nil
	}
	for _, id := range ids {
		if id != "" {
			return rest.NewHTTPError(ctx, http.StatusBadRequest, berrors.BknBackend_InvalidParameter_ID).
				WithErrorDetails("child resource ID must be generated by the server")
		}
	}
	return nil
}

func rejectClientSpecifiedKNChildIDs(ctx context.Context, mode string, kn *interfaces.KN) *rest.HTTPError {
	for _, conceptGroup := range kn.ConceptGroups {
		if conceptGroup == nil {
			continue
		}
		if httpErr := rejectClientSpecifiedChildIDs(ctx, mode, conceptGroup.CGID); httpErr != nil {
			return httpErr
		}
		for _, objectType := range conceptGroup.ObjectTypes {
			if objectType == nil {
				continue
			}
			if httpErr := rejectClientSpecifiedChildIDs(ctx, mode, objectType.OTID); httpErr != nil {
				return httpErr
			}
		}
		for _, relationType := range conceptGroup.RelationTypes {
			if relationType == nil {
				continue
			}
			if httpErr := rejectClientSpecifiedChildIDs(ctx, mode, relationType.RTID); httpErr != nil {
				return httpErr
			}
		}
		for _, actionType := range conceptGroup.ActionTypes {
			if actionType == nil {
				continue
			}
			if httpErr := rejectClientSpecifiedChildIDs(ctx, mode, actionType.ATID); httpErr != nil {
				return httpErr
			}
		}
	}
	for _, objectType := range kn.ObjectTypes {
		if objectType == nil {
			continue
		}
		if httpErr := rejectClientSpecifiedChildIDs(ctx, mode, objectType.OTID); httpErr != nil {
			return httpErr
		}
	}
	for _, relationType := range kn.RelationTypes {
		if relationType == nil {
			continue
		}
		if httpErr := rejectClientSpecifiedChildIDs(ctx, mode, relationType.RTID); httpErr != nil {
			return httpErr
		}
	}
	for _, actionType := range kn.ActionTypes {
		if actionType == nil {
			continue
		}
		if httpErr := rejectClientSpecifiedChildIDs(ctx, mode, actionType.ATID); httpErr != nil {
			return httpErr
		}
	}
	for _, metric := range kn.Metrics {
		if metric == nil {
			continue
		}
		if httpErr := rejectClientSpecifiedChildIDs(ctx, mode, metric.ID); httpErr != nil {
			return httpErr
		}
	}
	for _, riskType := range kn.RiskTypes {
		if riskType == nil {
			continue
		}
		if httpErr := rejectClientSpecifiedChildIDs(ctx, mode, riskType.RTID); httpErr != nil {
			return httpErr
		}
	}
	return nil
}
