// Copyright openbkn.ai
// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0. See the LICENSE file in the project root for details.

package local_index

import (
	"fmt"
	"strings"

	"vega-backend/interfaces"
)

// buildFieldMappings converts a Resource schema into the physical mapping used by OpenSearch.
func buildFieldMappings(schemaDefinition []*interfaces.Property) (map[string]any, error) {
	properties := map[string]any{}
	declaredFields := make(map[string]struct{}, len(schemaDefinition))
	for _, prop := range schemaDefinition {
		if prop != nil {
			declaredFields[prop.Name] = struct{}{}
		}
	}

	for _, prop := range schemaDefinition {
		if prop == nil {
			continue
		}
		fieldType := prop.Type
		switch prop.Type {
		case interfaces.DataType_Integer:
			fieldType = "long"
		case interfaces.DataType_UnsignedInteger:
			fieldType = "unsigned_long"
		case interfaces.DataType_Float:
			fieldType = "double"
		case interfaces.DataType_Decimal:
			fieldType = "scaled_float"
		case interfaces.DataType_String:
			fieldType = "keyword"
		case interfaces.DataType_Datetime, interfaces.DataType_Timestamp:
			fieldType = "date"
		case interfaces.DataType_Time:
			fieldType = "keyword"
		case interfaces.DataType_Json:
			fieldType = "object"
		case interfaces.DataType_Vector:
			fieldType = "knn_vector"
		case interfaces.DataType_Point:
			fieldType = "geo_point"
		case interfaces.DataType_Shape:
			fieldType = "geo_shape"
		case interfaces.DataType_Other:
			return nil, fmt.Errorf("unsupported schema field %q: type %s (original_type: %s)", prop.Name, prop.Type, prop.OriginalType)
		}

		fieldProps := map[string]any{"type": fieldType}
		if prop.Type == interfaces.DataType_Decimal {
			fieldProps["scaling_factor"] = 1000000000000000000.0
		}

		for _, feature := range prop.Features {
			if feature.FeatureType == interfaces.PropertyFeatureType_Fulltext {
				applyFulltextFeature(fieldProps, prop, feature)
				continue
			}
			switch feature.FeatureType {
			case interfaces.PropertyFeatureType_Keyword:
				applyKeywordFeature(fieldProps, prop, feature)
			case interfaces.PropertyFeatureType_Vector:
				if feature.Config != nil && prop.Type == interfaces.DataType_Vector {
					if dimension, exists := feature.Config["dimension"]; exists {
						fieldProps["dimension"] = dimension
					}
				}
			default:
				if feature.Config != nil {
					return nil, fmt.Errorf("unsupported feature type: %s", feature.FeatureType)
				}
			}
		}

		if prop.Type == interfaces.DataType_Vector {
			fieldProps["method"] = defaultVectorMethod()
		}
		properties[prop.Name] = fieldProps
	}

	for _, prop := range schemaDefinition {
		if prop == nil || (prop.Type != interfaces.DataType_String && prop.Type != interfaces.DataType_Text) {
			continue
		}
		for _, feature := range prop.Features {
			if feature.FeatureType != interfaces.PropertyFeatureType_Vector || feature.RefProperty != "" {
				continue
			}
			generatedName := VectorFieldName(prop.Name)
			if _, exists := declaredFields[generatedName]; exists {
				return nil, fmt.Errorf("generated vector field %q conflicts with declared field", generatedName)
			}
			dimension, ok := feature.Config["dimension"]
			if !ok {
				return nil, fmt.Errorf("vector feature for field %q has no resolved dimension", prop.Name)
			}
			fieldMapping := map[string]any{
				"type":      "knn_vector",
				"dimension": dimension,
			}
			for key, value := range feature.Config {
				if key != "embedding_model" && key != "method" {
					fieldMapping[key] = value
				}
			}
			fieldMapping["method"] = defaultVectorMethod()
			properties[generatedName] = fieldMapping
		}
	}

	return properties, nil
}

// VectorFieldName returns the physical vector field generated by the active local index manager.
func VectorFieldName(field string) string {
	return field + interfaces.LocalIndexVectorFieldSuffix
}

func applyFulltextFeature(fieldProps map[string]any, property *interfaces.Property, feature interfaces.PropertyFeature) {
	switch property.Type {
	case interfaces.DataType_String:
		fieldName := strings.TrimSpace(feature.FeatureName)
		if fieldName == "" {
			fieldName = interfaces.LocalIndexFulltextSubfieldName
		} else {
			fieldName = strings.TrimPrefix(fieldName, property.Name+".")
		}
		subfield := map[string]any{"type": "text"}
		for key, value := range feature.Config {
			subfield[key] = value
		}
		fields, ok := fieldProps["fields"].(map[string]any)
		if !ok {
			fields = map[string]any{}
			fieldProps["fields"] = fields
		}
		fields[fieldName] = subfield
	case interfaces.DataType_Text:
		for key, value := range feature.Config {
			fieldProps[key] = value
		}
	}
}

func applyKeywordFeature(fieldProps map[string]any, property *interfaces.Property, feature interfaces.PropertyFeature) {
	if property.Type != interfaces.DataType_Text {
		for key, value := range feature.Config {
			fieldProps[key] = value
		}
		return
	}
	fieldName := strings.TrimSpace(feature.FeatureName)
	if fieldName == "" {
		fieldName = interfaces.LocalIndexKeywordSubfieldName
	} else {
		fieldName = strings.TrimPrefix(fieldName, property.Name+".")
	}
	fields, ok := fieldProps["fields"].(map[string]any)
	if !ok {
		fields = map[string]any{}
		fieldProps["fields"] = fields
	}
	subfield := map[string]any{"type": "keyword"}
	for key, value := range feature.Config {
		subfield[key] = value
	}
	fields[fieldName] = subfield
}

func defaultVectorMethod() map[string]any {
	return map[string]any{
		"name":       "hnsw",
		"engine":     "lucene",
		"parameters": map[string]any{"ef_construction": 256},
	}
}
