db:
  host: "127.0.0.1"
  port: 3306
  user_name: "root"
  password: "<REPLACE_ME>"
  db_name: "dip_data_operator_hub"
  charset: "utf8mb4"
redis:
  connectInfo:
    username: ""
    password: ""
    host: "127.0.0.1"
    port: 6379
    masterHost: "127.0.0.1"
    masterPort: 6379
    slaveHost: ""
    slavePort: 6379
    sentinelHost: ""
    sentinelPort: 26379
    sentinelUsername: ""
    sentinelPassword: ""
    masterGroupName: "mymaster"
