project:
  language: zh-CN
  host: "0.0.0.0"
  port: 9000
  logger_level: 0
  name:
  pod_id: "POD_ID"
  machine_id: ""
  debug: false
operator:
  import_file_size_limit: 100000000
  import_operator_max_count: 10
  operator_description_length_limit: 500
mcp:
  conn_timeout: 10 # 单位:秒
  max_instances: 200
  instance_ttl: 1800 # 单位:秒
  cleanup_interval: 60 # 单位:秒
category:
  init_switch: true # 是否初始化算子分类

proxy_module:
  default_timeout: 30 # 单位:秒
  max_timeout: 120 # 单位:秒
  min_timeout: 1 # 单位:秒
  max_clients: 100
  client_lifetime: 300 # 单位:秒

oauth:
  # 对应hydra服务
  public_host: "hydra-public.kweaver"
  public_port: 4444
  public_protocol: "http"
  admin_host: "hydra-admin.kweaver"
  admin_port: 4445
  admin_protocol: "http"
  admin_prefix: "/admin"
user_management:
  private_host: "user-management-private.kweaver"
  private_port: 30980
  private_protocol: "http"
authorization:
  private_host: "authorization-private.kweaver"
  private_port: 30920
  private_protocol: "http"
agent-operator-app:
  private_host: "agent-operator-app.kweaver"
  private_port: 9000
  private_protocol: "http"
mf-model-api:
  private_host: "mf-model-api.kweaver"
  private_port: 9898
  private_protocol: "http"
mf-model-manager:
  private_host: "mf-model-manager.kweaver"
  private_port: 9898
  private_protocol: "http"
db:
  conn_timeout: 30
  read_timeout: 30
  write_timeout: 30
  max_open_conns: 30
  system_id: ""
business-system-service:
  private_host: "business-system-service.kweaver"
  private_port: 80
  private_protocol: "http"
sandbox-control-plane:
  private_host: "sandbox-control-plane.kweaver"
  private_port: 8000
  private_protocol: "http"
  template_id: "" # 模板ID
  session_resources:
    cpu: 1
    memory: 512Mi
    disk: 1Gi
    timeout: 3600 # 单位:秒
  max_sessions: 3
  active_sessions: 1
  max_concurrent_tasks: 100
vega-backend:
  private_host: "vega-backend-svc.kweaver"
  private_port: 13014
  private_protocol: "http"

redis:
  connectType: "sentinel"
  enableSSL: false
  secretName: ""
  caName: ""
  certName: ""
  keyName: ""
  poolSize: 10

# ai辅助相关配置
ai_generation_config:
  # python代码生成系统提示词ID
  python_function_generator_prompt_id: "" # 如果为空或为找到，则使用默认提示词
  metadata_param_generator_prompt_id: "" # 如果为空或为找到，则使用默认提示词
  llm:
    model: ""
    max_tokens: 1024
    temperature: 0.1
    top_k: 20
    top_p: 0.1
    frequency_penalty: 0.1
    presence_penalty: 0.1

oss-gateway-backend:
  private_host: "oss-gateway-backend.kweaver"
  private_port: 8080
  private_protocol: "http"
  storage_id: ""
  internal_request: false
  expires: 3600
