apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    module: {{ .Values.moduleName }}
spec:
  {{- if .Values.service.enableDualStack }}
  ipFamilies:
    - IPv6
    - IPv4
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    app: {{ .Release.Name }}
    module: {{ .Values.moduleName }}
  type: {{ .Values.service.type }}
