// Copyright openbkn.ai
// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

package resource_data

import (
	"context"
	"fmt"

	"vega-backend/interfaces"
	"vega-backend/logics/filter_condition"
)

// resolveVectorConditions converts the query text in the vector retrieval conditions into vectors in place and replaces the fields with
// The field in the index where the actual vector is stored.
//
// The caller only says, "Perform vector retrieval on stadium_name, and the query term is this sentence." In which field does the vector fall?
// Which model to use for calculation is the implementation detail of the local index: the fields are generated by the construction task, and the model is determined when the index is built.
// This is consistent with the processing method of full-text search - over there, vega also parses the fields into word segmentation subfields by itself
// (See fulltextFieldName of opensearch_condi.go), the caller does not need to know.
//
// When the condition is already a vector (the value is not a string), it is released as is: the old path of the data view has calculated the vector by itself.
func (rds *resourceDataService) resolveVectorConditions(ctx context.Context,
	resource *interfaces.Resource, cfg *interfaces.FilterCondCfg) error {

	if cfg == nil {
		return nil
	}

	for _, sub := range cfg.SubConds {
		if err := rds.resolveVectorConditions(ctx, resource, sub); err != nil {
			return err
		}
	}

	if cfg.Operation != filter_condition.OperationKnnVector {
		return nil
	}
	text, ok := cfg.Value.(string)
	if !ok {
		return nil
	}

	field, err := vectorFieldFor(resource, cfg.Name)
	if err != nil {
		return err
	}
	modelID, err := rds.embeddingModelForIndex(ctx, resource, cfg.Name)
	if err != nil {
		return err
	}
	model, err := rds.mfs.GetModelByID(ctx, modelID)
	if err != nil {
		return fmt.Errorf("condition [knn_vector] load model %q failed: %w", modelID, err)
	}
	if model == nil || model.ModelID == "" {
		return fmt.Errorf("condition [knn_vector] model %q is unavailable", modelID)
	}

	vectors, err := rds.mfs.GetVector(ctx, model, []string{text})
	if err != nil {
		return fmt.Errorf("condition [knn_vector] vectorize %q with model %q failed: %w", text, modelID, err)
	}
	if len(vectors) == 0 || vectors[0] == nil {
		return fmt.Errorf("condition [knn_vector] model %q returned no vector for %q", modelID, text)
	}

	cfg.Name = field
	cfg.Value = vectors[0].Vector
	return nil
}

// vectorFieldFor finds the physical vector field for a source field.
//
// When the field itself is a vector type (the data view path), use it directly. Otherwise, a vector must be declared on the source field
// The feature, vector, is on the field generated by the build task. If not found, an error will be reported - no downgrading here: quietly search the vector
// If any other operator is used, the caller will get a result that is completely different in semantics but seems successful.
func vectorFieldFor(resource *interfaces.Resource, name string) (string, error) {
	if resource == nil {
		return "", fmt.Errorf("condition [knn_vector] left field '%s' has no resource context", name)
	}
	if resource.LocalIndexName == "" {
		return "", fmt.Errorf("condition [knn_vector] resource '%s' has no local index; build one before vector search", resource.Name)
	}

	for _, prop := range resource.SchemaDefinition {
		if prop == nil {
			continue
		}
		if prop.Name == name && prop.Type == interfaces.DataType_Vector {
			return name, nil
		}
		for _, feature := range prop.Features {
			if feature.FeatureType != interfaces.PropertyFeatureType_Vector {
				continue
			}
			source := prop.Name
			if feature.RefProperty != "" {
				source = feature.RefProperty
			}
			if source == name {
				return interfaces.LocalIndexVectorFieldName(source), nil
			}
		}
	}

	return "", fmt.Errorf("condition [knn_vector] field '%s' has no vector index on resource '%s'", name, resource.Name)
}

// The embeddingModelForIndex takes the id of the embedding model used to create this index.
//
// The authoritative source is the snapshot of the build task that produced this index, not what is currently written on the resource: Has the feature configuration of the resource been changed
// However, when the index is not reconstructed, the two will be inconsistent, and the vector calculated by the wrong model cannot be compared with that in the index. Saved in the snapshot
// It is already the parsed model id, which is exactly the same as the one used to write the vector during the construction.
func (rds *resourceDataService) embeddingModelForIndex(ctx context.Context,
	resource *interfaces.Resource, field string) (string, error) {

	taskID := interfaces.BuildTaskIDFromIndexName(resource.LocalIndexName)
	if taskID == "" {
		return "", fmt.Errorf("condition [knn_vector] cannot tell which build task produced index '%s'", resource.LocalIndexName)
	}

	task, err := rds.bta.GetByID(ctx, taskID)
	if err != nil {
		return "", fmt.Errorf("condition [knn_vector] load build task %s failed: %w", taskID, err)
	}
	if task == nil || task.IndexConfig == nil {
		return "", fmt.Errorf("condition [knn_vector] build task %s has no index config", taskID)
	}
	feature, ok := task.IndexConfig.Features[field]
	if !ok || feature.Vector == nil || feature.Vector.ModelID == "" {
		return "", fmt.Errorf("condition [knn_vector] field '%s' was not vectorized by build task %s", field, taskID)
	}
	return feature.Vector.ModelID, nil
}
