// Copyright openbkn.ai
// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

package resource_data

import (
	"context"
	"fmt"
	"strings"

	"vega-backend/interfaces"
	"vega-backend/logics/filter_condition"
)

// resolveVectorConditions converts the query text in the vector retrieval conditions into vectors in place and replaces the fields with
// The field in the index where the actual vector is stored.
//
// The caller only says, "Perform vector retrieval on stadium_name, and the query term is this sentence." In which field does the vector fall?
// Which model to use for calculation is the implementation detail of the local index: the fields are generated by the construction task, and the model is determined when the index is built.
// This is consistent with the processing method of full-text search - over there, vega also parses the fields into word segmentation subfields by itself
// (See fulltextFieldName of opensearch_condi.go), the caller does not need to know.
//
// When the condition is already a vector (the value is not a string), it is released as is: the old path of the data view has calculated the vector by itself.
func (rds *resourceDataService) resolveVectorConditions(ctx context.Context,
	resource *interfaces.Resource, cfg *interfaces.FilterCondCfg) error {

	if cfg == nil {
		return nil
	}

	for _, sub := range cfg.SubConds {
		if err := rds.resolveVectorConditions(ctx, resource, sub); err != nil {
			return err
		}
	}

	if cfg.Operation != filter_condition.OperationKnnVector {
		return nil
	}
	text, ok := cfg.Value.(string)
	if !ok {
		return nil
	}

	field, err := vectorFieldFor(resource, cfg.Name)
	if err != nil {
		return err
	}
	modelID, err := rds.embeddingModelForIndex(ctx, resource, cfg.Name)
	if err != nil {
		return err
	}
	model, err := rds.mfs.GetModelByID(ctx, modelID)
	if err != nil {
		return fmt.Errorf("condition [knn_vector] load model %q failed: %w", modelID, err)
	}
	if model == nil || model.ModelID == "" {
		return fmt.Errorf("condition [knn_vector] model %q is unavailable", modelID)
	}

	vectors, err := rds.mfs.GetVector(ctx, model, []string{text})
	if err != nil {
		return fmt.Errorf("condition [knn_vector] vectorize %q with model %q failed: %w", text, modelID, err)
	}
	if len(vectors) == 0 || vectors[0] == nil {
		return fmt.Errorf("condition [knn_vector] model %q returned no vector for %q", modelID, text)
	}

	cfg.Name = field
	cfg.Value = vectors[0].Vector
	return nil
}

// vectorFieldFor finds the physical vector field for a source field.
//
// When the field itself is a vector type (the data view path), use it directly. Otherwise, a vector must be declared on the source field
// The feature, vector, is on the field generated by the build task. If not found, an error will be reported - no downgrading here: quietly search the vector
// If any other operator is used, the caller will get a result that is completely different in semantics but seems successful.
func vectorFieldFor(resource *interfaces.Resource, name string) (string, error) {
	if resource == nil {
		return "", fmt.Errorf("condition [knn_vector] left field '%s' has no resource context", name)
	}
	if !interfaces.HasAvailableLocalIndex(resource) {
		return "", fmt.Errorf("condition [knn_vector] resource '%s' has no local index; build one before vector search", resource.Name)
	}

	for _, prop := range resource.SchemaDefinition {
		if prop == nil {
			continue
		}
		if prop.Name == name && prop.Type == interfaces.DataType_Vector {
			return name, nil
		}
		for _, feature := range prop.Features {
			if feature.FeatureType != interfaces.PropertyFeatureType_Vector {
				continue
			}
			source := prop.Name
			if feature.RefProperty != "" {
				source = feature.RefProperty
			}
			if source == name {
				return interfaces.LocalIndexVectorFieldName(source), nil
			}
		}
	}

	return "", fmt.Errorf("condition [knn_vector] field '%s' has no vector index on resource '%s'", name, resource.Name)
}

// embeddingModelForIndex resolves the model from the current Resource index
// configuration. An available Resource guarantees this configuration matches
// its managed index, so queries never depend on a historical BuildTask.
func (rds *resourceDataService) embeddingModelForIndex(ctx context.Context,
	resource *interfaces.Resource, field string) (string, error) {
	if resource == nil || resource.IndexConfig == nil {
		return "", fmt.Errorf("condition [knn_vector] resource has no index configuration")
	}
	for _, prop := range resource.SchemaDefinition {
		if prop == nil {
			continue
		}
		for _, feature := range prop.Features {
			if feature.FeatureType != interfaces.PropertyFeatureType_Vector {
				continue
			}
			source := prop.Name
			if feature.RefProperty != "" {
				source = feature.RefProperty
			}
			if source != field {
				continue
			}
			if modelID, ok := feature.Config["embedding_model"].(string); ok && strings.TrimSpace(modelID) != "" {
				return strings.TrimSpace(modelID), nil
			}
			if modelID := strings.TrimSpace(resource.IndexConfig.DefaultEmbeddingModel); modelID != "" {
				return modelID, nil
			}
			return "", fmt.Errorf("condition [knn_vector] field '%s' has no embedding model", field)
		}
	}
	return "", fmt.Errorf("condition [knn_vector] field '%s' has no vector index on resource '%s'", field, resource.Name)
}
