{{/*
Copyright (c) 2026 OpenBKN
SPDX-License-Identifier: LicenseRef-OpenBKN
Licensed under the OpenBKN License, a modified Apache 2.0 with Additional
Conditions. See LICENSE-OPENBKN.txt in the repository root for the full text.
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-observability.fullname" . | trunc 54 | trimSuffix "-" }}-internal
  labels:
    {{- include "agent-observability.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "agent-observability.selectorLabels" . | nindent 4 }}
  ports:
    - name: lifecycle
      port: 8081
      targetPort: internal-http
      protocol: TCP
