// Package parsers function metadata parsing.
// @file py_func_schema_reverse.go
// @description: Reverse parameter definitions from the OpenAPI specification of the function tool.
package parsers

import (
	"github.com/getkin/kin-openapi/openapi3"

	"github.com/openbkn-ai/bkn-foundry/adp/execution-factory/operator-integration/server/interfaces"
	"github.com/openbkn-ai/bkn-foundry/adp/execution-factory/operator-integration/server/utils"
)

// The parameter definition of the function tool is expanded into the OpenAPI specification when it is stored, and is stored in a single column f_api_spec.
// When reading back, the caller needs the original ParameterDef shape (including required and nested sub_parameters),
// So here is a reverse analysis. Specifications are generated by createRequestBody / createResponses,
// The structure is fixed and you don't have to deal with arbitrary OpenAPI documentation.

const (
	applicationJSON = "application/json"
	statusOK        = "200"
	resultProperty  = "result"
	itemsProperty   = "items"
)

// FunctionParamsFromAPISpec restores the input and output parameter definitions from the API specifications of the function tool.
// When the specifications are missing or the structure does not match, an empty slice is returned, and the caller handles it as "no parameters".
func FunctionParamsFromAPISpec(apiSpec string) (inputs, outputs []*interfaces.ParameterDef) {
	if apiSpec == "" {
		return nil, nil
	}
	spec := utils.JSONToObject[interfaces.APISpec](apiSpec)
	return inputsFromRequestBody(spec.RequestBody), outputsFromResponses(spec.Responses)
}

// inputsFromRequestBody input parameters come from the properties of the request body schema.
func inputsFromRequestBody(requestBody *interfaces.RequestBody) []*interfaces.ParameterDef {
	if requestBody == nil {
		return nil
	}
	content, ok := requestBody.Content[applicationJSON]
	if !ok || content == nil || content.Schema == nil {
		return nil
	}
	return paramsFromSchema(content.Schema.Value)
}

// The outputsFromResponses output parameter is embedded under the result attribute of the 200 response.
func outputsFromResponses(responses []*interfaces.Response) []*interfaces.ParameterDef {
	var response *interfaces.Response
	for _, item := range responses {
		if item != nil && item.StatusCode == statusOK {
			response = item
			break
		}
	}
	if response == nil {
		return nil
	}
	content, ok := response.Content[applicationJSON]
	if !ok || content == nil || content.Schema == nil {
		return nil
	}
	root := content.Schema.Value
	if root == nil || root.Properties == nil {
		return nil
	}
	result, ok := root.Properties[resultProperty]
	if !ok || result == nil {
		return nil
	}
	return paramsFromSchema(result.Value)
}

// paramsFromSchema restores each attribute of an object schema into a parameter definition.
func paramsFromSchema(schema *openapi3.Schema) []*interfaces.ParameterDef {
	if schema == nil || len(schema.Properties) == 0 {
		return nil
	}
	required := make(map[string]bool, len(schema.Required))
	for _, name := range schema.Required {
		required[name] = true
	}
	params := make([]*interfaces.ParameterDef, 0, len(schema.Properties))
	for name, ref := range schema.Properties {
		if ref == nil {
			continue
		}
		params = append(params, paramFromSchema(name, ref.Value, required[name]))
	}
	sortParamsByName(params)
	return params
}

// paramFromSchema restores a single parameter and recursively expands nested structures by type.
func paramFromSchema(name string, schema *openapi3.Schema, required bool) *interfaces.ParameterDef {
	param := &interfaces.ParameterDef{Name: name, Required: required}
	if schema == nil {
		return param
	}
	param.Type = mapOpenAPIToType(schema.Type)
	param.Description = schema.Description
	param.Default = schema.Default
	param.Enum = schema.Enum
	param.Example = schema.Example

	switch param.Type {
	case interfaces.ParameterTypeObject:
		// The attributes of object are sub-parameters.
		param.SubParameters = paramsFromSchema(schema)
	case interfaces.ParameterTypeArray:
		// The element structure of array is stored in items, and the convention is to reduce it to a single sub-parameter named items.
		if schema.Items != nil && schema.Items.Value != nil {
			param.SubParameters = []*interfaces.ParameterDef{
				paramFromSchema(itemsProperty, schema.Items.Value, true),
			}
		}
	}
	return param
}

// mapOpenAPIToType is the inverse mapping of mapTypeToOpenAPI.
// OpenAPI's integer and number are unified to number in the parameter definition.
func mapOpenAPIToType(types *openapi3.Types) interfaces.ParameterType {
	if types == nil || len(*types) == 0 {
		return interfaces.ParameterTypeString
	}
	switch (*types)[0] {
	case openapi3.TypeInteger, openapi3.TypeNumber:
		return interfaces.ParameterTypeNumber
	case openapi3.TypeBoolean:
		return interfaces.ParameterTypeBoolean
	case openapi3.TypeArray:
		return interfaces.ParameterTypeArray
	case openapi3.TypeObject:
		return interfaces.ParameterTypeObject
	default:
		return interfaces.ParameterTypeString
	}
}

// sortParamsByName makes the order stable. The properties of the schema are map, and the traversal order is random.
// If not sorted, the order of parameters returned by the same tool will be different every time it is read.
func sortParamsByName(params []*interfaces.ParameterDef) {
	for i := 1; i < len(params); i++ {
		for j := i; j > 0 && params[j].Name < params[j-1].Name; j-- {
			params[j], params[j-1] = params[j-1], params[j]
		}
	}
}
