// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/permission_service.go
//
// Generated by this command:
//
//	mockgen -source interfaces/permission_service.go -destination interfaces/mock/mock_permission_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-query/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPermissionAccess is a mock of PermissionAccess interface.
type MockPermissionAccess struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionAccessMockRecorder
	isgomock struct{}
}

// MockPermissionAccessMockRecorder is the mock recorder for MockPermissionAccess.
type MockPermissionAccessMockRecorder struct {
	mock *MockPermissionAccess
}

// NewMockPermissionAccess creates a new mock instance.
func NewMockPermissionAccess(ctrl *gomock.Controller) *MockPermissionAccess {
	mock := &MockPermissionAccess{ctrl: ctrl}
	mock.recorder = &MockPermissionAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionAccess) EXPECT() *MockPermissionAccessMockRecorder {
	return m.recorder
}

// FilterResources mocks base method.
func (m *MockPermissionAccess) FilterResources(ctx context.Context, request interfaces.PermissionFilterRequest) (interfaces.PermissionFilterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterResources", ctx, request)
	ret0, _ := ret[0].(interfaces.PermissionFilterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterResources indicates an expected call of FilterResources.
func (mr *MockPermissionAccessMockRecorder) FilterResources(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterResources", reflect.TypeOf((*MockPermissionAccess)(nil).FilterResources), ctx, request)
}

// CheckPermissions mocks base method.
func (m *MockPermissionAccess) CheckPermissions(ctx context.Context, request interfaces.PermissionChecksRequest) (interfaces.PermissionChecksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermissions", ctx, request)
	ret0, _ := ret[0].(interfaces.PermissionChecksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermissions indicates an expected call of CheckPermissions.
func (mr *MockPermissionAccessMockRecorder) CheckPermissions(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermissions", reflect.TypeOf((*MockPermissionAccess)(nil).CheckPermissions), ctx, request)
}

// ResolvePropertyLevels mocks base method.
func (m *MockPermissionAccess) ResolvePropertyLevels(ctx context.Context, request interfaces.PropertyLevelsRequest) (interfaces.PropertyLevelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePropertyLevels", ctx, request)
	ret0, _ := ret[0].(interfaces.PropertyLevelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePropertyLevels indicates an expected call of ResolvePropertyLevels.
func (mr *MockPermissionAccessMockRecorder) ResolvePropertyLevels(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePropertyLevels", reflect.TypeOf((*MockPermissionAccess)(nil).ResolvePropertyLevels), ctx, request)
}

// ResolveRowFilters mocks base method.
func (m *MockPermissionAccess) ResolveRowFilters(ctx context.Context, request interfaces.RowFiltersRequest) (interfaces.RowFiltersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveRowFilters", ctx, request)
	ret0, _ := ret[0].(interfaces.RowFiltersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveRowFilters indicates an expected call of ResolveRowFilters.
func (mr *MockPermissionAccessMockRecorder) ResolveRowFilters(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveRowFilters", reflect.TypeOf((*MockPermissionAccess)(nil).ResolveRowFilters), ctx, request)
}

// MockPermissionService is a mock of PermissionService interface.
type MockPermissionService struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionServiceMockRecorder
	isgomock struct{}
}

// MockPermissionServiceMockRecorder is the mock recorder for MockPermissionService.
type MockPermissionServiceMockRecorder struct {
	mock *MockPermissionService
}

// NewMockPermissionService creates a new mock instance.
func NewMockPermissionService(ctrl *gomock.Controller) *MockPermissionService {
	mock := &MockPermissionService{ctrl: ctrl}
	mock.recorder = &MockPermissionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionService) EXPECT() *MockPermissionServiceMockRecorder {
	return m.recorder
}

// FilterQueryData mocks base method.
func (m *MockPermissionService) FilterQueryData(ctx context.Context, resources []interfaces.PermissionResource) ([]interfaces.PermissionResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterQueryData", ctx, resources)
	ret0, _ := ret[0].([]interfaces.PermissionResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterQueryData indicates an expected call of FilterQueryData.
func (mr *MockPermissionServiceMockRecorder) FilterQueryData(ctx, resources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterQueryData", reflect.TypeOf((*MockPermissionService)(nil).FilterQueryData), ctx, resources)
}

// RequirePermissions mocks base method.
func (m *MockPermissionService) RequirePermissions(ctx context.Context, requirements []interfaces.PermissionRequirement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequirePermissions", ctx, requirements)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequirePermissions indicates an expected call of RequirePermissions.
func (mr *MockPermissionServiceMockRecorder) RequirePermissions(ctx, requirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequirePermissions", reflect.TypeOf((*MockPermissionService)(nil).RequirePermissions), ctx, requirements)
}

// RequireQueryData mocks base method.
func (m *MockPermissionService) RequireQueryData(ctx context.Context, resources []interfaces.PermissionResource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireQueryData", ctx, resources)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireQueryData indicates an expected call of RequireQueryData.
func (mr *MockPermissionServiceMockRecorder) RequireQueryData(ctx, resources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireQueryData", reflect.TypeOf((*MockPermissionService)(nil).RequireQueryData), ctx, resources)
}

// MockPropertyAccessService is a mock of PropertyAccessService interface.
type MockPropertyAccessService struct {
	ctrl     *gomock.Controller
	recorder *MockPropertyAccessServiceMockRecorder
	isgomock struct{}
}

// MockPropertyAccessServiceMockRecorder is the mock recorder for MockPropertyAccessService.
type MockPropertyAccessServiceMockRecorder struct {
	mock *MockPropertyAccessService
}

// NewMockPropertyAccessService creates a new mock instance.
func NewMockPropertyAccessService(ctrl *gomock.Controller) *MockPropertyAccessService {
	mock := &MockPropertyAccessService{ctrl: ctrl}
	mock.recorder = &MockPropertyAccessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPropertyAccessService) EXPECT() *MockPropertyAccessServiceMockRecorder {
	return m.recorder
}

// ResolvePropertyLevels mocks base method.
func (m *MockPropertyAccessService) ResolvePropertyLevels(ctx context.Context, items []interfaces.PropertyLevelsRequestItem) ([]interfaces.PropertyLevelsDecisionEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePropertyLevels", ctx, items)
	ret0, _ := ret[0].([]interfaces.PropertyLevelsDecisionEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePropertyLevels indicates an expected call of ResolvePropertyLevels.
func (mr *MockPropertyAccessServiceMockRecorder) ResolvePropertyLevels(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePropertyLevels", reflect.TypeOf((*MockPropertyAccessService)(nil).ResolvePropertyLevels), ctx, items)
}

// MockRowFilterService is a mock of RowFilterService interface.
type MockRowFilterService struct {
	ctrl     *gomock.Controller
	recorder *MockRowFilterServiceMockRecorder
	isgomock struct{}
}

type MockRowFilterServiceMockRecorder struct{ mock *MockRowFilterService }

func NewMockRowFilterService(ctrl *gomock.Controller) *MockRowFilterService {
	mock := &MockRowFilterService{ctrl: ctrl}
	mock.recorder = &MockRowFilterServiceMockRecorder{mock}
	return mock
}

func (m *MockRowFilterService) EXPECT() *MockRowFilterServiceMockRecorder { return m.recorder }

func (m *MockRowFilterService) ResolveRowFilters(ctx context.Context, refs []string) ([]interfaces.RowFilterDecisionEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveRowFilters", ctx, refs)
	ret0, _ := ret[0].([]interfaces.RowFilterDecisionEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRowFilterServiceMockRecorder) ResolveRowFilters(ctx, refs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveRowFilters", reflect.TypeOf((*MockRowFilterService)(nil).ResolveRowFilters), ctx, refs)
}

// MockActionExecutionPermissionService is a mock of ActionExecutionPermissionService interface.
type MockActionExecutionPermissionService struct {
	ctrl     *gomock.Controller
	recorder *MockActionExecutionPermissionServiceMockRecorder
	isgomock struct{}
}

// MockActionExecutionPermissionServiceMockRecorder is the mock recorder for MockActionExecutionPermissionService.
type MockActionExecutionPermissionServiceMockRecorder struct {
	mock *MockActionExecutionPermissionService
}

// NewMockActionExecutionPermissionService creates a new mock instance.
func NewMockActionExecutionPermissionService(ctrl *gomock.Controller) *MockActionExecutionPermissionService {
	mock := &MockActionExecutionPermissionService{ctrl: ctrl}
	mock.recorder = &MockActionExecutionPermissionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionExecutionPermissionService) EXPECT() *MockActionExecutionPermissionServiceMockRecorder {
	return m.recorder
}

// RequirePermissions mocks base method.
func (m *MockActionExecutionPermissionService) RequirePermissions(ctx context.Context, requirements []interfaces.PermissionRequirement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequirePermissions", ctx, requirements)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequirePermissions indicates an expected call of RequirePermissions.
func (mr *MockActionExecutionPermissionServiceMockRecorder) RequirePermissions(ctx, requirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequirePermissions", reflect.TypeOf((*MockActionExecutionPermissionService)(nil).RequirePermissions), ctx, requirements)
}
