// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/vega_backend_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/vega_backend_access.go -destination ../interfaces/mock/mock_vega_backend_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-query/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVegaBackendAccess is a mock of VegaBackendAccess interface.
type MockVegaBackendAccess struct {
	ctrl     *gomock.Controller
	recorder *MockVegaBackendAccessMockRecorder
}

// MockVegaBackendAccessMockRecorder is the mock recorder for MockVegaBackendAccess.
type MockVegaBackendAccessMockRecorder struct {
	mock *MockVegaBackendAccess
}

// NewMockVegaBackendAccess creates a new mock instance.
func NewMockVegaBackendAccess(ctrl *gomock.Controller) *MockVegaBackendAccess {
	mock := &MockVegaBackendAccess{ctrl: ctrl}
	mock.recorder = &MockVegaBackendAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVegaBackendAccess) EXPECT() *MockVegaBackendAccessMockRecorder {
	return m.recorder
}

// QueryResourceData mocks base method.
func (m *MockVegaBackendAccess) QueryResourceData(ctx context.Context, resourceID string, params *interfaces.ResourceDataQueryParams) (*interfaces.DatasetQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryResourceData", ctx, resourceID, params)
	ret0, _ := ret[0].(*interfaces.DatasetQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryResourceData indicates an expected call of QueryResourceData.
func (mr *MockVegaBackendAccessMockRecorder) QueryResourceData(ctx, resourceID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryResourceData", reflect.TypeOf((*MockVegaBackendAccess)(nil).QueryResourceData), ctx, resourceID, params)
}
