// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/ontology_manager_access.go
//
// Generated by this command:
//
//	mockgen -source interfaces/ontology_manager_access.go -destination interfaces/mock/mock_ontology_manager_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-query/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOntologyManagerAccess is a mock of OntologyManagerAccess interface.
type MockOntologyManagerAccess struct {
	ctrl     *gomock.Controller
	recorder *MockOntologyManagerAccessMockRecorder
	isgomock struct{}
}

// MockOntologyManagerAccessMockRecorder is the mock recorder for MockOntologyManagerAccess.
type MockOntologyManagerAccessMockRecorder struct {
	mock *MockOntologyManagerAccess
}

// NewMockOntologyManagerAccess creates a new mock instance.
func NewMockOntologyManagerAccess(ctrl *gomock.Controller) *MockOntologyManagerAccess {
	mock := &MockOntologyManagerAccess{ctrl: ctrl}
	mock.recorder = &MockOntologyManagerAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOntologyManagerAccess) EXPECT() *MockOntologyManagerAccessMockRecorder {
	return m.recorder
}

// GetActionType mocks base method.
func (m *MockOntologyManagerAccess) GetActionType(ctx context.Context, knID, branch, atId string) (interfaces.ActionType, map[string]any, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionType", ctx, knID, branch, atId)
	ret0, _ := ret[0].(interfaces.ActionType)
	ret1, _ := ret[1].(map[string]any)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetActionType indicates an expected call of GetActionType.
func (mr *MockOntologyManagerAccessMockRecorder) GetActionType(ctx, knID, branch, atId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionType", reflect.TypeOf((*MockOntologyManagerAccess)(nil).GetActionType), ctx, knID, branch, atId)
}

// GetMetricDefinition mocks base method.
func (m *MockOntologyManagerAccess) GetMetricDefinition(ctx context.Context, knID, branch, metricID string) (*interfaces.MetricDefinition, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricDefinition", ctx, knID, branch, metricID)
	ret0, _ := ret[0].(*interfaces.MetricDefinition)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMetricDefinition indicates an expected call of GetMetricDefinition.
func (mr *MockOntologyManagerAccessMockRecorder) GetMetricDefinition(ctx, knID, branch, metricID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricDefinition", reflect.TypeOf((*MockOntologyManagerAccess)(nil).GetMetricDefinition), ctx, knID, branch, metricID)
}

// GetMetricExecutionContext mocks base method.
func (m *MockOntologyManagerAccess) GetMetricExecutionContext(ctx context.Context, knID, branch, metricID string) (*interfaces.MetricExecutionContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricExecutionContext", ctx, knID, branch, metricID)
	ret0, _ := ret[0].(*interfaces.MetricExecutionContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricExecutionContext indicates an expected call of GetMetricExecutionContext.
func (mr *MockOntologyManagerAccessMockRecorder) GetMetricExecutionContext(ctx, knID, branch, metricID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricExecutionContext", reflect.TypeOf((*MockOntologyManagerAccess)(nil).GetMetricExecutionContext), ctx, knID, branch, metricID)
}

// GetObjectType mocks base method.
func (m *MockOntologyManagerAccess) GetObjectType(ctx context.Context, knID, branch, otId string) (interfaces.ObjectType, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectType", ctx, knID, branch, otId)
	ret0, _ := ret[0].(interfaces.ObjectType)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetObjectType indicates an expected call of GetObjectType.
func (mr *MockOntologyManagerAccessMockRecorder) GetObjectType(ctx, knID, branch, otId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectType", reflect.TypeOf((*MockOntologyManagerAccess)(nil).GetObjectType), ctx, knID, branch, otId)
}

// GetRelationType mocks base method.
func (m *MockOntologyManagerAccess) GetRelationType(ctx context.Context, knID, branch, rtId string) (interfaces.RelationType, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationType", ctx, knID, branch, rtId)
	ret0, _ := ret[0].(interfaces.RelationType)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRelationType indicates an expected call of GetRelationType.
func (mr *MockOntologyManagerAccessMockRecorder) GetRelationType(ctx, knID, branch, rtId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationType", reflect.TypeOf((*MockOntologyManagerAccess)(nil).GetRelationType), ctx, knID, branch, rtId)
}

// GetRelationTypePathsBaseOnSource mocks base method.
func (m *MockOntologyManagerAccess) GetRelationTypePathsBaseOnSource(ctx context.Context, knID, branch string, query interfaces.PathsQueryBaseOnSource) ([]interfaces.RelationTypePath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationTypePathsBaseOnSource", ctx, knID, branch, query)
	ret0, _ := ret[0].([]interfaces.RelationTypePath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationTypePathsBaseOnSource indicates an expected call of GetRelationTypePathsBaseOnSource.
func (mr *MockOntologyManagerAccessMockRecorder) GetRelationTypePathsBaseOnSource(ctx, knID, branch, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationTypePathsBaseOnSource", reflect.TypeOf((*MockOntologyManagerAccess)(nil).GetRelationTypePathsBaseOnSource), ctx, knID, branch, query)
}

// GetRiskTypesByIDs mocks base method.
func (m *MockOntologyManagerAccess) GetRiskTypesByIDs(ctx context.Context, knID, branch string, riskTypeIDs []string) ([]interfaces.RiskType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRiskTypesByIDs", ctx, knID, branch, riskTypeIDs)
	ret0, _ := ret[0].([]interfaces.RiskType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRiskTypesByIDs indicates an expected call of GetRiskTypesByIDs.
func (mr *MockOntologyManagerAccessMockRecorder) GetRiskTypesByIDs(ctx, knID, branch, riskTypeIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRiskTypesByIDs", reflect.TypeOf((*MockOntologyManagerAccess)(nil).GetRiskTypesByIDs), ctx, knID, branch, riskTypeIDs)
}

// ListRelationTypes mocks base method.
func (m *MockOntologyManagerAccess) ListRelationTypes(ctx context.Context, knID, branch string, query interfaces.RelationTypesQuery) ([]interfaces.RelationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelationTypes", ctx, knID, branch, query)
	ret0, _ := ret[0].([]interfaces.RelationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRelationTypes indicates an expected call of ListRelationTypes.
func (mr *MockOntologyManagerAccessMockRecorder) ListRelationTypes(ctx, knID, branch, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelationTypes", reflect.TypeOf((*MockOntologyManagerAccess)(nil).ListRelationTypes), ctx, knID, branch, query)
}
