{{- if .Values.config.crypto.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.moduleName }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    module: {{ .Values.moduleName }}
type: Opaque
data:
  rsa_public_key.pem: {{ .Values.config.crypto.publicKey | required "RSA public key is required when config.crypto.enabled is true" | b64enc | quote }}

  rsa_private_key_pkcs8.pem: {{ .Values.config.crypto.privateKey | required "RSA private key is required when config.crypto.enabled is true" | b64enc | quote }}

{{- end }}