// Copyright openbkn.ai
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Package worker provides background workers for VEGA Manager.
package worker

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"

	"github.com/bytedance/sonic"
	"github.com/mohae/deepcopy"

	"vega-backend/interfaces"
	resourcelogic "vega-backend/logics/resource"
)

// buildIndexName returns the managed OpenSearch index name for a build task.
func buildIndexName(resourceID, buildTaskID string) string {
	return interfaces.BUILD_PREFIX + "-" + resourceID + "-" + buildTaskID
}

// parseBuildIndexName parses a managed build index name into its Resource and Build Task IDs.
// Both IDs are generated by Vega and must not contain '-'.
func parseBuildIndexName(indexName string) (resourceID, buildTaskID string, ok bool) {
	prefix := interfaces.BUILD_PREFIX + "-"
	if !strings.HasPrefix(indexName, prefix) {
		return "", "", false
	}
	parts := strings.Split(strings.TrimPrefix(indexName, prefix), "-")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", false
	}
	return parts[0], parts[1], true
}

// generateDocumentID builds a document ID from ordered build-key values.
func generateDocumentID(keys []interfaces.KeyValue) (string, error) {
	if len(keys) == 0 {
		return "", fmt.Errorf("build document ID: no build key fields")
	}

	for _, key := range keys {
		if key.Value == nil {
			return "", fmt.Errorf("build document ID: build key field %q is null", key.Key)
		}
		if stringValue, ok := key.Value.(string); ok && stringValue == "" {
			return "", fmt.Errorf("build document ID: build key field %q is empty", key.Key)
		}
	}

	serialized, err := sonic.Marshal(keys)
	if err != nil {
		return "", fmt.Errorf("marshal build key values: %w", err)
	}
	sum := sha256.Sum256(serialized)
	return hex.EncodeToString(sum[:]), nil
}

func extractKeyValues(fields []string, document map[string]any) ([]interfaces.KeyValue, error) {
	if document == nil {
		return nil, fmt.Errorf("build document ID: document is required")
	}

	values := make([]interfaces.KeyValue, 0, len(fields))
	for _, field := range fields {
		value, exists := document[field]
		if !exists {
			return nil, fmt.Errorf("build document ID: build key field %q is missing", field)
		}
		values = append(values, interfaces.KeyValue{Key: field, Value: value})
	}
	return values, nil
}

// updateResourceIndexName updates the index name of a resource
func updateResourceIndexName(ctx context.Context, resource *interfaces.Resource, rs interfaces.ResourceService, indexName string) error {
	if resource.LocalIndexName == indexName {
		return nil
	}

	if err := rs.InternalUpdateLocalIndexName(ctx, nil, resource.ID, indexName); err != nil {
		return err
	}
	resource.LocalIndexName = indexName

	return nil
}

func validateBuildTaskResourceFingerprint(resource *interfaces.Resource, buildTask *interfaces.BuildTask) error {
	if buildTask == nil || buildTask.IndexConfig == nil {
		return errors.New("build task has no index config snapshot")
	}
	taskFingerprint, err := resourcelogic.BuildTaskIndexConfigFingerprint(buildTask.IndexConfig)
	if err != nil {
		return fmt.Errorf("calculate build task index config fingerprint: %w", err)
	}
	fingerprint, err := resourcelogic.ResourceIndexConfigFingerprint(resource)
	if err != nil {
		return fmt.Errorf("calculate resource index config fingerprint: %w", err)
	}
	if fingerprint != taskFingerprint {
		return errors.New("resource index config has changed")
	}
	return nil
}

func cancelBuildTaskForDeletedParent(ctx context.Context, bts interfaces.BuildTaskService, taskID, detail string) error {
	_, err := bts.InternalMarkCancelled(ctx, nil, taskID, detail)
	return err
}

// createManagedLocalIndex creates a build-task local index through LocalIndexManager.
func createManagedLocalIndex(ctx context.Context, lim interfaces.LocalIndexManager, indexName string, buildTask *interfaces.BuildTask, resource *interfaces.Resource) error {
	schema, err := buildLocalIndexSchema(buildTask, resource)
	if err != nil {
		return err
	}
	exist, err := lim.CheckIndexExist(ctx, indexName)
	if err != nil {
		return fmt.Errorf("check local index exist failed: %w", err)
	}
	if exist {
		return nil
	}
	return lim.CreateIndex(ctx, indexName, schema)
}

func recreateManagedLocalIndex(ctx context.Context, lim interfaces.LocalIndexManager, indexName string,
	buildTask *interfaces.BuildTask, resource *interfaces.Resource) error {
	schema, err := buildLocalIndexSchema(buildTask, resource)
	if err != nil {
		return err
	}
	exists, err := lim.CheckIndexExist(ctx, indexName)
	if err != nil {
		return fmt.Errorf("check local index exist failed: %w", err)
	}
	if exists {
		if err := lim.DeleteIndex(ctx, indexName); err != nil {
			return fmt.Errorf("delete local index before full rebuild: %w", err)
		}
	}
	return lim.CreateIndex(ctx, indexName, schema)
}

func requireManagedLocalIndex(ctx context.Context, lim interfaces.LocalIndexManager, indexName string) error {
	exists, err := lim.CheckIndexExist(ctx, indexName)
	if err != nil {
		return fmt.Errorf("check local index exist failed: %w", err)
	}
	if !exists {
		return errors.New("cannot resume full build because its local index is missing")
	}
	return nil
}

func buildLocalIndexSchema(buildTask *interfaces.BuildTask, resource *interfaces.Resource) ([]*interfaces.Property, error) {
	var schema []*interfaces.Property
	if resource.SchemaDefinition != nil {
		schemaDefinition, ok := deepcopy.Copy(resource.SchemaDefinition).([]*interfaces.Property)
		if !ok {
			return nil, fmt.Errorf("copy resource schema failed")
		}
		schema = schemaDefinition
	}

	// Legacy resources that have never been updated still contain self-references. Without normalization,
	// dataset resources violate the ref_property restriction and keyword self-references on text fields
	// fail ref type validation (keyword requires string), preventing build task creation. Apply this only
	// to the deep copy above; leave the resource row unchanged so its next update can repair it.
	resourcelogic.NormalizeSelfReferencingFeatures(schema)

	if err := validateBuildTaskSchemaFeatures(resource.Category, schema); err != nil {
		return nil, err
	}
	if err := validateTaskFulltextFeatures(schema, buildTask); err != nil {
		return nil, err
	}
	if err := validateTaskEmbeddingFeatures(schema, buildTask); err != nil {
		return nil, err
	}
	return appendTaskEmbeddingVectorFields(schema, buildTask), nil
}

func validateBuildTaskSchemaFeatures(resourceCategory string, schema []*interfaces.Property) error {
	propsMap := make(map[string]*interfaces.Property, len(schema))
	for _, prop := range schema {
		if prop != nil {
			propsMap[prop.Name] = prop
		}
	}

	for _, prop := range schema {
		if prop == nil {
			continue
		}
		for _, feature := range prop.Features {
			if !resourcelogic.IsFeatureSupported(prop.Type, feature.FeatureType) {
				return fmt.Errorf("resource schema field %q type %q does not support feature type %q", prop.Name, prop.Type, feature.FeatureType)
			}
			if feature.RefProperty == "" {
				continue
			}
			if resourceCategory == interfaces.ResourceCategoryDataset {
				return fmt.Errorf("dataset schema feature on field %q must not set ref_property", prop.Name)
			}
			refProp, exists := propsMap[feature.RefProperty]
			if !exists {
				return fmt.Errorf("resource schema feature on field %q references missing property %q", prop.Name, feature.RefProperty)
			}
			if !resourcelogic.IsFeatureRefPropertyTypeSupported(refProp.Type, feature.FeatureType) {
				return fmt.Errorf("resource schema feature on field %q references property %q type %q incompatible with feature type %q", prop.Name, feature.RefProperty, refProp.Type, feature.FeatureType)
			}
		}
	}
	return nil
}

func appendTaskEmbeddingVectorFields(schema []*interfaces.Property, buildTask *interfaces.BuildTask) []*interfaces.Property {
	newSchema := append([]*interfaces.Property{}, schema...)
	for field, feature := range buildTaskIndexFeatures(buildTask) {
		if feature.Vector == nil {
			continue
		}
		newSchema = append(newSchema, &interfaces.Property{
			Name: interfaces.LocalIndexVectorFieldName(field),
			Type: interfaces.DataType_Vector,
			Features: []interfaces.PropertyFeature{
				{
					FeatureType: interfaces.DataType_Vector,
					Config: map[string]any{
						"dimension": feature.Vector.EmbeddingDim,
						"method": map[string]any{
							"name":   "hnsw",
							"engine": "lucene",
							"parameters": map[string]any{
								"ef_construction": 256,
							},
						},
					},
				},
			},
		})
	}
	return newSchema
}

func buildTaskIndexFeatures(buildTask *interfaces.BuildTask) map[string]interfaces.BuildTaskFieldIndexFeature {
	if buildTask == nil || buildTask.IndexConfig == nil {
		return nil
	}
	return buildTask.IndexConfig.Features
}

func buildTaskHasEmbedding(buildTask *interfaces.BuildTask) bool {
	for _, feature := range buildTaskIndexFeatures(buildTask) {
		if feature.Vector != nil {
			return true
		}
	}
	return false
}

func buildTaskBuildKeyFields(buildTask *interfaces.BuildTask) []string {
	if buildTask == nil || buildTask.IndexConfig == nil {
		return nil
	}
	return append([]string(nil), buildTask.IndexConfig.BuildKeyFields...)
}

// The hasFulltextFeature determines whether a field already has the fulltext feature.
func hasFulltextFeature(prop *interfaces.Property) bool {
	for _, f := range prop.Features {
		if f.FeatureType == interfaces.PropertyFeatureType_Fulltext {
			return true
		}
	}
	return false
}

// analyzerOf returns the analyzer name from fulltext feature configuration, or an empty string when absent.
func analyzerOf(config map[string]any) string {
	if config == nil {
		return ""
	}
	if v, ok := config["analyzer"].(string); ok {
		return v
	}
	return ""
}

func validateTaskFulltextFeatures(schema []*interfaces.Property, buildTask *interfaces.BuildTask) error {
	fulltextConfigs := map[string]*interfaces.BuildTaskFulltextConfig{}
	for field, feature := range buildTaskIndexFeatures(buildTask) {
		if feature.Fulltext != nil {
			fulltextConfigs[field] = feature.Fulltext
		}
	}

	schemaFulltextFields := map[string]struct{}{}
	for _, prop := range schema {
		if prop == nil {
			continue
		}
		for i := range prop.Features {
			feature := &prop.Features[i]
			if feature.FeatureType != interfaces.PropertyFeatureType_Fulltext {
				continue
			}
			fieldName := indexFeatureFieldName(prop, *feature)
			schemaFulltextFields[fieldName] = struct{}{}
			fulltextConfig, ok := fulltextConfigs[fieldName]
			if !ok {
				return fmt.Errorf("resource schema fulltext field %q is not in build task index config", fieldName)
			}
			taskAnalyzer := fulltextConfig.Analyzer
			schemaAnalyzer := analyzerOf(feature.Config)
			if schemaAnalyzer != "" && schemaAnalyzer != taskAnalyzer {
				return fmt.Errorf("resource schema fulltext analyzer %q for field %q does not match build task analyzer %q", schemaAnalyzer, fieldName, taskAnalyzer)
			}
			if taskAnalyzer != "" && schemaAnalyzer == "" {
				feature.Config = map[string]any{"analyzer": taskAnalyzer}
			}
		}
	}
	for field := range fulltextConfigs {
		if _, ok := schemaFulltextFields[field]; !ok {
			return fmt.Errorf("build task fulltext field %q is not in resource schema features", field)
		}
	}
	return nil
}

func validateTaskEmbeddingFeatures(schema []*interfaces.Property, buildTask *interfaces.BuildTask) error {
	embeddingFields := map[string]struct{}{}
	for field, feature := range buildTaskIndexFeatures(buildTask) {
		if feature.Vector != nil {
			embeddingFields[field] = struct{}{}
		}
	}

	schemaEmbeddingFields := map[string]struct{}{}
	for _, prop := range schema {
		if prop == nil {
			continue
		}
		for _, feature := range prop.Features {
			if feature.FeatureType != interfaces.PropertyFeatureType_Vector {
				continue
			}
			fieldName := indexFeatureFieldName(prop, feature)
			schemaEmbeddingFields[fieldName] = struct{}{}
			if _, ok := embeddingFields[fieldName]; !ok {
				return fmt.Errorf("resource schema embedding field %q is not in build task index config", fieldName)
			}
		}
	}
	for field := range embeddingFields {
		if _, ok := schemaEmbeddingFields[field]; !ok {
			return fmt.Errorf("build task embedding field %q is not in resource schema features", field)
		}
	}
	return nil
}

func indexFeatureFieldName(prop *interfaces.Property, feature interfaces.PropertyFeature) string {
	if feature.RefProperty != "" {
		return feature.RefProperty
	}
	return prop.Name
}
