name: release-trace-ai-agent-observability

on:
  push:
    branches: ['**']
    paths:
      - 'trace-ai/agent-observability/**'
      - '.github/workflows/release-trace-ai-agent-observability.yml'
      - '.github/workflows/reusable-*.yml'
  workflow_dispatch:

jobs:
  diag-chart:
    uses: ./.github/workflows/reusable-chart.yml
    with:
      service-path: trace-ai/agent-observability
      chart-path: charts/agent-observability
      chart-name: agent-observability
      version: 'diag-0.0.1'
      publish: false
